### ISSUE TITLE
Add a test-build-config batch file for Windows builds

### ISSUE THREAD

**Issue by johnkord** [Microsoft/openenclave#1002]

**Comment by dragoshsch** [comment]
@johnkord I created PR #1108 to solve this.

**Comment by ionutbalutoiu** [comment]
The PR https://github.com/Microsoft/openenclave/pull/1108 merged. Closing this.

**Comment by johnkord** [comment]
As of #1143 this change was reverted. That PR reverted the Jenkinsfile back to the previous non-scripted version, and that doing so reverted this batch->powershell change. However,there was an issue that @CodeMonkeyLeet noticed this morning that originally led us down this path of investigation: https://oe-jenkins.eastus.cloudapp.azure.com/blue/organizations/jenkins/Bors/detail/staging/288/pipeline/32
![failed powershell but success](https://user-images.githubusercontent.com/16021727/49325049-6cd49680-f4f0-11e8-8e9e-590e029c1f00.PNG)

Note that powershell isn't able to find the script it's trying to run and fails, but somehow Jenkins reports it as a successful step. I imagine it wasn't able to find the powershell script to run due to issue #1148 which seemed to somehow prevent git checkout/cleanup from working for the Windows stages.

**Comment by dragoshsch** [comment]
@johnkord This happens because an exit code isn't set automatically by the PowerShell plugin, so we solved this in PR #1150 by using a wrapper to call PowerShell commands.

**Comment by johnkord** [comment]
This should be resolved now as per #1150
