### ISSUE TITLE
Investigate `get_c_compiler_dir.sh` script

### ISSUE THREAD

**Issue by andschwa** [Microsoft/openenclave#1017]
There exists a script we run during CMake configuration that does "magic" and sets the variable `OE_C_COMPILER_INCDIR` which is later used by several targets. The explanation is "obtain default compiler include holding the intrinsics," but we need to figure out why this exists and if there is a better way to do it.

**Comment by radhikaj** [comment]
https://stackoverflow.com/questions/40055022/cmake-how-to-choose-c-headers
From here it seems that you have to explicitly set include paths for each of your compilers while using cmake. I am investigating further to see if there is a different way to do this.

**Comment by radhikaj** [comment]
I also found this. I am unable to figure out where the compiler provided intrinsics are stripped.

# we strip the default include containing the compiler-provided intrinsics
# add it back in
#target_include_directories(oecore SYSTEM PRIVATE {OE_C_COMPILER_INCDIR})
