### ISSUE TITLE
oe_create_enclave(): result=1 in Azure Confidential Cloud

### ISSUE THREAD

**Issue by novikov-alexander** [Microsoft/openenclave#1025]
I've created a VM in the Azure Confidential Cloud with preinstalled open enclave library.
All of samples worked fine. Then I removed open-enclave library.
Then I cloned and build the last version of openenclave from github via steps written in documentation.
Almost all tests are failed. Each failed test and sample write "oe_create_enclave(): result=1". What does it mean and how to fix it?

**Comment by anakrish** [comment]
@novikov-alexander 
Just to rule it out, can you check the kernel version to see if the kernel has been updated?
What we know is that whenever the kernel is updated, the intel sgx drivers need to be installed again.

**Comment by novikov-alexander** [comment]
@anakrish 
4.15.0-1022-azure

I think the problem is not in the kernel because package installed via "apt" works fine.

**Comment by novikov-alexander** [comment]
I've reinstalled the driver. It doesn't help

**Comment by anakrish** [comment]
Thanks @novikov-alexander.
Interesting. On my VM uname -a gives:
Linux accVM **4.15.0-1023-azure** #24~16.04.1-Ubuntu SMP Wed Aug 29 12:54:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

Can you give @dmitsh access to your VM?

**Comment by novikov-alexander** [comment]
@anakrish How to do it(give access)?


I've tried to recreate VMs in West America and East Europe regions yesterday. Both of them have (4.15.0-1022-azure kernel)

**Comment by novikov-alexander** [comment]
@dmitsh How to do it better (give access to you)?

**Comment by novikov-alexander** [comment]
@anakrish  I've just updated the kernel to 4.15.0-1025-azure, reinstalled the driver and everything began to work! So, the problem was in the kernel.

Thank you!
