### ISSUE TITLE
Add separate build configuration for Windows to build and test PE enclaves.

### ISSUE THREAD

**Issue by CodeMonkeyLeet** [Microsoft/openenclave#1035]
The current build configuration for Windows allows only the host components to tests to be executed on Windows and for the enclave binaries to be sourced from a prior build on Linux. With the introduction of PE enclaves that can be compiled and run on Windows, we will need to add a new build configuration to test enclaves compiled and executed entirely on Windows.

**Comment by johnkord** [comment]
@CodeMonkeyLeet Is this an issue we should keep open, are we intending to do it any time soon?

**Comment by CodeMonkeyLeet** [comment]
@johnkord There will still be ci/cd changes to support the updated plan of supporting Windows-only build through clang cross-compile (see #1264, #1272), so we will likely spin up a new task/repurpose this one. I need to do a pass on these.

**Comment by CodeMonkeyLeet** [comment]
Closing out issues related to Windows PE enclave support until we find a use case. CI changes for cross-compile configuration for Windows has been done (see  #1272, #1415).
