### ISSUE TITLE
Logging:  Need to add logging mechanism in to the SDK

### ISSUE THREAD

**Issue by soccerGB** [Microsoft/openenclave#1045]
The current OE SDK has no logging at all, which makes triage any OE SDK issues outside of a dev machine impossible.

The logging in question here is for the OE SDK itself, not the client's OE enclave.
Given the OE SDK open source, developers can exam the source code for what's actually logged, as long as we make sure no sensitive information logged, there should have no trust issue here.

**Comment by soccerGB** [comment]
Logging: Need to add logging mechanism in to the SDK
 
The logging type is for adding instrumentation into the OE SDK itself, not the client's OE enclave. This is pure for the purpose of helping us triaging/debugging OE SDK issues without the need of accessing to the remote machine, it would also help OE application debugging .
While the logging is on, it might impact enclave performance, we could make it an enclave-controllable configuration, they can turn on/off and default could be off.  The type of debugging has much less security concern here because OE SDK is opened source, users of OE  SDK can be assured of no secret/personal information will be logged to the host. This guarantee is similar to the enclave code trusts our open-source OE SDK.  The goal is to make sure we log enough details (but no secret from enclave ) in OE SDK session so that we could root most of the OE SDK issues report from a remote user should they decide to share it with us.

**Comment by soccerGB** [comment]
Proposal:

# Open Enclave SDK tracing

   Supports logging OE SDK API operations to console or file by setting logging level and flags configuration through host environment variables. 
   
## What would be logged?

### Inside the enclaves

- Enclaves created with OE_ENCLAVE_FLAG_DEBUG flag will honor logging options set in above environment varaibles
- Production encalves (no OE_ENCLAVE_FLAG_DEBUG) will have logging disabled by default. It will have to call oe_enable_sdk_logging(`true`) , a new api, to opt in for logging. It could be dynamically opt-out with oe_enable_sdk_logging(`false`) call.

### On the host application side

   OE SDK will conduct its logging according to the logging options in the environment varaibles

# Logging evvironment variables

- OE_LOG_PATH:  log filenname, logging goes to console if not set. 
                All loggings(including host and all enclaves laoded by the same host)  go to the same log file.
- OE_LOG_LEVEL: logging level
- OE_LOG_FLAGS: flags for specifying function areas to log

  Example:
  
      OE_LOG_PATH=test.log 
      OE_LOG_LEVEL=ERROR 
      OE_LOG_FLAGS=0xffffffff  
      
When no OE_LOG_* environemnt variables were found, here are that default values: 

      All logging goes to console
      Level is default to OE_LOG_LEVEL_ERROR
      Flags are set to OE_LOG_FLAGS_ALL
     
  
## Log levels

```c
      typedef enum _log_level_ {
          OE_LOG_LEVEL_NONE = 0,
          OE_LOG_LEVEL_ERROR,
          OE_LOG_LEVEL_WARNING,
          OE_LOG_LEVEL_INFO,
          OE_LOG_LEVEL_MAX
      } log_level_t;
```

## Log flags

```c
    #define OE_LOG_FLAGS_NONE           0x00000000
    #define OE_LOG_FLAGS_ATTESTATION    0x00000001
    #define OE_LOG_FLAGS_GET_REPORT     0x00000002
    #define OE_LOG_FLAGS_VERIFY_REPORT  0x00000004
    #define OE_LOG_FLAGS_COMMON         0x00000008
    #define OE_LOG_FLAGS_CERT           0x00000010
    #define OE_LOG_FLAGS_TOOLS          0x00000020
    #define OE_LOG_FLAGS_CRYPTO         0x00000040
    #define OE_LOG_FLAGS_SGX_SPECIFIC   0x00000100
    #define OE_LOG_FLAGS_IMAGE_LOADING  0x00000200
    #define OE_LOG_FLAGS_OTHERS         0x00000400
    #define OE_LOG_FLAGS_ALL            0xffffffff
```   

# Key changes:

## Four internal macros are added

There are added for instrumenting OE SDK code. 
```c
#define OE_TRACE(level, ...)                    \
    do                                          \
    {                                           \
        oe_log(trace_flag, level, __VA_ARGS__); \
    } while (0)

#define OE_TRACE_ERROR(fmt, ...) \
    OE_TRACE(                    \
        OE_LOG_LEVEL_ERROR,      \
        fmt " @%s %s:%d\n",      \
        ##__VA_ARGS__,           \
        __FILE__,                \
        __FUNCTION__,            \
        __LINE__)

#define OE_TRACE_WARNING(fmt, ...) \
    OE_TRACE(                      \
        OE_LOG_LEVEL_WARNING,      \
        fmt "[%s %s:%d]\n",        \
        ##__VA_ARGS__,             \
        __FILE__,                  \
        __FUNCTION__,              \
        __LINE__)

#define OE_TRACE_INFO(fmt, ...) \
    OE_TRACE(                   \
        OE_LOG_LEVEL_INFO,      \
        fmt "[%s %s:%d]\n",     \
        ##__VA_ARGS__,          \
        __FILE__,               \
        __FUNCTION__,           \
        __LINE__)
```
## New public enclave API: 
      An enclave can use this API to opt-in SDK logging for the enclave operations
      void oe_enable_sdk_logging(bool enabled) for opt-in and opt-out enclave logging

# OE_RAISE 

   The OE_RAISE macros is re-defined to use OE_TRACE_ERROR()
   
Example:

      ~/install-active/share/openenclave/samples/remote_attestation$ OE_LOG_PATH=test.log OE_LOG_LEVEL=ERROR OE_LOG_FLAGS=0xffffffff  host/attestation_host ./enc1/enclave1.signed.so ./enc2/enclave2.signed.so

      ================= New logging session =================
      21:25:51 (H)Failed::OE_INVALID_QE_IDENTITY_INFO @/home/soccerl/active/host/sgxquoteprovider.c oe_get_qe_identity_info:345
      21:25:51 (E)enclave2.signed.so:Failed::OE_INVALID_QE_IDENTITY_INFO @/home/soccerl/active/enclave/qeidinfo.c oe_get_qe_identity_info:71
      21:25:51 (E)enclave2.signed.so:Failed::OE_INVALID_PARAMETER @/home/soccerl/active/enclave/cert.c oe_cert_chain_free:678
      21:25:51 (E)enclave2.signed.so:Failed::OE_INVALID_QE_IDENTITY_INFO @/home/soccerl/active/enclave/report.c oe_verify_report:81

**Comment by dthaler** [comment]
I think the "OE_LOG_PATH" part of the proposal is too limited, in that it assumes that the log is stored as a file in the untrusted file system.   Instead I think it should be designed more like we discussed for files and sockets, where there's different providers with different security semantics.

**Comment by soccerGB** [comment]
https://github.com/Microsoft/openenclave/pull/1118
