### ISSUE TITLE
Expand the OE SDK CI system to cover Microsoft/Azure-DCAP-Client repo

### ISSUE THREAD

**Issue by soccerGB** [Microsoft/openenclave#1048]
For any OE application to conduct remote-attestation successfully on Azure environment, a working Microsoft/Azure-DCAP-Client , built from repo (https://github.com/Microsoft/Azure-DCAP-Client) is essential.

We want to make sure no regressing changes were merged into Microsoft/Azure-DCAP-Client repo

**Comment by ionutbalutoiu** [comment]
This is the `WiP` PR for this https://github.com/Microsoft/Azure-DCAP-Client/pull/9

**Comment by ionutbalutoiu** [comment]
Closing this one since the following pull requests enabled successful OE CI with the latest `Microsoft/Azure-DCAP-Client` code:

- https://github.com/Microsoft/Azure-DCAP-Client/pull/9
- https://github.com/Microsoft/Azure-DCAP-Client/pull/15
