### ISSUE TITLE
Fix Jenkins pipeline to treat skipped stage as failed

### ISSUE THREAD

**Issue by andschwa** [Microsoft/openenclave#1057]
As worked around in #1012, Jenkins will not treat a build as failed if a stage is skipped. This is problematic because it means that with manual intervention, it was possible to skip e.g. `check-precommit-reqs`, and that meant it was possible to merge code to master that actually failed the build.

We've worked around this by moving all stages into a single parallel stage such that there is "only one" stage according to Jenkins. This is far from ideal, however, as we will want to have multiple stages, and per #1029, we had to disable fail-fast semantics, which means that every build now runs to completion even if the `check-precommit-reqs` tests fail.

/cc @johnkord

**Comment by oprinmarius** [comment]
@andschwa 
Currently there is no way to report Skipped stages as failed with Declarative Pipeline (The one we have in Jenkinsfiel), but we have several options to implement:

1. We can install a plugin and disable  "Restart from stage" option completely. In this way every build can only be triggered from the start.
2. We can re-write the Jenkinsfile as Scripted Pipeline , and manually check the status of each stage , and if it has run. If a stage is skipped we can report it as failed.

Please let me know your thoughts

**Comment by andschwa** [comment]
Hm. It's a tough choice.

On the one hand, scripted pipelines are a lot more powerful, and as we continue to run into problems with declarative pipelines, rewriting them into scripted pipelines becomes an enticing choice.

But that's also a rather high cost to pay when disabling "restart from stage" is a choice, and one that I think we'd want to make regardless.

So I would suggest to install that plugin and disable "restart from stage" for now, and if we encounter yet another compelling reason to rewrite the scripts, we can do so then. (This will probably happen as we add post-build/test stages.)

**Comment by oprinmarius** [comment]
@andschwa I installed the Job restrictions plugin but unfortunately project restrictions cannot be enabled for Multi-branch pipelines.
Re-writing the Jenkinsfile as Scripted remains our only option.
