### ISSUE TITLE
Determine how to safely perform a Windows update on Windows CI systems

### ISSUE THREAD

**Issue by johnkord** [Microsoft/openenclave#1062]
The last time I performed a Windows update on the Windows CI system that we use, the Jenkins agent started throwing several errors around every 5 minutes or so, complaining about dropping a connection. Investigation needs to be done into how to safely perform Windows updates on Windows CI systems.

**Comment by ahapliuc** [comment]
I have disabled automatic windows updates for now. When we will deploy the new agents, we will always deploy the latest images.
