### ISSUE TITLE
Use Ansible to make Jenkins master redeployable

### ISSUE THREAD

**Issue by johnkord** [Microsoft/openenclave#1063]
Configuring a newly deployed system for CI requires some manual invocation of commands after provisioning. For example, on a Linux ACC node, there are some scripts that need to be run manually in order to configure ssh keys, install java, install docker, etc. It's more complicated for redeploying the host for the Jenkins CI system.

I'd like to see all of this information be encapsulated into a Puppet/Ansible/DSC configuration that can be applied to a newly deployed system.

**Comment by ahapliuc** [comment]
@johnkord do you have some tips on how Jenkins was deployed? This would help us test and validate the way that we deploy the CI agents.

**Comment by johnkord** [comment]
Closing this because we agreed that this wasn't necessary and more work than it is work.
