### ISSUE TITLE
Conditionally set HeapPageCount for tests

### ISSUE THREAD

**Issue by andschwa** [Microsoft/openenclave#1066]
The `HeapPageCount` for libcxx tests were increased from 8192 to 12288 by VVDN with the libcxx upgrade to 7.0 presumably because one test needed the extra 4k pages. Since there is one wrapper for all the libcxx tests, all the tests got the extra heap page count.

Since we merged libcxxthrd with libcxx, the extra heap pages now are applied to all the tests.

Is there an elegant way to use the extra heap pages for only the test that needs it instead of all tests?

**Comment by andschwa** [comment]
This was originally from @anitagov, and I did not want it to get lost in my email.

**Comment by johnkord** [comment]
@anitagov Can you look at this and close this if it is no longer relevant?

**Comment by anitagov** [comment]
Closing this as this cannot be done in its current state. We may run into problems when libcxx ELF enclaves are enabled to run on Windows.
