### ISSUE TITLE
libunwind tests link to .libs/libunwind-x86_64.a *and* to .libs/libunwind.a but don't use the interface library

### ISSUE THREAD

**Issue by andschwa** [Microsoft/openenclave#1068]
It's strange, see the graph:

![libunwind](https://user-images.githubusercontent.com/2226434/48381759-64780100-e692-11e8-8b07-4ff44f39ecc0.PNG)

We should probably have `libunwindtest-support` link the correct one transitively.

**Comment by andschwa** [comment]
@mikbras Do you have any historical context?

**Comment by mikbras** [comment]
Hi Andy. The tests were written by VVDN. I'm not sure what they are doing or are suppose to do.

What is the "interface library"?

**Comment by andschwa** [comment]
Ah, it is not an interface library, it's a static library: `libunwindtest-support` (but its interface still can/should be used to link the right library).

What is "VVDN"?

**Comment by andschwa** [comment]
These are the confusing lines, they were last edited by you and "arjunvnambiar":

```
    target_link_libraries(libunwindtest-${NAME}_enc libunwindtest-support)
    target_link_libraries(libunwindtest-${NAME}_enc ${LIBUNWIND_LIB_DIR}/libunwind-x86_64.a ${LIBUNWIND_LIB_DIR}/libunwind.a)
    target_link_libraries(libunwindtest-${NAME}_enc oelibc oelibcxx oeenclave)
```

**Comment by andschwa** [comment]
I'm closing this in favor of #1128, as that will require this to be fixed.
