### ISSUE TITLE
oe_ptrace appears as an orphaned node in CMake graph

### ISSUE THREAD

**Issue by andschwa** [Microsoft/openenclave#1073]
Nothing depends on it.

**Comment by anakrish** [comment]
I think it is intended for use by the debugger.
I will have to figure out how it is loaded/used by the debugger.

**Comment by anitagov** [comment]
Anand is right. Here is info from the README.md file. 
The oe_ptrace library implements the customized ptrace and waitpid function to get and set 
enclave registers, and fix the enclave breakpoint. **It is preloaded into the GDB by oe-gdb script.**

**Comment by andschwa** [comment]
Ah, thank you! Let's get a comment to that effect in the library's `CMakeLists.txt`, since it appears as an orphaned node in the graph.

**Comment by andschwa** [comment]
I am just going to close this as I think the issue is enough of a note for anyone who wonders in the future.
