### ISSUE TITLE
Improve oe_create_enclave error messages

### ISSUE THREAD

**Issue by letmaik** [Microsoft/openenclave#1074]
There are situations where `oe_create_enclave()` returns code 1 which `oe_result_str()` resolves to "OE_FAILURE". This doesn't say anything really. It would be good to distinguish more error conditions and expose them appropriately.

**Comment by CodeMonkeyLeet** [comment]
One specific example: The PE enclave work (#811) introduced invoking `OE_SET_ENCLAVE_SGX` by default in enclave/core/properties.c with undefined values so as to reserve the constant data section in the resulting PE file for signing later. 

If the app dev doesn't call `OE_SET_ENCLAVE_SGX` with valid values, or override them with valid values during signing, then `oe_create_enclave()` fails with the opaque `OE_FAILURE` return, whereas we could now specifically catch this condition and return a more meaningful error by trapping the "undefined" values in the .oeinfo.

**Comment by CodeMonkeyLeet** [comment]
Some work was done to distinguish error codes with `OE_PLATFORM_ERROR` and there is continuing work in #1387 to also log the underlying errors. Using the newer issue to track further improvements in this area.
