### ISSUE TITLE
Set USE_LIBSGX to ON by default

### ISSUE THREAD

**Issue by andschwa** [Microsoft/openenclave#1076]
This was a separate part of #969 that we pulled out.

Instead of requiring users to build with `cmake -DUSE_LIBSGX` on SGX-enabled machines, we should just use `find_library` to detect the SGX library, and if found, enable it. (If it's not found, we need to emit a warning that we're only building in simulation mode).

**Comment by radhikaj** [comment]
A machine that has SGX+FLC capability can be used in SGX1 mode or SGX1+FLC mode or simulation mode. Similarly, a SGX1 machine can be used in SGX1 mode or simulation mode.

**Comment by anakrish** [comment]
@radhikaj 
It might make sense to default to the most commonly used scenario, if possible after detecting the hardware capabilities. I would like USE_LIBSGX=1 to be the default since Coffee Lake machines are the common ones we have.

**Comment by andschwa** [comment]
So I did part of this in #1276. That is, if `USE_LIBSGX=ON` but the libraries are _not_ found at configuration time, we now fatally error with a message. I'm opening a separate PR to change the default to ON instead of OFF.

**Comment by andschwa** [comment]
This was resolved by #1279.
