### ISSUE TITLE
Need samples for demonstrating multi-thread usage in enclaves

### ISSUE THREAD

**Issue by anitagov** [Microsoft/openenclave#1089]
OE samples need to be extended to demonstrate multi-thread usage in enclaves. 
Since threads cannot be created in enclaves, they are created on the host and then used by the enclave. Creation, Join and Detach of threads are done only on the host.
These samples should also demonstrate creation/joining/detaching of threads using pthread_create/pthread_join/pthread_detach hooks/shim layer.

**Comment by johnkord** [comment]
Closing this issue as won't fix.
