### ISSUE TITLE
Broken libc-test

### ISSUE THREAD

**Issue by berinpaul** [microsoft/openenclave#1090]
The test ../../3rdparty/musl/libc-test/src/functional/tls_align.c is currently broken since the sixth program header of the elf object is of type TLS. Application raises `OE_UNSUPPORTED` at `host/loadelf.c:169`.

**Comment by anitagov** [comment]
@mikbras -- This broke 18 days back with the elf changes.

**Comment by johnkord** [comment]
@anitagov Have you looked at this? Do you know if this is fixed now?

**Comment by johnkord** [comment]
We've assigned this to you, @anitagov , can you give us a status update on it when you get a chance to take a look? :)

**Comment by anitagov** [comment]
Enabling this test back with my PR #1508  as it seems to be passing with the latest libc version.

**Comment by anitagov** [comment]
Fixed with PR #1508 and hence closing
