### ISSUE TITLE
Libcxx functional tests that require C++17 flag

### ISSUE THREAD

**Issue by anitagov** [Microsoft/openenclave#1091]
Pulling this issue out of #151 as the following require C++17 support. After upgrade to libcxx 7.0, the library supports C++17. So, these can be enabled when we decide to build libcxx  enclave tests with C++17. We currently build with C++14 flag.
3rdparty/libcxx/libcxx/test/libcxx/language.support/support.dynamic/new_faligned_allocation.sh.cpp
3rdparty/libcxx/libcxx/test/std/algorithms/alg.sorting/alg.clamp/clamp.comp.pass.cpp
3rdparty/libcxx/libcxx/test/std/algorithms/alg.sorting/alg.clamp/clamp.pass.cpp
3rdparty/libcxx/libcxx/test/std/language.support/support.types/byte.pass.cpp

**Comment by johnkord** [comment]
Closing as won't fix for now, until we plan to support C++17.
