### ISSUE TITLE
Apply -ffreestanding to all enclave objects.

### ISSUE THREAD

**Issue by mikbras** [Microsoft/openenclave#1094]
The **tests/fs** enclave was crashing when calling **fread** and **fwrite** (using **Clang** in release mode). This is caused built-in **fread** and **fwrite** calls (note that **oelibc** provides its own version of these functions, which are never reached due to the optimization). To workaround, the following options may be used.
```
-fno-builtin-fread
-fno-builtin-fwrite
```

But other problems are lurking, so it is best to disable built-ins altogether, as follows.

```
-fno-builtin
```

Better yet, all enclave sources should be compiled as freestanding.

```
-ffreestanding
```

The **pkg-config** scripts should be updated as well.

**Comment by vishnumohan1991** [comment]
In your branch mikbras.oefs2  the test fs run successfully in release mode. so we can't able to reproduce the issue.@mikbras

**Comment by andschwa** [comment]
@mikbras @CodeMonkeyLeet Is this still relevant?

**Comment by johnkord** [comment]
We're going to close this. If it continues to happen on the new io branch, let's reopen.
