### ISSUE TITLE
(Documentation?) std::chrono::high_resolution_clock

### ISSUE THREAD

**Issue by acl33** [Microsoft/openenclave#1098]
Calling std::chrono::high_resolution_clock::now() from inside the Enclave aborts with message:
Assertion failed: "clock_gettime(): panic" == NULL (/mnt/c/Users/allawr/openenclave/libc/syscalls.c: _syscall_clock_gettime: 134)
This is probably to be expected from what LibcSupport.md says about clock_gettime, but LibcxxSupport.md claims that chrono is fully supported....

**Comment by anitagov** [comment]
I updated LibcSupport.md to indicate the limitations of clock_gettime but didn't update LibcxxSupport.md  to indicate the partial support of chrono. Thanks for flagging this. Will update this.

**Comment by anakrish** [comment]
@anitagov Can you see if we can cause a link error for this case.

**Comment by anitagov** [comment]
This is fixed by PR #1138
