### ISSUE TITLE
Re-use (and factor out) Ansible configuration work to be used with oe-engine

### ISSUE THREAD

**Issue by johnkord** [Microsoft/openenclave#1113]
The Cloudbase team is doing some work to add Ansible configurations for Jenkins agents, and it might be a good idea to reuse (and factor out) some of this work to be used with Azure ACC deployments.

**Comment by ionutbalutoiu** [comment]
@dmitsh @johnkord Please let us know if we decide to use Ansible in oe-engine, or we simply rely on plain bash cloud-init scripts.

**Comment by dmitsh** [comment]
@ionutbalutoiu @johnkord I tend to keep use of cloud-init scripts in oe-engine. That gives us more flexibility.

**Comment by ionutbalutoiu** [comment]
@dmitsh thank-you. Closing this for now.
