### ISSUE TITLE
Deduplicate package installation logic

### ISSUE THREAD

**Issue by andschwa** [Microsoft/openenclave#1117]
I don't know the correct solution here, but the problem is this:

We have duplicated package installation logic in half a dozen places now. Keeping in mind that there are a few scenarios of packages (SDK developer packages, SDK user packages, CI packages), there are a few subsets we could and should keep track of in a single location. Right now, if we had to bump any of these packages, we would need to update all of the following:

- [install-prereqs](https://github.com/Microsoft/openenclave/blob/master/scripts/install-prereqs)
- [Jenkins agent Dockerfile](https://github.com/Microsoft/openenclave/blob/master/.jenkins/Dockerfile)
- [Ansible playbooks for Jenkins](https://github.com/Microsoft/openenclave/pull/1111)
- [oe-engine provision script](https://github.com/Microsoft/oe-engine/blob/ba7af1de679e8c04e6510ffcff0f4155be7cea07/parts/provision.sh)
- the internal wiki page (and scripts there)
- this is a non-exhaustive list, I've probably forgotten something...

/cc @johnkord @dmitsh

**Comment by andschwa** [comment]
@oprinmarius I lean toward option 3, but regarding Ansible as a dependency, I need a refresher. Its only dependency is Python, right? Is it easily installed with pip or something, or would we need to `apt-get install` it everywhere?

**Comment by oprinmarius** [comment]
@andschwa yes, you are correct. Ansible can be installed by pip or apt-get and has Python as a dependency .

**Comment by oprinmarius** [comment]
https://github.com/Microsoft/openenclave/pull/1218

**Comment by johnkord** [comment]
As far as this repo is concerned, this issue is resolved!
