### ISSUE TITLE
Expose whether attestation is supported by OE

### ISSUE THREAD

**Issue by achamayou** [Microsoft/openenclave#1124]
We have functionality that depends on enclave attestation that we want to build into the application, and which should not be governed by a runtime flag. We currently detect whether oesign is linking libsgx, which implies the presence of the attestation functionality, but it's obviously not a particularly good way to do that.

If the exported CMake functionality could expose whether the OE install has that functionality through a definition or some other mecanism, it would be very helpful.

**Comment by johnkord** [comment]
@achamayou Let's talk about this sometime, Amaury. I'm going to close this issue for now, but we should follow up about this.
