### ISSUE TITLE
oecore: Use CMakeLists to build libunwind

### ISSUE THREAD

**Issue by anakrish** [Microsoft/openenclave#1126]
Currently libunwind building is very complex
1. It uses an external project that runs configure, make etc.
2. We do a bit of code transformation on the fly so that we can take control of unwinding (rewrite Gtrace.c, GStep.c) etc.

We need to rewrite libunwind building to use CMakeLists so that it builds seamlessly on Linux and Windows.

CC: @andschwa @mikbras

**Comment by andschwa** [comment]
I believe I actually have your changes integrated... but they come with some other changes I am still reconciling. Making good progress though!

**Comment by andschwa** [comment]
For some reason this wasn't automatic. Resolve dby #1154.
