### ISSUE TITLE
mbed tests fail if the root folder is named buildid

### ISSUE THREAD

**Issue by anakrish** [Microsoft/openenclave#1145]
If the root folder is named "buildid", then mbed tests fail. The tests try to open files that don't exist.
Possibly because they do a string replace of the word "build"

**Comment by andschwa** [comment]
@ionutbalutoiu Would you be able to get this triaged and worked on? I think it should be fairly independent of my other CMake work, but it's also really annoying that I have to build and run the full libc and libcxx tests in a particular folder.

Note: this only repros with full CXX tests, so like `cmake ~/openenclave/ -DUSE_LIBSGX=ON -DENABLE_FULL_LIBC_TESTS=ON -DENABLE_FULL_LIBCXX_TESTS=ON`

**Comment by oprinmarius** [comment]
@andschwa   The piece of code here: https://github.com/Microsoft/openenclave/blob/a2ac58dbd01e1c8e5f36ea45147834fdfdeb5384/tests/mbed/host/host.c#L37-L59   is the one that is causing problems.

Currently if we have any folder containing the word "build" in our working directory the string replace will split the path before the first occurrence of the word "build" and add the tail to it.

ex:  CWD:  /home/jenkins/test/buildid/build/tests/mbed
       Will get transformed into: 
        /home/jenkins/test/3rdparty/mbedtls/mbedtls/tests/suites/test_suite_gcm.aes128_de.data 


We can either split the PATH before the LAST occurrence of the word build, or we can use relative folder path from CWD.

**Comment by andschwa** [comment]
Hm. This logic is too hard-coded. The `cwd` absolutely does not have to have `build` in it, and frequently does not!

I think you're right that we'd be safer to just use a relative folder path rather than looking for `build`, as long as that's consistent. As for the hard-coded `tail`, _maybe_ this is safe, but if not, we can use CMake to set `#define`s to replace it at build time.

**Comment by dragoshsch** [comment]
@andschwa I think the best approach to this would be to set `#defines` using CMake, as you pointed out. Would you like us to make a PR with that?

**Comment by aserdean** [comment]
@andschwa I sent out this PR to address it: https://github.com/Microsoft/openenclave/pull/1326

I'm assuming that the test case path remains the same. If you want to tweak it a bit more please let me know.
