### ISSUE TITLE
Upgrade CMake to 3.13

### ISSUE THREAD

**Issue by andschwa** [Microsoft/openenclave#1146]
As part of my current chain of fixes for the CMake build (see stuff in progress in the project), I need to upgrade us to the latest CMake which comes with better support for `OBJECT` "libraries" (which is a CMake-ism that makes a lot of our build easier and cross-platform). This will _not_ affect consumers of OE, just developers of the SDK itself (us). This will also solve and replace #1000.

- [x] update install-prereqs script
- [x] update Jenkins nodes (agents with hardware label)
- [x] update Jenkins oe-tools Docker image
- [x] ~update Ansible files in #1111~ doesn't actually need to be done
- [x] update readme instructions
- [x] make sure everyone knows

Just FYI @Microsoft/openenclave

**Comment by andschwa** [comment]
I may actually be able to get away with CMake 3.12, as specifically I am utilizing this change in CMake 3.12 which allows to remove a hack that extracts and combines static archives manually:

> The target_link_libraries() command now supports Object Libraries. Linking to an object library uses its object files in direct dependents and also propagates usage requirements.

This would be nice because I previously updated the CI to 3.12 😄

**Comment by andschwa** [comment]
@ionutbalutoiu do you think you could take care of the CI updates? We might as well go to latest which is CMake 3.13.1 as long as we're doing this.

I need this before I can run my changes through the CI for full libcxx tests (though I can do it locally right now, so I'm not blocked, it's just slow).

If you got the CI things updated, I can get the readme updated and help the team out in installing CMake manually. Assigning this over to you for now. Thank you!

**Comment by andschwa** [comment]
Something along the lines of:

```
wget https://github.com/Kitware/CMake/releases/download/v3.13.1/cmake-3.13.1-Linux-x86_64.sh
sudo bash cmake-3.13.1-Linux-x86_64.sh --skip-license --prefix=/usr/local
```

Would programmatically install it.

**Comment by ionutbalutoiu** [comment]
Hello @andschwa! I've upgraded the cmake on all the Linux hardware nodes to `3.13.1`.

@dragoshsch is assigned to do the rest of the items.

**Comment by dragoshsch** [comment]
@andschwa I've created PR #1158 to update the install-prereqs script and the Dockerfile. I'm a bit unclear on how I should update the oetools-azure Docker image in the registry, perhaps I can get some guidance on that.

Thanks!

**Comment by dragoshsch** [comment]
@andschwa I upgraded the docker image by bumping the version number **from 1.7 to 1.8**, so the new image is oetools-azure:**1.8**. I also did the neccessary Jenkinsfile changes in PR #1158 .

**Comment by andschwa** [comment]
Thank you both so much!
