### ISSUE TITLE
Thread Local Storage implementation for Simulation Mode

### ISSUE THREAD

**Issue by anakrish** [Microsoft/openenclave#1160]
Thread local storage needs to be implemented specifically for simulation mode.
For thread-local storage in x86-64 abi, the FS register must be correctly set up to point to end of the storage containing thread-local variables.

CC: @mikbras @CodeMonkeyLeet @anitagov @lilyfang

**Comment by johnkord** [comment]
@EMumau Hold off on work for this issue, if you considered working on it :) We have to decide what to do with simulation mode first

**Comment by anakrish** [comment]
FYI, this has already been implemented and locked down with tests.
