### ISSUE TITLE
CMake Cleanup: Addition of test enclaves should not be based on platform

### ISSUE THREAD

**Issue by anakrish** [Microsoft/openenclave#1162]
Today the enclave portion of tests are added only on Linux platforms.
E.g: https://github.com/Microsoft/openenclave/blob/master/tests/echo/CMakeLists.txt#L6

 Instead of depending on the platform, the enclave directories must be added based on another flag, say
OE_BUILD_TEST_ENCLAVES. OE_BUILD_TEST_ENCLAVES must be set to true by default on Linux, and must also be set to true on ELF on Windows workflow.

CC: @soccerGB @andschwa

**Comment by andschwa** [comment]
We resolved this in #1268.
