### ISSUE TITLE
CMake: Avoid Linux specific stuff in 3rd party builds

### ISSUE THREAD

**Issue by anakrish** [Microsoft/openenclave#1164]
Some 3rd part src like MUSL use autoconf etc which are not available in Git Bash.
These need to be avoided so that they build on Windows.

CC: @soccerGB @andschwa

**Comment by andschwa** [comment]
@ionutbalutoiu Would you please take a look at this?

The ask is to make the [musl "build"](3rdparty/musl/CMakeLists.txt) cross-platform. Specifically, things like [this](https://github.com/Microsoft/openenclave/blob/d92b90f7fc16e2abd144a0fda2af89609efc6cfa/3rdparty/musl/CMakeLists.txt#L29) and [this](https://github.com/Microsoft/openenclave/blob/d92b90f7fc16e2abd144a0fda2af89609efc6cfa/3rdparty/musl/CMakeLists.txt#L45) won't work on Windows.

It doesn't have to ported to Windows immediately, but if we could replace these steps where we're calling musl's Autotools build system (the `./configure`) with our own CMake code, that would get us a long way toward bringing it over.

**Comment by dragoshsch** [comment]
@andschwa I'm afraid I don't have much experience with CMake/CMakeLists and I'll need a bit more guidance on this as I'm unsure on how to proceed.

**Comment by andschwa** [comment]
@dragoshsch We'll pause for a bit, I'll ping you all again later on this.

@anakrish and @mikbras how likely is it that we could skip this work? Anand's branch doesn't actually _require_ this to build ELFs (elves? 👅) on Windows, it seemed more of like a nice-to-have, as otherwise we're just relying on some Linux tools on Windows to provide Autotools. Mike, it sounds like musl will become an optional plugin in favor of elibc... so I am not convinced we need to do the work to build musl with CMake.

**Comment by anakrish** [comment]
@andschwa  Yes, at minimum we need the changes on my branch to build elves on windows.

**Comment by andschwa** [comment]
So let's change this from "CMake: Avoid Linux specific stuff in 3rd party builds" (which implies a fully cross-platform build for musl e.g. CMake) to "Make WSL a requirement for building elves on Windows" as the only changes for musl were to call `bash` (as in WSL) when running Autotools.

I think this is reasonable given the scope; it doesn't seem reasonable to rewrite the build for musl when _most_ people will be using elibc instead (according to @mikbras).

**Comment by andschwa** [comment]
First clarification with @anakrish, the dependency actually isn't even bash from WSL, it's bash from Git bash.

Second clarification, the `elibc` @mikbras had mentioned won't be exposed to the end user as the libc API, that'll still be musl.

So we still need to build musl in both places all the time.

I think the right call is to just require a bash equivalent (Git bash or WSL etc.) when building elves on Windows, and not to rewrite musl build system in CMake.

So this becomes the question: can we take that dependency? Avoiding that dependency requires writing that build system, which I don't think is worth it.

**Comment by andschwa** [comment]
I am going to close this issue. We settled on using the Linux tools (e.g. Bash) when needed on Windows, via Git Bash (or WSL or whatever). Writing a new build system for musl is _not_ required.
