### ISSUE TITLE
oeedger8r: ocall returns OE_OUT_OF_MEMORY instead of OE_ENCLAVE_ABORTING

### ISSUE THREAD

**Issue by EMumau** [Microsoft/openenclave#1165]
Making an ocall from an enclave which is aborting returns OE_OUT_OF_MEMORY instead of OE_ENCLAVE_ABORTING.
This affects abortStatus test and workaround was added to PASS this test on Linux

This error is in the code generated by the oeedger8r.

**Comment by anakrish** [comment]
@andschwa This is a good starting task to get into the Ocaml based oeedger8r.
Please follow up with @EMumau about an example.
