### ISSUE TITLE
pkg-config equivalent on windows

### ISSUE THREAD

**Issue by anakrish** [Microsoft/openenclave#1183]
We use pkg-config on Linux to allow SDK users to obtain the correct compilation flags.
Is there an equivalent on Windows?
LLVM has an llvm-config that provides information about the llvm install. Should there be an oe-config?

CC: @andschwa @mikbras

**Comment by andschwa** [comment]
I don't like either. I'd prefer just to provide a CMake package. If a user isn't using CMake, then they can just follow an example; I don't think there are any other standards on Windows for this.

**Comment by andschwa** [comment]
I am going to close this as we now provide the only real equivalent (a CMake package). Anything else would really be documentation, which should be a separate issue.
