### ISSUE TITLE
If libzma-dev is installed on a machine building oe, enclaves don't link

### ISSUE THREAD

**Issue by yakman2020** [Microsoft/openenclave#1186]
One of my machines as a large number of packages installed due to a history of being used for dcos developement. Because of that, libunwind autogen.sh sets the define HAVE_LZMA which triggers the need for liblzma in the enclave. Since we haven't built a liblzma.a to link, the result is link errors farther down the build from undefined references.

We should disable minidebug info, which forces that define off.
We should also institute a patch file for differences between our use of libunwind and the actual repo.

**Comment by andschwa** [comment]
This should no longer be an issue as #1154 changed the libunwind build away from their Autotools build to our own subset using CMake code we own.
