### ISSUE TITLE
Windows CI should also test GCC ELF enclaves

### ISSUE THREAD

**Issue by anitagov** [Microsoft/openenclave#1190]
Currently, Windows CI tests only use Clang ELF enclaves and this is a shortcoming. This should be extended to test GCC ELF enclaves.

**Comment by anitagov** [comment]
@johnkord @ionutbalutoiu - We may want to discuss if we really need this.  One configuration - Debug - Linux-Elf-Build may be all we need.

**Comment by ionutbalutoiu** [comment]
Hello @anitagov!

@dragoshsch tried this configuration and it seems to work on the current master branch. He opened the PR https://github.com/Microsoft/openenclave/pull/1478 adding a new testing stage for `Win2016 Ubuntu1804 gcc Debug Linux-Elf-build` (see https://github.com/Microsoft/openenclave/pull/1478/commits/8749517e823ce1ee4e592d936b335feb94437275 from the PR).

Regards,
Ionut
