### ISSUE TITLE
samples make world fails with OE_PLATFORM_ERROR

### ISSUE THREAD

**Issue by brenzi** [Microsoft/openenclave#1192]
I've followed 
https://github.com/Microsoft/openenclave/blob/master/docs/GettingStartedDocs/install_oe_sdk.md

then went to https://github.com/Microsoft/openenclave/blob/master/docs/GettingStartedDocs/using_oe_sdk.md
to test

but `make world` fails:
```
make[2]: Leaving directory '/home/brenzi/oe/samples/local_attestation/host'
make[1]: Leaving directory '/home/brenzi/oe/samples/local_attestation'
make -s run-silent
Host: Creating two enclaves
Host: Enclave library ./enc1/enclave1.signed.so
Host: oe_create_enclave failed. OE_PLATFORM_ERRORHost: Terminating enclaves
Host:  failed 
Makefile:15: recipe for target 'run' failed
make[2]: *** [run] Error 1
Makefile:21: recipe for target 'run-silent' failed
make[1]: *** [run-silent] Error 2
Makefile:24: recipe for target 'run' failed
make: *** [run] Error 2
```

I also couldn't build oesgx tool, because documentation seems outdated:
https://github.com/Microsoft/openenclave/blob/710702db7ca1a0bfdd45deb53c74f5c7a784deff/docs/GettingStartedDocs/SGXSupportLevel.md
there is no `./build` folder in this repository

My system is ubuntu 16.04, running on intel NUC8i3BEH2. `uname -a':
```
Linux chainbrick 4.15.0-42-generic #45~16.04.1-Ubuntu SMP Mon Nov 19 13:02:27 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
SGX is enabled in BIOS

**Comment by brenzi** [comment]
I should add that, before testing openenclave I played around with hyperledger sawtooth, also installing intel sgx tools:
https://sawtooth.hyperledger.org/docs/core/releases/1.0/sysadmin_guide/configure_sgx.html

Might there be conflicting tools?

**Comment by anakrish** [comment]
I suspect re-installing the SGX drivers would fix this.
@soccerGB Can you follow up?

**Comment by brenzi** [comment]
rebooting and re-installing the driver didn't help:
```
sudo ./sgx_linux_x64_driver.bin 
source /opt/openenclave/share/openenclaverc
cd samples/
make world
```
still results in above error.

maybe this helps:
```
> lsmod | grep sgx
isgx                   45056  0
intel_sgx              94208  0
```

**Comment by jmechalas** [comment]
What's is the output from the oesgx tool? I am pretty sure your NUC does not Flexible Launch Control.

**Comment by jmechalas** [comment]
I have this problem as well when running on a FLC-capable system. I have tried both the pre-packaged binaries and a build from source using 0.4.1. Any attempt to launch an enclave produces an OE_PLATOFRM_ERROR result.

This is a generic Ubuntu 16.04 LTS system which supports SGX1+FLC (not an Azure VM).

**Comment by johnkord** [comment]
This seems to be related to #1511 and what @jmechalas said above. I'll close this issue and we can track this problem in #1511
