### ISSUE TITLE
build_optee.sh not found in Linux Host on ARM

### ISSUE THREAD

**Issue by mofanv** [Microsoft/openenclave#1207]
Hello,

When I try to run `./build_optee.sh` in development of Linux Host on ARM [this webpage](https://github.com/Microsoft/openenclave/blob/feature.new_platforms/new_platforms/docs/linux_arm_dev.md). However, I could run this by typing `./new_platforms/build_optee.sh`. It also executable without errors, but I don't know whether this is the correct way of fixing it.
Does anybody have ideas about this?

 Any comment is appreciated.
Thanks.

**Comment by lilyfang** [comment]
That's expected. optee only works on new_platforms branch at this moment.

**Comment by dthaler** [comment]
The doc linked to was updated to say ./new_platforms/scripts/build_optee.sh which is the current location of the script.
