### ISSUE TITLE
oe_register_pthread_hooks should be made a public API

### ISSUE THREAD

**Issue by anitagov** [Microsoft/openenclave#1211]
oe_register_pthread_hooks is an internal API but needs to be made public if we want customers to implement their own pthread_create/pthread_join/pthread_detach in their enclaves.

Additionally, OE should provide hooks for pthread_cond_timedwait as this API currently asserts and is not supported.

**Comment by anitagov** [comment]
After discussion with @mikbras , OE will need to provide the implementation for pthread_cond_timewait.

**Comment by anitagov** [comment]
To add to my previous comment: oe_register_pthread_hooks will continue to be an internal API i.e. will not be made public.

Will need to change the title and description of this issue.

**Comment by johnkord** [comment]
Setting to wontfix and we will revisit this during the upcoming EDMM work
