### ISSUE TITLE
Proposal: set OE_SIMULATION at configure time if libsgx etc. is not found

### ISSUE THREAD

**Issue by andschwa** [Microsoft/openenclave#1232]
Similar to #1076, as part of making our build smarter, I propose that if libsgx (or optee etc.) is not found at configure time (that is, `-DUSE_LIBSGX=OFF`), that we _build_ with `OE_SIMULATION` set as like a `#define`. Currently, if we build without SGX available, we still need to set `OE_SIMULATION=1` as an environment variable at _runtime_ in order to run the tests. This is annoying! If the binaries were built without SGX available, then only simulation mode is going to be usable by those binaries, so why are we requiring a runtime environment variable? If it's not set, everything fails, and it's not like we can copy this binary to an SGX capable system and have it start working. So let's just automatically run in simulation mode when tests were built without any other support.

**Comment by johnkord** [comment]
We're closing this issue because if the libsgx flag isn't set for the build, we can still interface with SGX using AESM.
