### ISSUE TITLE
Make ctest work in parallel

### ISSUE THREAD

**Issue by mjp41** [Microsoft/openenclave#1236]
Currently running `ctest -j2` sometimes crashes ctest. Some schedules work, but the more you increase the parallelism, the more likely it is to crash.  The crash completely halts ctest, not sure what can cause that.

**Comment by andschwa** [comment]
Hm, thanks for the report! I think that it probably has to do with limited enclave memory. @anakrish Can you expand more on this?

**Comment by johnkord** [comment]
We're not currently investigating this, and it might not be possible because the individual tests were not written to run in parallel.
