### ISSUE TITLE
pkg-config: Validate compile/link flags

### ISSUE THREAD

**Issue by anakrish** [Microsoft/openenclave#1238]
When building test enclaves, we build using the following flags  (as of this writing):

-g   -Wall -Werror -Wpointer-arith -Wconversion -Wextra -Wno-missing-field-initializers -fno-strict-aliasing -mxsave -fno-builtin-malloc -fno-builtin-calloc -m64 -fPIC -nostdinc -fno-stack-protector -fvisibility=hidden -nostdinc++ -std=c++14

Not all of these flags are exposed by pkg-config.

Additionally, we use the -pie linker option. The [documentation ](https://gcc.gnu.org/onlinedocs/gcc-8.2.0/gcc/Link-Options.html)for that says:
**-pie**
Produce a dynamically linked position independent executable on targets that support it. F**or predictable results, you must also specify the same set of options used for compilation** (-fpie, -fPIE, or model suboptions) when you specify this linker option.

CC: @mikbras @andschwa

**Comment by andschwa** [comment]
I think instead of just validating the hard coded flags, we should generate pkg-config via CMake, kind of like they did [here](https://dailycommit.blogspot.com/2016/10/how-to-generate-pkg-config-file-with.html).

**Comment by andschwa** [comment]
@johnkord this is another nice-to-have backlog item. Perhaps Cloudbase can do it?

**Comment by andschwa** [comment]
I've looked further into auto-generating the pkg-config files, and I don't think it's worth the effort. So instead, I am comparing CMake package flags against our pkg-config flags. Differences so far:

Compile options for oecore missing from CFLAGS: `-fno-stack-protector;-fvisibility=hidden`.

But otherwise...everything is good. @anakrish @CodeMonkeyLeet are these flags that should be in pkg-config, or should _not_ be in the CMake package?

**Comment by anakrish** [comment]
We need to use the -fvisibility=hidden since it marks symbols as non exported; enclaves are a single module and exported symbols don't make sense.

-fno-stack-protector is a flag we need to get rid of in v0.6. Instead we need to compile with the strongest available stack protection; but it requires enhancing our C library initialization.

**Comment by andschwa** [comment]
So that sounds like `-fvisibility=hidden` should be in our pkg-config, if possible, for compiling enclaves.

And we'll just remove `-fno-stack-protector` eventually; but do we want it removed from the CMake package? That is, I can make it just a build time thing and not an install time thing.

**Comment by anakrish** [comment]
Yes. Unfortunately we want it removed for  from cmake package as well since we don't yet have the necessary infrastructure to implement it correctly.
I noticed that we are not passing -fvisibility=hidden when building mbedtls.
It would be good to have a single source of truth for the flags if possible. Something for cloudbase?

**Comment by andschwa** [comment]
Clarified offline with Anand.

For now, we want both of these options to be both in the pkg-config and the CMake package. So I'll open up an issue to do that.

I am uncertain of the viability of doing the last request; it's quite a bit more complicated than it seems.
