### ISSUE TITLE
Use new Ansible scripts

### ISSUE THREAD

**Issue by andschwa** [Microsoft/openenclave#1240]
Now that #1218 is in, we need to do the following:
- [x] Add documentation about Ansible (specifically calling out that it should be the single source of truth for package requirements)
- [x] Rewrite the `install-prereqs` script to install Ansible and run the playbooks, such that the end result is the same as it is now (all prereqs installed automatically, but without duplicate logic)
- [x] Update Docker images given the Dockerfile changes

/cc @johnkord

**Comment by oprinmarius** [comment]
https://github.com/Microsoft/openenclave/pull/1244

**Comment by ionutbalutoiu** [comment]
@andschwa looks like all the items are checked. Is there any work left here ?

**Comment by johnkord** [comment]
Looks good! - Andy
