### ISSUE TITLE
Add a second Ubuntu 18.04 system to Jenkins and more 18.04 tests to Jenkinsfile.

### ISSUE THREAD

**Issue by johnkord** [Microsoft/openenclave#1252]
We just enabled Ubuntu 18.04 in the Jenkins CI building against master, but we have only added two tests so far. We should try to get full coverage on Ubuntu 18.04 for the 3 different build types with the 2 different compilers, similar to what we have on Ubuntu 16.04.

This may be a good opportunity to try out the Ansible playbooks on Ubuntu 18.04 to see what may be missing.

Checklist:
- [x] Add second Ubuntu 1804 Jenkins slave
- [ ] Add more Ubuntu 18.04 tests. This pull request https://github.com/Microsoft/openenclave/pull/1256 addresses this

**Comment by oprinmarius** [comment]
@johnkord  I added the missing ACC tests in the following PR:
https://github.com/Microsoft/openenclave/pull/1256

However we are still missing Container Test with Ubuntu 18.04 , and Simulation tests are using the OETOOLS_IMAGE which is also Ubuntu 16.04

Do we want to enable Docker tests using Ubuntu 18.04 ?
We would have to create another Dockerfile , publish a new Docker image based on Ubuntu 18.04 and adjust the Jenkins tests to support IMAGE_NAME to be passed as an argument

If this is needed I can follow up with another PR

**Comment by ahapliuc** [comment]
@johnkord I've added the repositories in line with the Ubuntu 16.04 repositories for the new Ubuntu 18.04 Jenkins slave and it seems that no open enclave package has been published yet in them:
![image](https://user-images.githubusercontent.com/2115347/50557097-6cdfd600-0cea-11e9-8d3e-3ae66694038d.png)

Can the open enclave package for 18.04 be published in the respective repository?

**Comment by johnkord** [comment]
@oprinmarius I think we should eventually add a container test with Ubuntu 18.04, and definitely add more simulation tests to run on 18.04.  Eventually we can probably reduce our test coverage for simulation mode on 16.04, as long as we run one stage in CI for 16.04, maybe the "RelWithDebInfo" test.

@ahapliuc The open-enclave 18.04 package hasn't been published quite yet as you've noted, since master isn't ready for a release yet. We're going to talk with @lilyfang about this sometime soon and find out when we can plan for the next release (which should have an 18.04 package).

I'm fairly certain we'll be publishing it to the exact repository that you mentioned in that picture! I'll update the instructions for publishing to 18.04 when the time comes.
