### ISSUE TITLE
Add Ubuntu 18.04 support to libcxx_tests.Jenkinsfile

### ISSUE THREAD

**Issue by johnkord** [Microsoft/openenclave#1278]

**Comment by johnkord** [comment]
@ionutbalutoiu Is this feature complete now?

**Comment by ionutbalutoiu** [comment]
@johnkord Yes. We just need to add the testing stages and enable the CI.

There was an initial effort [here](https://github.com/Microsoft/openenclave/pull/1324), but we held on that a bit to have the libcxx Jenkinsfile refactoring for the ephemeral nodes.

The libcxx refactoring PR https://github.com/Microsoft/openenclave/pull/1542 is ready now. As soon as that PR is merged, we'll be quickly adding the 18.04 stages.
