### ISSUE TITLE
Windows CI performance improvements

### ISSUE THREAD

**Issue by johnkord** [Microsoft/openenclave#1281]
Under our current setup, Windows builds can really slow down CI jobs, but there are a few tasks that could speed them up:

- [x] Add one more Windows node to Jenkins that can perform Windows CI
- [x] Use the D:\ drive for all CI jobs on the Windows CI systems. The D:\ drive is the default temp drive on Windows Azure systems, and has significantly faster performance: https://blogs.msdn.microsoft.com/mast/2013/12/06/understanding-the-temporary-drive-on-windows-azure-virtual-machines/

**Comment by andschwa** [comment]
I think this is really high priority because our CI runs are taking an _entire hour_ per job right now, which is bad.

**Comment by johnkord** [comment]
@andschwa @ionutbalutoiu Yes I agree, this should be one of the highest priority tasks in right now in https://github.com/Microsoft/openenclave/projects/4

**Comment by ionutbalutoiu** [comment]
> @andschwa @ionutbalutoiu Yes I agree, this should be one of the highest priority tasks in right now in https://github.com/Microsoft/openenclave/projects/4

Note taken!

**Comment by ionutbalutoiu** [comment]
I've configured a second Windows Jenkins slave `ACC-Win-2`. It's using the same Azure VM configuration (`Standard_DC2s` size and `eastus` region).

Both Windows Jenkins slaves are using `D:\` temp storage for the Jenkins workspace root directory.

They serve jobs under the common label `SGXFLC-Windows` (previously defined on the first agent).
