### ISSUE TITLE
Port the pre-commit scripts to Windows

### ISSUE THREAD

**Issue by andschwa** [Microsoft/openenclave#1285]
In #1284 we had to disable installing the pre-commit script on Windows because although the hook script is compatible, some of the scripts it called are not. This should be investigated and fixed, as we do want the functionality on Windows too.

On Windows it can be assumed that Bash and the others that come with Git are present, but the scripts need to be compatible with them. I think clang-format and shellcheck might pose problems.

**Comment by dragoshsch** [comment]
@andschwa as far as I can see it, you're right with `shellcheck` and `clang-format` being the only tools that aren't installed in something like a Git Bash setup.

Splitting the pre-commit hook between OS-es and rewriting all the scripts without `shellcheck` and `clang-format` will introduce needless breakage in the CI if the scripts differing even minorly (which I'm certain they will). I think windows users should just install [LLVM](http://releases.llvm.org/7.0.1/LLVM-7.0.1-win64.exe) and [shellcheck](https://storage.googleapis.com/shellcheck/shellcheck-stable.zip) just like any other users.

In my tests only a one line change is needed in `./scripts/format-code` after installing LLVM and shellcheck from the links above in **git bash**.

What do you think about all this?

**Comment by andschwa** [comment]
@dragoshsch I am quite happy to have clang-format and shellcheck installed in Git Bash (that might mean updating the Windows docs, or do we have anything to automatically setup Windows yet @anakrish?) and use those.

**Comment by anakrish** [comment]
Our Getting Started for Windows is here: https://github.com/Microsoft/openenclave/blob/master/docs/GettingStartedDocs/GettingStarted.Windows.md
That would need to be updated as necessary.

How do we ensure the correct clang-format version though?
The clang-format I get via LLVM says verstion 7.0; but don't we want some other specific version?

**Comment by andschwa** [comment]
@anakrish Actually we fixed that the day before yesterday in #1311 and now want clang-format-7 😄 (Thanks @oprinmarius)

**Comment by anakrish** [comment]
Great!
