### ISSUE TITLE
edgr8r directory missing from install breaks out of tree build

### ISSUE THREAD

**Issue by yakman2020** [Microsoft/openenclave#1290]
The edgr8r files are needed by the _t.c generated files produced by the edgr8tor.

**Comment by andschwa** [comment]
Can you be more specific?

**Comment by yakman2020** [comment]
The edgr8r directory doesn't get installed in /opt/openenclave/includes/openenclave

**Comment by paulcallen** [comment]
Curious. I run cmake as ``` cmake .. -DUSE_LIBSGX=1 -DCMAKE_INSTALL_PREFIX:PATH=~/openenclave-install``` and then when I do a make/make install I see these files:
```
ls ~/openenclave-install/include/openenclave/edger8r
common.h  enclave.h  host.h
```

Are you saying there are other files missing, or when there is no CMAKE_INSTALL_PREFIX specified it is broken?

**Comment by paulcallen** [comment]
and these files are put there via include/cmakelists.txt line 13 I believe

**Comment by yakman2020** [comment]
repro:

clone openenclave.git
cd to openenclave, mkdir build
cmake -G "Unix Makefiles -DUSE_LIBSGX=1 ..
make
make install

Look at /opt/openenclave/include/openenclave and you will not see the edgr8r directory.

**Comment by andschwa** [comment]
@paulcallen LOL I didn't even know that file existed.

**Comment by andschwa** [comment]
We were never able to repro this, closing for now. Feel free to re-open with a repro.
