### ISSUE TITLE
Default to BUILD_ENCLAVES=1 on Windows

### ISSUE THREAD

**Issue by johnkord** [Microsoft/openenclave#1292]
By default, the behavior on Windows should be to build ELF enclaves locally on that Windows system using clang. This will require a change both to the CMake build system and the CI to compensate for that (so that we can continue to test both scenarios for ELF enclave build platforms that are consumed on Windows).

**Comment by ionutbalutoiu** [comment]
Fixed by https://github.com/Microsoft/openenclave/pull/1327
