### ISSUE TITLE
Simulation testing on Windows

### ISSUE THREAD

**Issue by johnkord** [Microsoft/openenclave#1293]
We want to validate that simulation mode functions properly on Windows in our CI.

**Comment by ionutbalutoiu** [comment]
> The Cloudbase team has tested this, and have found that these tests fail in simulation mode on Windows:
> 
> ```
> 6 - tests/abortStatus (SEGFAULT)
> 32 - tests/stdcxx (SEGFAULT)
> ```

These are the failures encountered **besides** the documented known failures from [here](https://github.com/Microsoft/openenclave/blob/master/docs/GettingStartedDocs/GettingStarted.Windows.md#known-issues).

Once we have a PR ready for this, we'll document those as well if they are consistent failures.
