### ISSUE TITLE
Issues with Jenkins stage Check Pre-Commit requirements 

### ISSUE THREAD

**Issue by anitagov** [Microsoft/openenclave#1298]
We have encountered lots of issues with the new Jenkins stage "Check Pre-Commit Requirements".
1) Firstly, the title is misleading as it is doing a make and build. Please change this to something appropriate to indicate what this new stage is doing. 
2) The tests are run in simulation mode. Since we have so many simulation runs already, I don't see the need for another simulation run. 
3) Tests seem to be timing out randomly with this stage causing us to repeat our CI run. The 1 hr. run which needs to be repeated is a waste of machine time.

**Comment by anitagov** [comment]
Great if this can be addressed ASAP. Thanks.

**Comment by ionutbalutoiu** [comment]
@anitagov Marius is on it
