### ISSUE TITLE
Ansible-playbook shouldn't require sourcing of /etc/environment for CMake binaries availability in PATH

### ISSUE THREAD

**Issue by johnkord** [Microsoft/openenclave#1308]
A proposed solution to this is to create symbolic links in a normal path for binaries that point to the installed CMake binaries.

**Comment by andschwa** [comment]
Can we just go back to installing CMake to `/usr/local/bin`?

**Comment by andschwa** [comment]
Installing to `/cmake/bin` and then modifying `/etc/environment` is super non-standard IMHO.

**Comment by johnkord** [comment]
That sounds good to me.

**Comment by ionutbalutoiu** [comment]
John opened https://github.com/Microsoft/openenclave/pull/1316 to fix this issue.
