### ISSUE TITLE
Windows: New Ansible configuration is needed to enable DCAP 

### ISSUE THREAD

**Issue by CodeMonkeyLeet** [Microsoft/openenclave#1320]
As part of adding DCAP attestation support for ELF enclaves running on Windows, we need a new Ansible script to configure Windows with the new prerequisites:

* Target configuration is Windows Server 2016 ACC VM
* Latest PSW needs to be installed:
    * http://registrationcenter-download.intel.com/akdlm/irc_nas/15018/Intel%20SGX%20PSW%20for%20Windows%20v2.2.100.48339.exe
    * This is a self-extracting ZIP executable, and the unpacked `PSW_EXE_RS2_and_before\Intel(R)_SGX_Windows_x64_PSW_2.2.100.48339.exe` installer needs to be run.
* DCAP package consists of multiple components that need to be manually installed:
    * http://registrationcenter-download.intel.com/akdlm/irc_nas/15017/Intel%20SGX%20DCAP%20for%20Windows%20v1.0.100.48134.exe
    * Also a self-extracting ZIP executable than needs to be unpacked, which contains more packages and          Intel SGX DCAP Windows SW Installation Guide.pdf, which has more details than the summary below:
        * `LC_driver_WinServer2016\WinServer2016\Signed_1152921504627869629.zip` needs to be unzipped and the `drivers\942f489c-bd5a-4745-89e4-e1cdc68a1adf\sgx_base_dev.inf` it contains needs to be installed to `root\SgxLCDevice`.
        * `DCAP_INF\WinServer2016\Signed_1152921504627869999.zip` also needs to be unzipped and the `drivers\d5b94c05-b0d1-42e9-82c1-d394f8642fa3\sgx_dcap_dev.inf` it contains installed to `root\SgxLCDevice_DCAP`.
        * Both the nuget packages `nupkg\DCAP_Components\DCAP_Components.1.0.100.0.nupkg` and `nupkg\EnclaveCommonAPI\EnclaveCommonAPI.1.0.100.0.nupkg` need to be installed as well.
    * To enable the LC driver, the system regkey must also be set: `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\sgx_lc_msr\Parameters\"SGX_Launch_Config_Optin"=dword:00000001`
        * This requires a reboot to take effect once the driver is running.
* Install the Azure DCAP client nupkg
    * There's no pre-built drop of this from https://github.com/Microsoft/Azure-DCAP-Client/tree/master/src/Windows currently, so we will need to manually build and host it for the time being using the given instructions.

_To install driver .inf from command line:_
* `devcon.exe` from the [Windows Driver Kit for Windows 10](https://go.microsoft.com/fwlink/?linkid=2026156) can be used. For example:
```cmd
devcon.exe install sgx_base_dev.inf root\SgxLCDevice
devcon.exe install sgx_dcap_dev.inf root\SgxLCDevice_DCAP
```
* It is usually installed to `C:\Program Files (x86)\Windows Kits\10\tools\x64` and is not pathed by default.

_To install .nupkg from command line:_
* [nuget.exe for CLI](https://dist.nuget.org/win-x86-commandline/latest/nuget.exe) can be used.
```cmd
nuget.exe install EnclaveCommonAPI -Source 'C:\Intel SGX DCAP for Windows v1.0.100.48134\nupkg' -OutputDirectory C:\openenclave\prereqs\nuget
nuget.exe install DCAP_Components -Source 'C:\Intel SGX DCAP for Windows v1.0.100.48134\nupkg' -OutputDirectory C:\openenclave\prereqs\nuget
nuget.exe install Microsoft.Azure.DCAP.Client -Source C:\Azure_DCAP_nupkg_folder;nuget.org -OutputDirectory C:\openenclave\prereqs\nuget
```
* It would be nice if we can install to a target folder that does not include the nupkg version number, since they much be referenced for header include paths in the build project. 
* Note that for the Azure DCAP nupkg, `nuget.org` must also be specified as a source because it needs to pull down dependency packages.

**Comment by ionutbalutoiu** [comment]
@CodeMonkeyLeet Thank-you for all the great details about the task! On it.
