### ISSUE TITLE
Need to add support for establishing secure channel between enclaves : TLS with remote attestation

### ISSUE THREAD

**Issue by soccerGB** [microsoft/openenclave#1325]
# Integrate attestation to TLS (Transport Layer Security) between Open Enclave enclaves

## Prerequisites

  The audience is assumed to be familiar:
   
  - [Transport Layer Security (TLS)](https://en.wikipedia.org/wiki/Transport_Layer_Security) a cryptographic protocol designed to provide communications security over a computer network.

  - [Open Enclave Remote attestation](https://github.com/Microsoft/openenclave/tree/master/samples/remote_attestation#what-is-attestation): Remote Attestation is the concept of a HW entity or of a
combination of HW and SW gaining the trust of a remote provider or producer.

## Abstract

  As Open Enclave SDK getting adopted into more realistic scenarios, we are receiving requests from OE SDK developers for adding support to establish a TLS channel between two attested enclaves.

  We do have the remote_attestation sample that shows how to conduct remote attestation between two enclaves and establish a `proprietary` channel based on asymmetric keys exchanged during the attestation process. It demonstrates how to conduct mutual attestation but it does not go all the way to show how to establish a fully secure channel. Most of the real world software uses TLS-like standard protocol through popular TLS APIs (OpenSSL, WolfSSL, Mbedtls...) for establishing secure channels.

  Instead of inventing a new communication protocol, the document proposes a solution for addressing above customer need by adding a mechanism into OE SDK to seamlessly integrate remote attestation into the TLS's handshake process without changing any of existing TLS APIs.

### Overview

  The attestation feature that comes with TEE (such as Intel SGX or ARM's TrustZone enclave) could significantly improve a TLS endpoint (client or server) trustworthiness for a TLS connection starting or terminating inside an enclave. 

  By taking advantage of the fact that TLS involving parties use public-key cryptography for identity authentication during the TLS handshaking process, we propose to use a self-signed X509.V3 certificate to represent a TLS endpoint's identity. In this certificate, we make it cryptographically bound to this specific enclave instance by adding a custom certificate extension (called quote extension) with this enclave's attestation quote that has the certificate's public key information embedded. (a new OE API , oe_gen_tls_cert(), will be added to generate this certificate)

  The receiving TLS connection peer will perform the following "Custom extended certificate validation" inside the peer certificate verification callback (all TLS APIs support this callback for custom certificate validation)

  1. Validate certificate
  2. Validate quote extension
  3. Extract this quote extension and perform quote validation
  4. Validate peer enclave's identity with information from the quote

  A new OE API , oe_verify_tls_cert(), will be added to perform step 1-3 and leaving step 4 to application for business logics.
    
    Once authenticating the received certificate, it can be confident that the connecting party is indeed a specific enclave image running inside a TEE (SGX enclave for example).
    
The same authentication process could be applied to both directions in the TLS handshaking process to establish an attested TLS channel between two enclaves.

 As you can see, we are proposing a mechanism to integrate remote attestation with existing TLS API implementation seamlessly, not proposing any new TLS API implementation.

### Detailed Design

Here are the detailed steps needed for a TLS party to conduct in the TLS connection establishment process for achieving attested TLS connection. Those steps apply to both a TLS client and a TLS server. 

##### Generate PKI key pair

  - a private key (pkey): used for generating a certificate and represent the identity of the TLS connecting party
  - a public key (pubkey): used in the TLS handshake process to create a digital signature in every TLS connection,

##### Generate a X509.V3 certificate

 - Use pubkey as Subject Public Key
 - Self-signed with pkey
 - Generate a remote report (quote) as follows:
   call oe_get_report

        oe_get_report(
                OE_REPORT_FLAGS_REMOTE_ATTESTATION,
                report_user_data, //  the hash value of pubkey
                sizeof(report_user_data),
                NULL,
                0,
                remote_report_buf,
                remote_report_buf_size);

      where: the report's user data contains a hash value of pubkey. 
      
      As shown in the OE SDK's remote_attestation sample, this binds the pubkey to this specific enclave instance crypto-graphically. That is, the identity of the enclave is representing the identity of the TLS connecting party because of this pubkey ties to both the certificate and enclave instance.
      In the case of Intel SGX, the root of trust would be Intel.
      
- Embed this quote into an X509v3 extensions
    
The following two new OE SDK APIs are proposed to handle this certificate generation/free work.

```
/**
 * oe_generate_attestation_certificate.
 *
 * This function generates a self-signed x.509 certificate with an embedded
 * quote from the underlying enclave.
 *
 * @param[in] subject_name a string contains an X.509 distinguished
 * name (DN) for customizing the generated certificate. This name is also used
 * as the issuer name because this is a self-signed certificate
 * See RFC5280 (https://tools.ietf.org/html/rfc5280) specification for details
 * Example value "CN=Open Enclave SDK,O=OESDK TLS,C=US"
 *
 * @param[in] private_key a private key used to sign this certificate
 * @param[in] private_key_size The size of the private_key buffer
 * @param[in] public_key a public key used as the certificate's subject key
 * @param[in] public_key_size The size of the public_key buffer.
 *
 * @param[out] output_cert a pointer to buffer pointer
 * @param[out] output_cert_size size of the buffer above
 *
 * @return OE_OK on success
 */
oe_result_t oe_generate_attestation_certificate(
    const unsigned char* subject_name,
    uint8_t* private_key,
    size_t private_key_size,
    uint8_t* public_key,
    size_t public_key_size,
    uint8_t** output_cert,
    size_t* output_cert_size);

/**
 * Free the given cert
 * @param[in] cert If not NULL, the buffer to free.
 */
void oe_free_attestation_certificate(uint8_t* cert);

```

- load this certificate to a TLS endpoint using standard TLS API

```
    For example (with mbedtls):
        mbedtls_ssl_conf_own_cert(conf, server_cert, pkey)
```

##### Transport the certificate to the peer endpoint

 There is no work here, and it leverages the existing standard TLS handshaking process for exchanging certificates between a client and a server.

##### Authenticate peer certificate

Upon receiving a certificate from the peer endpoint, we need to authenticate the received certificate.

In this design, instead of using the TLS API's default authentication routine, which validates the certificate against a pre-determined CAs for authentication, we replace it with "Extended custom certificate validation" to be conducted inside "peer certificate verification callback," which is an API supported by all TLS APIs.

```
 For example: disable mbedtls default authentication routine
    mbedtls_ssl_conf_authmode(conf, MBEDTLS_SSL_VERIFY_NONE);
```

Setup peer certificate verification callback.

```
For example
 In Mbedtls: 
    int cert_verify_callback(void *data, mbedtls_x509_crt *crt, int depth, uint32_t *flags)
    mbedtls_ssl_conf_verify(conf, cert_verify_callback, NULL);

 In OpenSSL
    void SSL_CTX_set_cert_verify_callback(SSL_CTX *ctx,
                             int (*callback)(X509_STORE_CTX *, void *), void *arg);
    int ssl_app_verify_callback(X509_STORE_CTX *ctx, void *arg) 
```

Here is what need to validate inside the peer certificate verification callback

1. Verify the signature on the self-signed certificate to ascertain that the attestation report is genuine and unmodified. 
2. Compute the SHA256 hash of the peer's public key and compare this against the report’s user data in the quote. If they match, this is proof that the server is indeed running inside a genuine TEE and using this key to secure the TLS session
3. Validate the enclave’s identity (e.g., MRENCLAVE in SGX) against the expected list. This check ensures only the intended party is allowed to connect to.
  
If any of the above verification steps fails, the TLS connection will abort

The following new OE SDK API is added to handle checking 1 and 2 above.

```
/**
 * oe_verify_attestation_certificate
 *
 * This function perform a custom validation on the input certificate. This
 * validation includes extracting an attestation evidence extension from the
 * certificate before validating this evidence. An optional enclave_identity_callback
 * could be passed in for a calling client to further validate the identity of
 * the enclave creating the quote.
 * @param[in] cert_in_der a pointer to buffer holding certificate contents
 *  in DER format
 * @param[in] cert_in_der_len size of certificate buffer above
 * @param[in] enclave_identity_callback callback routine for custom identity
 * checking
 * @param[in] arg an optional context pointer argument specified by the caller
 * when setting callback
 * @retval OE_OK on a successful validation
 * @retval OE_VERIFY_FAILED on quote failure
 * @retval OE_INVALID_PARAMETER At least one parameter is invalid
 * @retval OE_FAILURE general failure
 * @retval other appropriate error code
 */
oe_result_t oe_verify_attestation_certificate(
    uint8_t* cert_in_der,
    size_t cert_in_der_len,
    oe_identity_verify_callback_t enclave_identity_callback,
    void* arg);

```

A custom callback is added to handle checking 3.

```
/**
 * identity validation callback type
 * @param[in] identity a pointer to an enclave's identity information
 * @param[in] arg caller defined context
 */
typedef oe_result_t (
    *oe_identity_verify_callback_t)(oe_identity_t* identity, void* arg);
```

## Required dependencies and Status

- Socket support in OE SDK (prototyped)
- Enabling the mbedtls' MBEDTLS_NET_C component for the version of mbedtls, which supports networking features (prototyped)

We have a working prototype of this attested TLS connection proposal run with above two items.

## Reference

This proposal bases on the design from the following paper. 

[Integrating Remote    Attestation    with Transport Layer Security](https://arxiv.org/ftp/arxiv/papers/1801/1801.05863.pdf)

OE SDK's host-based remote attestation support makes it perfect to work with this design.

**Comment by CodeMonkeyLeet** [comment]
@soccerGB Is this considered completed with #1761

**Comment by soccerGB** [comment]
I would wait until the socket feature is merged and check in end-2-end test and SDK samples before closing this issue.

**Comment by soccerGB** [comment]
both feature implementation and sdk samples were done and merged into master branch
