### ISSUE TITLE
oesign makes assumptions about filenames

### ISSUE THREAD

**Issue by Lusitanian** [Microsoft/openenclave#1351]
oesign makes some strange assumptions about filenames - among them, that "enc" must be (case-sensitively) contained within the enclave filename. this consumed a large amount of dev time today since our enclaves have "Enclave" with a capital "E" in the filename.

**Comment by Lusitanian** [comment]
additionally, the error output is nonexistent. in order to discover this I had to compile oesign with debug symbols and step into the sign routine

**Comment by achamayou** [comment]
@mikbras could this be prioritised please, it's quite annoying to have to rename all enclaves in a project. The logic that uses substrings to guess which argument is which does not seem particularly sound, something explicity based on flags would preferable (oesign sign -e enclave.so -c config.conf -k key.pem).

**Comment by andschwa** [comment]
@achamayou I spoke with @CodeMonkeyLeet and this is definitely something we can do. I'll be doing it as side work, so I can't get a firm time to you, but I'll surely get this cleaned up!

**Comment by achamayou** [comment]
@andschwa thank you, that'd be very helpful. For what it's worth, we use https://github.com/CLIUtils/CLI11, it supports sub-command and it's well-documented.

**Comment by jmechalas** [comment]
I'd like to see this changes as well. All assumptions about filenames should be removed entirely.

**Comment by andschwa** [comment]
@johnkord While this would be nice to have, I don't see it as a v0.5 item.

**Comment by jmechalas** [comment]
It's not a nice to have. It's a developer friction because it enforces arbitrary file naming conventions in an environment where file names are traditionally meaningless. Considering all that needs to be done is delete the logic that was added to enforce the filenames it's not exactly a heavy lift.

**Comment by andschwa** [comment]
Ah, thanks @jmechalas. I'll prioritize this then.

**Comment by ionutbalutoiu** [comment]
I just opened https://github.com/Microsoft/openenclave/pull/1602 to address this issue.

The `oesign sign` CLI will accept the following named parameters:
* `--enclave-image [-e]`
* `--config-file [-c]`
* `--key-file [-k]`
