### ISSUE TITLE
The GCC tests are failing on Ubuntu 18.04

### ISSUE THREAD

**Issue by ionutbalutoiu** [Microsoft/openenclave#1353]
Currently the 1804 CI jobs consistently report failures when running the GCC tests. These are the results from some of the jobs:

* https://oe-jenkins.eastus.cloudapp.azure.com/blue/organizations/jenkins/Bors/detail/trying/604/pipeline/
* https://oe-jenkins.eastus.cloudapp.azure.com/blue/organizations/jenkins/OpenEnclave-libcxx_tests-moprin-temp/detail/OpenEnclave-libcxx_tests-moprin-temp/2/pipeline/

Looks like the 3rd party dependency `musl` treats some warnings as errors, thus the job fails.

**Comment by johnkord** [comment]
@andschwa and I talked about this and think we should disable these warnings as errors for the musl project.

**Comment by andschwa** [comment]
Specifically disable with #pragmas. There should be an existing pattern to follow as some warnings are similarly disabled already.

**Comment by andschwa** [comment]
Resolved via #1358.
