### ISSUE TITLE
Improve Ansible scripts to provision new Linux slaves

### ISSUE THREAD

**Issue by ionutbalutoiu** [Microsoft/openenclave#1354]
Right now, the Ansible scripts require a secret to provision new Jenkins slaves:
https://github.com/Microsoft/openenclave/blob/31a6c4fa21e0c8d1cc4019004f0a9027c12c2663/scripts/ansible/vars/variables.var#L5

This means that some manual steps need to be done on the Jenkins master to add the new node and fetch the secret for it, which is not desirable.

Also, I feel that we should remove the 3rd party dependency `kobanyan.jenkins-jnlp-slave` and have our tasks to set up the Linux Jenkins slave.

Improvements check-list:

* [x] Automate the node creation & secret fetch. This is already addressed by https://github.com/Microsoft/openenclave/pull/1350
* [x] Remove `kobanyan.jenkins-jnlp-slave` 3rd party dependency

**Comment by vlaza** [comment]
The 1st part with `jenkins_slave_secret` is resolved in https://github.com/Microsoft/openenclave/pull/1350

**Comment by vlaza** [comment]
@ionutbalutoiu Please assign this one also to me as I already started working on it.

**Comment by ionutbalutoiu** [comment]
> @ionutbalutoiu Please assign this one also to me as I already started working on it.

Done

**Comment by vlaza** [comment]
2nd item from checklist is addressed by https://github.com/Microsoft/openenclave/pull/1403

**Comment by ionutbalutoiu** [comment]
With https://github.com/Microsoft/openenclave/pull/1430 being merged, this is fixed.
