### ISSUE TITLE
Add Ansible scripts to set up new Windows Jenkins slave

### ISSUE THREAD

**Issue by ionutbalutoiu** [Microsoft/openenclave#1355]
This issue will be used for the new Ansible scripts to set up new Windows Jenkins slaves on the ACC hardware.

The work here comes combined with the request from https://github.com/Microsoft/openenclave/issues/1320.

**Comment by vlaza** [comment]
@ionutbalutoiu Please assign this one also to me as I already started working on it.

**Comment by vlaza** [comment]
PR created https://github.com/Microsoft/openenclave/pull/1402 and depends on https://github.com/Microsoft/openenclave/pull/1375

**Comment by ionutbalutoiu** [comment]
Fixed by https://github.com/Microsoft/openenclave/pull/1402
