### ISSUE TITLE
Refactor test-samples.sh (to remove it, probably)

### ISSUE THREAD

**Issue by johnkord** [Microsoft/openenclave#1357]
We came across this test-samples.sh script, which we think could probably be factored out. It looks like its purpose is to facilitate running of the samples tests. This logic can probably be handled from within CMake without needing to run this script.

**Comment by andschwa** [comment]
Beware anyone who looks at this script! It is not fun 😭

**Comment by aserdean** [comment]
I have a question about this one.
In summary the script is only used here:
https://github.com/Microsoft/openenclave/blob/master/samples/CMakeLists.txt#L44
and ran only via ctest .

The test executes an `make install` and a run of samples:

<details>

```
+ test -i = -i
+ realpath /home/ubuntu/openenclave/build
+ BIN_DIR=/home/ubuntu/openenclave/build
+ realpath -m /home/ubuntu/openenclave/build/samples/samples-test/opt/openenclave
+ INSTALL_DIR=/home/ubuntu/openenclave/build/samples/samples-test/opt/openenclave
+ rm -rf /home/ubuntu/openenclave/build/samples/samples-test/opt/openenclave
+ make -C /home/ubuntu/openenclave/build DESTDIR=/home/ubuntu/openenclave/build/samples/samples-test install
+ TEST_MAKE_DIR=/home/ubuntu/openenclave/build/samples/samples-test/opt/openenclave/share/openenclave/samples
+ export PKG_CONFIG_PATH=/home/ubuntu/openenclave/build/pkgconfig
+ export PATH=/home/ubuntu/openenclave/build/samples/samples-test/opt/openenclave/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
+ [ ]
+ MAKE_TASKS=world
+ make -C /home/ubuntu/openenclave/build/samples/samples-test/opt/openenclave/share/openenclave/samples OE_PREFIX=/home/ubuntu/openenclave/build/samples/samples-test/opt/openenclave world
make: Entering directory '/home/ubuntu/openenclave/build/samples/samples-test/opt/openenclave/share/openenclave/samples'
```

</details>

I am thinking to split this into two. Add a step just to run the samples and delegate the install via a stage in the CI where we install the deb produced on a clean system provisioned via ansible roles (w or w/o the sample run).

@andschwa , @johnkord what do you think?
CC: @ionutbalutoiu

**Comment by johnkord** [comment]
I just talked with Andy about this, we think we should hold off a little bit before we change this.

Cheng-mean and Andy and I agreed that we should be running the samples tests as part of the normal test run because it tests two main scenarios: that a package install works (albeit a non-deb package), and a bunch of common scenarios (like remote attestation, etc).

As for factoring out this script, I believe there are some changes coming to the cmake interface that may or may not affect this issue. So for now we can ignore this issue :)
