### ISSUE TITLE
Use --device for /dev/sgx instead of --privileged in Jenkinsfiles

### ISSUE THREAD

**Issue by johnkord** [Microsoft/openenclave#1366]
We accidentally reverted to using "--privileged -v /dev/sgx:/dev/sgx" for docker flags for non-simulation container tests, when we should be using the "--device /dev/sgx:/dev/sgx" option instead.

**Comment by johnkord** [comment]
This should also be changed in the Azure-DCAP-Client Jenkinsfile

**Comment by stefanlupsa** [comment]
since it's on a different repo bu mentioned in the issue, i'm linking the PR here as well https://github.com/Microsoft/Azure-DCAP-Client/pull/33
