### ISSUE TITLE
oeedger8r : generated code: error: implicit conversion changes signedness: 'int' to 'size_t'

### ISSUE THREAD

**Issue by soccerGB** [Microsoft/openenclave#1369]
I noticed that the oeedger8r generated code does not build clean without 
-Wno-conversion compiler option. Given that we enabled warning as a error for implicit type conversion, this is becoming a problem. It would be great to have this fixed so that we dont need to add "-Wno-conversion" in out code

276:55: error: implicit conversion changes signedness: 'int' to 'size_t'
     (aka 'unsigned long') [-Werror,-Wsign-conversion]
    if (a_Name) OE_ADD_SIZE(_input_buffer_size, _args.a_nNameLen);
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~
oe_result_t ocall_bind(
        oe_socket_error_t* _retval,
        void* a_hSocket,
        const void* a_Name,
        int a_nNameLen) ---------------------- does not match the size parameter in the black line below

{
if (a_Name) OE_ADD_SIZE(_input_buffer_size, _args.a_nNameLen); ….
}

oe_result_t oe_add_size(size_t* total, size_t size)

**Comment by andschwa** [comment]
Am doing (saw the email).
