### ISSUE TITLE
Remove references to install-prereqs in format-code

### ISSUE THREAD

**Issue by johnkord** [Microsoft/openenclave#1370]
Since we're deprecating install-prereqs, we shouldn't reference in other places anymore, and we noticed there's an error message in format-code that refers to it

**Comment by dragoshsch** [comment]
@johnkord I can only find references to `install-prereqs` in `README.md`:

```
$ rg -i install-prereqs
scripts/README.md
13:- [install-prereqs][] - Installs packages needed to build Open Enclave```

Is there something I'm missing here? If not, I think we can close this issuel

**Comment by johnkord** [comment]
Thanks Dragos!
