### ISSUE TITLE
Add validation Ansible role for the Jenkins slaves

### ISSUE THREAD

**Issue by ionutbalutoiu** [Microsoft/openenclave#1395]
Once https://github.com/Microsoft/openenclave/pull/1375 is merged, we should add a validation role to be executed at the end of the Jenkins slaves setup playbook.

This should be able to verify the expected state of the Jenkins slaves after configuration is finished by the previous tasks.

Check-list:

* [x] Add validation role for Linux
* [x] Add validation role for Windows

**Comment by vlaza** [comment]
Both items in checklist are solved by https://github.com/Microsoft/openenclave/pull/1448
