### ISSUE TITLE
Hackathon Ideas

### ISSUE THREAD

**Issue by andschwa** [Microsoft/openenclave#1405]
- Fix oesign CLI #1351 
- Implement more samples (self-contained features)
- Implement examples (full apps in enclaves)
- Handle enclave memory disappearing (sleep mode / live migrations)
- Improve oedump to inspect enclave methods #564
- Add VS Code support (automatic debugger setup, pkg-config, EDL syntax highlighting, etc.)

**Comment by andschwa** [comment]
TODO: We need a temporary subscription for the Hackathon. @pushkarcMS Could you help me get one set up? It would be for students to spin up ACC VMs. We need to avoid the policy that gets applied to our subscription which limits connections only to Microsoft corpnet IP addresses.

**Comment by andschwa** [comment]
@gupta-ak For HackIllinois specifically I think we should welcome a "bring your own" style of examples to implement. I am imagining students having prior homework assignments or side projects that they want to re-implement in an enclave. Sort of a "lab" style.

**Comment by gupta-ak** [comment]
@andschwa That sounds good!
