### ISSUE TITLE
Inconsistency between test-build-config and CMake code

### ISSUE THREAD

**Issue by ionutbalutoiu** [Microsoft/openenclave#1425]
The [--build-type](https://github.com/Microsoft/openenclave/blob/05e69d739d20382f83dc61496a252490b33f07ed/scripts/test-build-config#L75) passed to the `test-build-config` bash script is passed further to the CMake `-DCMAKE_BUILD_TYPE` parameter [here](https://github.com/Microsoft/openenclave/blob/05e69d739d20382f83dc61496a252490b33f07ed/scripts/test-build-config#L124).

However, the `test-build-config` script capitalizes the `--build-type / -b` parameter before passing it to CMake (see [here](https://github.com/Microsoft/openenclave/blob/05e69d739d20382f83dc61496a252490b33f07ed/scripts/test-build-config#L102)) and even validates that it's all uppercase [here](https://github.com/Microsoft/openenclave/blob/05e69d739d20382f83dc61496a252490b33f07ed/scripts/test-build-config#L111-L114).

The problem is that there are parts of the `CMake` code that doesn't expect it to be all uppercase. For example [here](https://github.com/Microsoft/openenclave/blob/4969be9fe68bdb6e8e76af04e1f53a9f989c331e/CMakeLists.txt#L144-L146). This leads to errors and masked test failures, like the most recent one discovered [here](https://github.com/Microsoft/openenclave/pull/1321#issuecomment-459778019).

@andschwa pointed out that it's not a good practice to do `if (CMAKE_BUILD_TYPE)` in this issue https://github.com/Microsoft/openenclave/issues/756.

However, if the effort to remove `if (CMAKE_BUILD_TYPE)` from CMake is high, I think that we can at least make the `test-build-config` script to correctly pass the `BUILD_TYPE`, as it's expected by the CMake code.

**Comment by ionutbalutoiu** [comment]
cc @andschwa @johnkord 

What do you think about my suggestion about adjusting the `test-build-config` script until https://github.com/Microsoft/openenclave/issues/756 is fully addressed ?

**Comment by andschwa** [comment]
@ionutbalutoiu I thought we were removing `test-build-config` entirely, so this should be addressed by the Jenkinsfile passing the correct case of `CMAKE_BUILD_TYPE` (or by checking all instances of that in CMake and doing the to_upper comparison).

**Comment by anitagov** [comment]
We don't really need this issue as the Linux test-build-config script has gone and the Windows test-build-config script is also being deprecated (PR #1428 ).
@andschwa - Can you verify that the JenkinsFile has the correct parameters?

**Comment by anitagov** [comment]
We don't really need this issue as the Linux test-build-config script has gone away and the Windows test-build-config script is also being deprecated (PR #1428 ).
@andschwa - Can you verify that the JenkinsFile has the correct parameters?

**Comment by ionutbalutoiu** [comment]
This issue is referring to the Linux `test-build-config` script.

As mentioned by Andy [here](https://github.com/Microsoft/openenclave/pull/1321#pullrequestreview-194328681), we didn't delete it yet. So far, we have these:

* PR https://github.com/Microsoft/openenclave/pull/1398 - Converts the `Packaging.Jenkinsfile` to scripted and removes the `test-build-config` usage
* PR https://github.com/Microsoft/openenclave/pull/1324 - Converts the `libcxx_tests.Jenkinsfile` to scripted and removes the `test-build-config` usage
* https://github.com/Microsoft/Azure-DCAP-Client/issues/36 - Just created another issue to track the removal of `test-build-config` usage from Azure-DCAP-Client Jenkinsfile. We'll take care of it.

After all the above get sorted, I think we can remove the `test-build-config` script entirely, and we can close this issue.

@andschwa @anitagov What do you think ?

**Comment by ionutbalutoiu** [comment]
@aserdean merged https://github.com/Microsoft/openenclave/pull/1431 adding insensitive comparison to CMake, and we'll not have troubles around the `CMAKE_BUILD_TYPE` parameter.

Also, after https://github.com/Microsoft/openenclave/pull/1324 gets merged, the `test-build-config` script can be removed entirely.

I'm closing this issue since it's not a problem anymore.
