### ISSUE TITLE
Windows test failure with Debug Linux build

### ISSUE THREAD

**Issue by ionutbalutoiu** [microsoft/openenclave#1426]
When running the Windows OE tests using a Linux build with `-DCMAKE_BUILD_TYPE=Debug`, the following unit test fails consistently:
```
8 - tests/backtrace (Failed)
```

The full reason behind this has been explained [here](https://github.com/Microsoft/openenclave/pull/1321#issuecomment-459778019).

We ended up adding `-DUSE_DEBUG_MALLOC=OFF` as a temporary workaround to avoid the failure, but it's not desirable.

This pull request https://github.com/Microsoft/openenclave/pull/1408 removes the temporary workaround and reproduces the current issue.

**Comment by ionutbalutoiu** [comment]
Hello @mikbras,

This issue is related to the [oe_backtrace_symbols](https://github.com/Microsoft/openenclave/blob/171f2c29906e1963e6cca3f25ae8ba562a334f05/enclave/core/sgx/backtrace.c#L87-L118) function added by you in [this commit](https://github.com/Microsoft/openenclave/commit/096f2cf1bf795602d259fecc1f0e4ab678d7583f) for `v0.4.1` release.

The failure is happening when running the tests in `Debug` mode on Windows. These are the pieces of code from tests that fail:

1. https://github.com/Microsoft/openenclave/blob/171f2c29906e1963e6cca3f25ae8ba562a334f05/tests/backtrace/enc/enc.cpp#L99-L100
2.  https://github.com/Microsoft/openenclave/blob/171f2c29906e1963e6cca3f25ae8ba562a334f05/tests/backtrace/enc/enc.cpp#L120-L121

The exact piece of code do not fail on Linux (using `Debug` mode as well) and `oe_backtrace_symbols` correctly returns the symbols, thus the assertion doesn't fail.

Digging further into the `oe_backtrace_symbols` implementation, we found out that the `oe_call` with `OE_OCALL_BACKTRACE_SYMBOLS` from:
https://github.com/Microsoft/openenclave/blob/171f2c29906e1963e6cca3f25ae8ba562a334f05/enclave/core/sgx/backtrace.c#L105-L110
correctly sets the `args->ret`, thus the function returned value is correct.

However, when running the tests on Windows, the `args->ret` value is always empty, even after executing `oe_call` with `OE_OCALL_BACKTRACE_SYMBOLS`.

Do you know if the function `oe_backtrace_symbols` is supposed to work on Windows as well ?

**NOTES**:
* This failure is isolated to the unit tests executed with a Linux elf build on Windows, and it doesn't impact Windows cross-compiled builds. 
* This scenario is currently skipped by the CI, otherwise the failure will be blocking.

cc @johnkord @CodeMonkeyLeet @andschwa

**Comment by CodeMonkeyLeet** [comment]
@ionutbalutoiu No, I don't believe it works on Windows, see #961

**Comment by ionutbalutoiu** [comment]
> @ionutbalutoiu No, I don't believe it works on Windows, see #961

Thank-you for the reference! We might need to add some extra `ifdef` condition for checking if not `WIN32` here:
https://github.com/Microsoft/openenclave/blob/171f2c29906e1963e6cca3f25ae8ba562a334f05/tests/backtrace/enc/enc.cpp#L96-L103
and here:
https://github.com/Microsoft/openenclave/blob/171f2c29906e1963e6cca3f25ae8ba562a334f05/tests/backtrace/enc/enc.cpp#L119-L124

Or simply wait for the proper support of backtrace on Windows.

So far, our workaround for the CI is to force `USE_DEBUG_MALLOC` to `OFF`:
https://github.com/Microsoft/openenclave/blob/171f2c29906e1963e6cca3f25ae8ba562a334f05/.jenkins/Jenkinsfile#L95
And we have the flag disabled, regardless of the CMake logic from here:
https://github.com/Microsoft/openenclave/blob/4969be9fe68bdb6e8e76af04e1f53a9f989c331e/CMakeLists.txt#L144-L150

**Comment by mikbras** [comment]
I enabled backtrace support on Windows and it works fine for me with debug-malloc. The PR is here #1860.

I enabled tests/backtrace, which now runs and I allocated and un-freed block in tests/echo (which I've since taken back out). It prints a proper backtrace.

**Comment by ionutbalutoiu** [comment]
@mikbras This is awesome news!

I just tested removing our workaround for the CI (force `USE_DEBUG_MALLOC` to `OFF`) on top of your PR https://github.com/microsoft/openenclave/pull/1860, and everything worked as expected.

Once your PR to enable backtrace on Windows is merged, we can have this issue fixed.

**Comment by ionutbalutoiu** [comment]
Fixed by https://github.com/microsoft/openenclave/pull/1860
