### ISSUE TITLE
Add a few new Jenkins nodes and reduce executors

### ISSUE THREAD

**Issue by johnkord** [Microsoft/openenclave#1439]
There's been a bit of instability on some of the CI nodes that might be remedied by adding one (or two) more nodes per ACC label (both Linux and Windows).  Also, it might be worth it to reduce the number of executors per Linux system to 1 and then use Ninja as the build generator for most of our stages.  @ionutbalutoiu What do you think about this?

**Comment by ionutbalutoiu** [comment]
I agree with you @johnkord. I'll get this sorted out.

**Comment by ionutbalutoiu** [comment]
@johnkord @andschwa @anitagov 

I added 2 more Jenkins Linux ACC machines (`18.04` + `16.04`), and I set the workers count to `1` for all our `ACC` hardware machines.

Things looks to be more stable now. I'll monitor the CI jobs and look for any flakiness.

Please let me know if you notice them first.
