### ISSUE TITLE
Add CMake support for samples

### ISSUE THREAD

**Issue by johnkord** [Microsoft/openenclave#1440]
In order to support building our samples on Windows, we'll need to add a cross platform way to build them there. CMake seems like the easiest solution, since the rest of our build uses CMake. This could also help solve #1357 

I've assigned Ionut, Alin, and Anita to this issue, but realistically we don't need everyone working on it. @aserdean I remember you mentioned this is something you were interested in. Let me know if you'd like to work on this :).  I know Anita was considering working on this too, so I'll sync up with everyone next week

**Comment by aserdean** [comment]
@johnkord issue https://github.com/Microsoft/openenclave/issues/1357 has a different problem IMO. I updated it with my findings.

I can take a stab at generating also cmakefiles across the samples if that is okay with you.

**Comment by anitagov** [comment]
Sounds good to me.

**Comment by johnkord** [comment]
Thanks @aserdean !

**Comment by aserdean** [comment]
As an update on this one, I finished with `samples/helloword` and `samples/file-encryptor`, after which I got to `samples/data-sealing` and I hit a semi issue:
```
/home/ubuntu/openenclave/samples/data-sealing/common/keys.cpp:108:14: error: no matching function for call to 'oe_get_seal_key_by_policy_v2'
    result = oe_get_seal_key_by_policy(
             ^~~~~~~~~~~~~~~~~~~~~~~~~
/home/ubuntu/openenclave/include/openenclave/enclave.h:517:35: note: expanded from macro 'oe_get_seal_key_by_policy'
#define oe_get_seal_key_by_policy oe_get_seal_key_by_policy_v2
                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/ubuntu/openenclave/include/openenclave/enclave.h:579:13: note: candidate function not viable: no known conversion from 'uint8_t [1]' to 'uint8_t **' (aka 'unsigned char **') for 2nd argument
oe_result_t oe_get_seal_key_by_policy_v2(
```

`samples/data-sealing` uses **OE_API_VERSION v1**

Is it okay if I update the samples for **OE_API_VERSION v2** as part of the effort?

CC: @andschwa

**Comment by andschwa** [comment]
@paulcallen ought to know.

**Comment by anitagov** [comment]
@aserdean - Can you please point us to your branch? OR file a PR with what you already have. Thanks.

**Comment by aserdean** [comment]
@anitagov : Sure: https://github.com/Microsoft/openenclave/pull/1466 .

I will close the PR and break all the changes into atomic commits after we decide what we keep and CI is green.

**Comment by aserdean** [comment]
Closed via: https://github.com/Microsoft/openenclave/pull/1472 and https://github.com/Microsoft/openenclave/pull/1570

**Comment by andschwa** [comment]
Thank you so much @aserdean!
