### ISSUE TITLE
Upgrade mbedtls to 2.7.9 or better

### ISSUE THREAD

**Issue by CodeMonkeyLeet** [Microsoft/openenclave#1446]
We've fallen behind in keeping up with the various fixes in the crypto library and as of 2/11/19 we're about 3 stable versions behind to get to 2.7.9. 

Of note is a fix to handling for `MBEDTLS_PLATFORM_CALLOC/FREE_MACRO` which can be worked around by setting `MBEDTLS_PLATFORM_STD_CALLOC/FREE` instead, but that should be updated to use the macro definitions as documented for `MBEDTLS_PLATFORM_MEMORY` when we upgrade to 2.7.9 or better.

Related to #1457: We may move directly to 2.16.0 instead as the new long-term support branch mbedTLS has marked.

**Comment by vlaza** [comment]
Hello, we are already working on this as part of https://github.com/Microsoft/openenclave/pull/1486
and tests passed https://github.com/Microsoft/openenclave/compare/master...vlaza:ISSUE-1456

**Comment by CodeMonkeyLeet** [comment]
@vlaza Didn't know you were actively working on this since I split it out of #1456. I needed to take a look at the `MBEDTLS_PLATFORM_CALLOC/FREE_MACRO` issue so spent a bit of time on this. This PR looks identical to yours except for the updated comments in config.h detailing the choice to keep the use of `MBEDTLS_PLATFORM_STD_CALLOC/FREE`. It has also passed Sandbox tests.

GitHub doesn't appear to correctly compare [mbedtls_2.7.9](https://github.com/Microsoft/openenclave/tree/mbedtls_2.7.9) correctly with your fork, so can you pull the branch and diff against your private?
