### ISSUE TITLE
Clean-up OpenEnclave warnings from builds

### ISSUE THREAD

**Issue by ionutbalutoiu** [Microsoft/openenclave#1447]
Currently, there are a lot of warnings when building the project on both Linux and Windows.

Ideally, we should start cleaning them up.

**Comment by andschwa** [comment]
The only extant warnings should be from third-party code. Can you list specifics to our code?

**Comment by ionutbalutoiu** [comment]
> The only extant warnings should be from third-party code. Can you list specifics to our code?

Oh, it might be only third-party code. Let me double check this and if I cannot find anything related to our code, I'll be closing this issue.

**Comment by ionutbalutoiu** [comment]
I double checked logs from OE builds using `gcc` and `clang-7`.

I found only warnings related to the 3rd-party code, and nothing related to our code.

Closing this issue.
