### ISSUE TITLE
Ensure OCaml / CMake are same versions linux and windows

### ISSUE THREAD

**Issue by vlaza** [Microsoft/openenclave#1449]
Found that we are not installing the exact same minor versions on Windows/Linux Jenkins slave nodes.

**Linux**
* CMake: 3.13.1 - upgrade / leave as-is or downgrade to 3.12.4
* OCaml: 4.02.3 - leave as-is or downgrade to 4.02.1

**Windows**
* CMake: 3.12.18.. (provided by Visual Studio 2017)
* OCaml: 4.02.1

Will require to patch Ansible provisioning roles to deploy the same versions.
Linux: upgrade / leave as-is or downgrade to 3.12.4
Windows: bump minor version of OCaml to 4.02.3 (might be an issue here as there is no package available yet for this version) or downgrade to 4.02.1

**Comment by vlaza** [comment]
Blocked by https://github.com/Microsoft/openenclave/pull/1448

**Comment by anakrish** [comment]
@vlaza Do we need to install cmake separately on Windows? My understanding was that Visual Studio came with its own specific version of cmake. 
CC @johnkord @anitagov @CodeMonkeyLeet @andschwa

**Comment by vlaza** [comment]
@anakrish on Windows it is already installed with Visual Studio and seems it is version: 3.12.18081601-MSVC_2 as per https://github.com/Microsoft/openenclave/blob/master/docs/GettingStartedDocs/GettingStarted.Windows.md#microsoft-visual-studio-2017

I will update the description of the issue and conduct further checks.

> Linux: bump minor version of CMake to 3.13.3
> Windows: bump minor version of OCaml to 4.02.3 (might be an issue here as there is no package available yet for this version)

**Comment by ionutbalutoiu** [comment]
> @vlaza Do we need to install cmake separately on Windows? My understanding was that Visual Studio came with its own specific version of cmake.
> CC @johnkord @anitagov @CodeMonkeyLeet @andschwa

Hello @anakrish 

We don't need to install CMake separately, Visual Studio with CMake tools component comes with CMake installed.

Victor suggest to match the versions of `CMake` and `OCaml` for Windows and Linux. I consider this a good practice and we should do it.

**Comment by ionutbalutoiu** [comment]
I synced offline with Victor and we think that it's not worth downgrading the packages from a running system, or forcing a particular version instead of the latest stable package when setting up new nodes.

However, whenever there's an update for the stable packages (either on Ubuntu or Windows), we should try and upgrade to a version matching the other platform, for consistency (in case the current version is older).

Closing this issue for now.

**Comment by andschwa** [comment]
Yup, I agree with @ionutbalutoiu, no reason to downgrade the Linux packages.

**Comment by anitagov** [comment]
I have cmake installed on my ACC Windows VM. And this is the one that seems to get used when I build on Windows. The cmake with Visual Studio might suffice -- but this version may be different from the one that we install. So, at this point, I think we are fine as long as we have at least cmake version 3.12.x.
