### ISSUE TITLE
Upgrade 3rdparty libraries

### ISSUE THREAD

**Issue by CodeMonkeyLeet** [Microsoft/openenclave#1456]
As with the previous release, we should evaluate updating to the latest versions of the stable 3rdparty libraries prior to the next (v0.5) OE SDK update. Libraries on the horizon for the end of Feb include:

- [x] [MUSL libc 1.1.21](http://www.musl-libc.org/releases/musl-1.1.21.tar.gz)
    - Note that the `libc-test` suite comes from a different, _unversioned_ project at (separate update command in `3rdparty/musl/update.make`)
    - There's been an update in Nov 2018 that we didn't pick up, and we should probably do so now. (added `strptime` test) 
- [ ] LLVM libcxx 8.0.0 ([final](http://llvm.org/svn/llvm-project/libcxx/tags/RELEASE_800/final/))
- [x] [mbedTLS 2.7.9](https://tls.mbed.org/download/start/mbedtls-2.7.9-apache.tgz)

Note that the security approval for the versions of the LLVM libcxx and MUSL libc libraries still stand, so there's not an urgent to upgrade from them for any security reason. *Given the slip in LLVM's schedule, we will bump taking the libcxx 8.0.0 update to the next release.*

> mbedTLS though, does have relevant security fixes, and so is tracked separately by #1446.

For the libc/libcxx updates, they are also a little more involved as we need to identify and evaluate changes to the test set as well. A general outline of the process for onboarding a new version includes:

1. Update the relevant `update.make` file for the 3rd party library and run it to pull down and apply the new version.
2. Attempt to build OE SDK with the updated source code. Find and fix any breaks, and repeat for all build configurations.
    1. A common source of failures will be the mismatch in the test files we expect to be present as used in `tests/libc` and `tests/libcxx`; primarily libcxx tests since the libc tests don't change much, but the guidance here applies to both.
    2. Each of those test suites defines a `tests.all` file which inventories the set of all tests we expect exist for the version of the respective library we're using.
    3. As part of the update, we do a diff of a sorted file tree walk of the new test folder contents against the old `tests.all` to understand what tests were added/removed/moved, which helps with the next step.
3. Attempt to run the OE SDK tests with the `ENABLE_FULL_LIBCXX_TESTS` CMake variable set to true.
    1. This is also the configuration for the Jenkins [OpenEnclave-libcxx_tests pipeline](https://oe-jenkins.eastus.cloudapp.azure.com/blue/organizations/jenkins/OpenEnclave-libcxx_tests/activity), but I would suggest running it locally since it takes a non-trivial amount of time to complete and hog the limited ACC VMs, preventing other pipelines from running.
    2. The libc tests already runs all of the supported tests, so no additional flag is necessary. 
    3. The set of supported tests should be expanded to include any new tests.
        - For libcxx tests, this is defined by the `tests.supported` file.
        - For libc tests, this is defined in the `tests.cmake` file.
    4. Any test failures should be triaged as either broken or unsupported:
        - A _broken_ test is one that we think should pass, but does not for bug or dependency reasons.
        - An _unsupported_ test is one where we explicit decide that the failure is by design (e.g. I/O functions where OE provides no I/O support).
    5. We also take the set of previously broken and unsupported tests and run them again to see if any of them have started passing.
        - Some tests do because they no longer rely on functions not supported in OE SDK, for example.
    6. Update the sets of `tests.supported`, `tests.broken` and `tests.unsupported` so that they reflect the new total set of `tests.all`.
        - Usually the triage process for determining the supported/unsupported/broken split requires a bit of insight, and @mikbras, @anakrish & @CodeMonkeyLeet are usually available to consult on those fronts. 

> In terms of the PR, steps 1 & 2 are usually 1 commit and all of the test modifications and updates are 1 or more subsequent commits to keep the 3rdparty changes separate from the OE test changes.

**Comment by johnkord** [comment]
Simon (@CodeMonkeyLeet) wants to offer some comments on this.

**Comment by CodeMonkeyLeet** [comment]
Updated the title and description of this issue to track the LLVM slip.

**Comment by vlaza** [comment]
Info: We are still waiting for a `final` release on *8.0.0*

**Comment by aserdean** [comment]
RC4 has been released:
http://llvm.org/svn/llvm-project/libcxx/tags/RELEASE_800/rc4/

CC: @vlaza

**Comment by vlaza** [comment]
rc5 has been released: http://llvm.org/svn/llvm-project/libcxx/tags/RELEASE_800/rc5/

**Comment by vlaza** [comment]
I have updated the PR for *rc5* and re-running all tests.

**Comment by vlaza** [comment]
I have updated the PR with *final* release and all tests in the updated version are passing.

**Comment by johnkord** [comment]
Closing this as complete except for LLVM 8.0 which is scheduled for v0.6.
