### ISSUE TITLE
Flaky Windows simulation tests

### ISSUE THREAD

**Issue by aserdean** [Microsoft/openenclave#1474]
The following tests have a high chance of failure on windows under simulation mode:
```
tests/SampleApp
tests/SampleAppCRT
tests/abortStatus
tests/backtrace
tests/cppException
tests/ecall
tests/echo
tests/enclaveparam
tests/file
tests/getenclave
tests/hexdump
tests/hostcalls
tests/initializers
tests/mbed*
tests/mixed_c_cpp
tests/ocall
tests/ocall-create
tests/oeedger8r
tests/pingpong
tests/pingpong-shared
tests/props
tests/props_unsigned
tests/safecrt
tests/stdc
tests/stdcxx
tests/thread*
```

@oprinmarius found them when running multiple jobs in the CI:
* [OpenEnclave-sandbox#751](https://oe-jenkins.eastus.cloudapp.azure.com/blue/organizations/jenkins/OpenEnclave-sandbox/detail/OpenEnclave-sandbox/751/pipeline)
* [OpenEnclave-sandbox#752](https://oe-jenkins.eastus.cloudapp.azure.com/blue/organizations/jenkins/OpenEnclave-sandbox/detail/OpenEnclave-sandbox/752/pipeline)
* [OpenEnclave-sandbox#753](https://oe-jenkins.eastus.cloudapp.azure.com/blue/organizations/jenkins/OpenEnclave-sandbox/detail/OpenEnclave-sandbox/753/pipeline)
* [OpenEnclave-sandbox#754](https://oe-jenkins.eastus.cloudapp.azure.com/blue/organizations/jenkins/OpenEnclave-sandbox/detail/OpenEnclave-sandbox/754/pipeline)
* [OpenEnclave-sandbox#755](https://oe-jenkins.eastus.cloudapp.azure.com/blue/organizations/jenkins/OpenEnclave-sandbox/detail/OpenEnclave-sandbox/755/pipeline)
* [Bors-trying#721](https://oe-jenkins.eastus.cloudapp.azure.com/blue/organizations/jenkins/Bors/detail/trying/721/pipeline)

UPDATED from: https://github.com/Microsoft/openenclave/pull/1407#issuecomment-467369393

**Comment by johnkord** [comment]
Windows simulation mode doesn't work.
