### ISSUE TITLE
Need to convert existing samples to use V2 APIs

### ISSUE THREAD

**Issue by soccerGB** [Microsoft/openenclave#1485]
The work is a followup for the feature in the following link to push V2 APIs to samples.

https://github.com/Microsoft/openenclave/commit/e5e7f0dddaa6d9759f838515d00f0064df177935#diff-014693700bd59ca0f5ab157573ed80d9

**Comment by aserdean** [comment]
@soccerGB , @paulcallen I updated the samples to v2 as part of the cmake samples effort:
https://github.com/Microsoft/openenclave/pull/1466

I sent a PR only with that here:
https://github.com/Microsoft/openenclave/pull/1493

**Comment by aserdean** [comment]
Closed with PR: https://github.com/Microsoft/openenclave/pull/1493
