### ISSUE TITLE
Clarify libc support for threads

### ISSUE THREAD

**Issue by letmaik** [Microsoft/openenclave#1487]
docs/LibcSupport.md lists `threads.h` as partially supported and mentions "Unsupported functions: pthread_create(), pthread_join() and pthread_detach()". This doesn't make sense to me as these are pthreads functions which are not part of the C11 `threads.h` header. Should this entry be split up into two? One for `threads.h` and one for `pthread.h`?

**Comment by CodeMonkeyLeet** [comment]
Yes, you're right we should do a better job of clarifying this.
