### ISSUE TITLE
Windows host state gets corrupted after enclave entry and exit

### ISSUE THREAD

**Issue by anitagov** [microsoft/openenclave#1501]
The current host context which includes the FPU and SSE register state is not saved on entering the enclave on Windows. Hence the host state after enclave exit is perturbed and this has multiple repercussions, the primary one being that future enclave entry can result in incorrect state being passed to the enclave. Future calls on host can also result in unexpected behavior.

Uncovered this bug when I found that math libc tests, part of the ELF enclave did not run correctly on Windows.

**Comment by johnkord** [comment]
@anitagov Are there any PRs associated with this issue? Do you happen to know if this was fixed yet?

**Comment by anitagov** [comment]
My PR #1508 currently in flight restores and saves SSE register state i.e. MXCSR in the Windows host enclave entry/exit flows.  Ran into issues with restoring FPU register state and will debug further after my PR #1508 gets in as this is non-trivial.

Will keep this issue updated. Please do not close.

**Comment by anitagov** [comment]
However, cannot save/restore the FPU control word as the default FPU state on Linux is **0x37f** but on Windows (with Visual Studio 2017) ix **0x27f** (observed from debugging). Bits 8 and 9 in the x87 FPU control word refer to the _Precision Control field_ and 3 indicates Double Extended Precision (64 bits) but 2 indicates Double Precision (53 bits), the default for Windows. See table below for the Precision Control Field table from the Intel Software Developer Manual.

So, saving and restoring the Windows host state causes the ELF enclaves to lose precision. Hence, we do not need to do this.


![image](https://user-images.githubusercontent.com/16311437/57974055-0c82c580-7967-11e9-9b04-d3691695d2fb.png)

**Comment by anitagov** [comment]
With my fix for #1508 , I added saving and restoring MXCSR in the Windows host enclave entry/exit flow. We do not need to save/restore the Windows host FPU state as explained above. So, closing this.
