### ISSUE TITLE
Investigate ecall_ocall test in the case where it intermittently hangs

### ISSUE THREAD

**Issue by johnkord** [Microsoft/openenclave#1507]
The ecall_ocall test will sometimes hang (seemingly) forever.

There are two tasks to this issue:

- [x] Specific a ctest timeout for this individual test to be approximately 5 times as long as the test normally takes to complete. (Edit: Not necessary now that this issue is fixed)
- [x] Investigate what may be causing this test to hang, and fix it. Solved by PR https://github.com/Microsoft/openenclave/pull/1512

I've assigned @ionutbalutoiu to this issue, but the second item in this issue may need some of the team's expertise to help analyze. It could be a good opportunity to learn more about the inner workings of enclaves!

**Comment by johnkord** [comment]
Some examples of the test hanging:

jenkins.eastus.cloudapp.azure.com/blue/organizations/jenkins/Bors/detail/staging/642/pipeline/57)
* [Bors-trying#732](https://oe-jenkins.eastus.cloudapp.azure.com/blue/organizations/jenkins/Bors/detail/trying/732/pipeline/43)
* [Bors-trying#736](https://oe-jenkins.eastus.cloudapp.azure.com/blue/organizations/jenkins/Bors/detail/trying/736/pipeline/54)
* [Bors-trying#738](https://oe-jenkins.eastus.cloudapp.azure.com/blue/organizations/jenkins/Bors/detail/trying/738/pipeline/53)
* [Bors-trying#739](https://oe-jenkins.eastus.cloudapp.azure.com/blue/organizations/jenkins/Bors/detail/trying/739/pipeline/58)

**Comment by anitagov** [comment]
Can we get this test pulled out until it is trouble-shooted as it is blocking my PR? Thanks.

**Comment by johnkord** [comment]
@anitagov Is it reproing consistently now for you?

Tagging @anakrish who may know more about this test!

**Comment by anakrish** [comment]
Sure. I will take a look at this.

**Comment by anitagov** [comment]
@johnkord - It reproduced twice in a row.

**Comment by ionutbalutoiu** [comment]
@johnkord 

The actual issue was solved by @anakrish as part of https://github.com/Microsoft/openenclave/pull/1512. Thanks!

Regarding your comment about playing with `ctest` timeout parameter: Do you think it's necessary ? We have the [timeout](https://github.com/Microsoft/openenclave/blob/1ca8377aca2200f707d6ca704c3dfa156b63ee30/.jenkins/Jenkinsfile#L11) instance from the Jenkinsfile, and we should be covered in case something hangs again.

**Comment by johnkord** [comment]
Closing as resolved
