### ISSUE TITLE
Unsupported libcxx test issues categorized here

### ISSUE THREAD

**Issue by CodeMonkeyLeet** [Microsoft/openenclave#151]
This issue tracks libcxx tests we would like to run but the tests require features that are not supported in the enclave unrelated to the functionality being tested:

- [x] Requires pthread_create():
    + 3rdparty/libcxx/libcxx/test/libcxx/utilities/memory/util.smartptr/race_condition.pass.cpp (Enabled with PR #1070 )
- [x] Enclave abort() results in SIGILL instead of SIGABRT: ==> This is expected behavior with SGX enclaves. So test will not be supported
    + 3rdparty/libcxx/libcxx/test/libcxx/debug/debug_abort.pass.cpp
- [x] Requires c++17 support: Currently, libcxx enclaves are still built with c++14. New issue #1091 opened to track this.
    + 3rdparty/libcxx/libcxx/test/libcxx/language.support/support.dynamic/new_faligned_allocation.sh.cpp
    + 3rdparty/libcxx/libcxx/test/std/algorithms/alg.sorting/alg.clamp/clamp.comp.pass.cpp
    + 3rdparty/libcxx/libcxx/test/std/algorithms/alg.sorting/alg.clamp/clamp.pass.cpp
    + 3rdparty/libcxx/libcxx/test/std/language.support/support.types/byte.pass.cpp
- [x] Requires libgcc support: Enabled these tests with clang. (PR #1082 )
    + 3rdparty/libcxx/libcxx/test/libcxx/containers/unord/next_pow2.pass.cpp
    + 3rdparty/libcxx/libcxx/test/std/utilities/template.bitset/bitset.members/count.pass.cpp
- [x] Locales other than C or POSIX locales are unsupported: => These will never be supported. 
    + 3rdparty/libcxx/libcxx/test/std/localization/locale.categories/category.collate/locale.collate.byname/compare.pass.cpp
   + 3rdparty/libcxx/libcxx/test/std/localization/locale.categories/category.collate/locale.collate.byname/hash.pass.cpp
   + 3rdparty/libcxx/libcxx/test/std/localization/locale.categories/category.collate/locale.collate.byname/transform.pass.cpp
   + 3rdparty/libcxx/libcxx/test/std/localization/locale.categories/category.collate/locale.collate.byname/types.pass.cpp
   + 3rdparty/libcxx/libcxx/test/std/localization/locale.categories/category.ctype/locale.codecvt.byname/ctor_wchar_t.pass.cpp
   + 3rdparty/libcxx/libcxx/test/std/localization/locale.categories/category.ctype/locale.ctype.byname/is_1.pass.cpp
   + 3rdparty/libcxx/libcxx/test/std/localization/locale.categories/category.ctype/locale.ctype.byname/is_many.pass.cpp
   + 3rdparty/libcxx/libcxx/test/std/localization/locale.categories/category.ctype/locale.ctype.byname/narrow_1.pass.cpp
   + 3rdparty/libcxx/libcxx/test/std/localization/locale.categories/category.ctype/locale.ctype.byname/narrow_many.pass.cpp
   + 3rdparty/libcxx/libcxx/test/std/localization/locale.categories/category.ctype/locale.ctype.byname/scan_is.pass.cpp
   + 3rdparty/libcxx/libcxx/test/std/localization/locale.categories/category.ctype/locale.ctype.byname/scan_not.pass.cpp
   + 3rdparty/libcxx/libcxx/test/std/localization/locale.categories/category.ctype/locale.ctype.byname/tolower_1.pass.cpp
   + 3rdparty/libcxx/libcxx/test/std/localization/locale.categories/category.ctype/locale.ctype.byname/tolower_many.pass.cpp
   + 3rdparty/libcxx/libcxx/test/std/localization/locale.categories/category.ctype/locale.ctype.byname/toupper_1.pass.cpp
   + 3rdparty/libcxx/libcxx/test/std/localization/locale.categories/category.ctype/locale.ctype.byname/toupper_many.pass.cpp
   + 3rdparty/libcxx/libcxx/test/std/localization/locale.categories/category.ctype/locale.ctype.byname/types.pass.cpp
   + 3rdparty/libcxx/libcxx/test/std/localization/locale.categories/category.ctype/locale.ctype.byname/widen_1.pass.cpp
   + 3rdparty/libcxx/libcxx/test/std/localization/locale.categories/category.ctype/locale.ctype.byname/widen_many.pass.cpp
   + 3rdparty/libcxx/libcxx/test/std/localization/locale.categories/category.monetary/locale.money.get/locale.money.get.members/get_long_double_en_US.pass.cpp
   + 3rdparty/libcxx/libcxx/test/std/localization/locale.categories/category.monetary/locale.money.get/locale.money.get.members/get_long_double_fr_FR.pass.cpp
   + 3rdparty/libcxx/libcxx/test/std/localization/locale.categories/category.monetary/locale.money.get/locale.money.get.members/get_long_double_ru_RU.pass.cpp
   + 3rdparty/libcxx/libcxx/test/std/localization/locale.categories/category.monetary/locale.money.get/locale.money.get.members/get_long_double_zh_CN.pass.cpp
   + 3rdparty/libcxx/libcxx/test/std/localization/locale.categories/category.monetary/locale.money.get/locale.money.get.members/get_string_en_US.pass.cpp
   + 3rdparty/libcxx/libcxx/test/std/localization/locale.categories/category.monetary/locale.moneypunct.byname/curr_symbol.pass.cpp
   + 3rdparty/libcxx/libcxx/test/std/localization/locale.categories/category.monetary/locale.moneypunct.byname/decimal_point.pass.cpp
   + 3rdparty/libcxx/libcxx/test/std/localization/locale.categories/category.monetary/locale.moneypunct.byname/frac_digits.pass.cpp
   + 3rdparty/libcxx/libcxx/test/std/localization/locale.categories/category.monetary/locale.moneypunct.byname/grouping.pass.cpp
   + 3rdparty/libcxx/libcxx/test/std/localization/locale.categories/category.monetary/locale.moneypunct.byname/negative_sign.pass.cpp
   + 3rdparty/libcxx/libcxx/test/std/localization/locale.categories/category.monetary/locale.moneypunct.byname/neg_format.pass.cpp
   + 3rdparty/libcxx/libcxx/test/std/localization/locale.categories/category.monetary/locale.moneypunct.byname/pos_format.pass.cpp
   + 3rdparty/libcxx/libcxx/test/std/localization/locale.categories/category.monetary/locale.moneypunct.byname/positive_sign.pass.cpp
   + 3rdparty/libcxx/libcxx/test/std/localization/locale.categories/category.monetary/locale.moneypunct.byname/thousands_sep.pass.cpp
   + 3rdparty/libcxx/libcxx/test/std/localization/locale.categories/category.monetary/locale.money.put/locale.money.put.members/put_long_double_en_US.pass.cpp
   + 3rdparty/libcxx/libcxx/test/std/localization/locale.categories/category.monetary/locale.money.put/locale.money.put.members/put_long_double_fr_FR.pass.cpp
   + 3rdparty/libcxx/libcxx/test/std/localization/locale.categories/category.monetary/locale.money.put/locale.money.put.members/put_long_double_ru_RU.pass.cpp
   + 3rdparty/libcxx/libcxx/test/std/localization/locale.categories/category.monetary/locale.money.put/locale.money.put.members/put_long_double_zh_CN.pass.cpp
   + 3rdparty/libcxx/libcxx/test/std/localization/locale.categories/category.monetary/locale.money.put/locale.money.put.members/put_string_en_US.pass.cpp
   + 3rdparty/libcxx/libcxx/test/std/localization/locale.categories/category.numeric/locale.nm.put/facet.num.put.members/put_long_double.pass.cpp
   + 3rdparty/libcxx/libcxx/test/std/localization/locale.categories/category.time/locale.time.get.byname/date_order.pass.cpp
   + 3rdparty/libcxx/libcxx/test/std/localization/locale.categories/category.time/locale.time.get.byname/date_order_wide.pass.cpp
   + 3rdparty/libcxx/libcxx/test/std/localization/locale.categories/category.time/locale.time.get.byname/get_date.pass.cpp
   + 3rdparty/libcxx/libcxx/test/std/localization/locale.categories/category.time/locale.time.get.byname/get_date_wide.pass.cpp
   + 3rdparty/libcxx/libcxx/test/std/localization/locale.categories/category.time/locale.time.get.byname/get_monthname.pass.cpp
   + 3rdparty/libcxx/libcxx/test/std/localization/locale.categories/category.time/locale.time.get.byname/get_monthname_wide.pass.cpp
   + 3rdparty/libcxx/libcxx/test/std/localization/locale.categories/category.time/locale.time.get.byname/get_one.pass.cpp
   + 3rdparty/libcxx/libcxx/test/std/localization/locale.categories/category.time/locale.time.get.byname/get_one_wide.pass.cpp
   + 3rdparty/libcxx/libcxx/test/std/localization/locale.categories/category.time/locale.time.get.byname/get_time.pass.cpp
   + 3rdparty/libcxx/libcxx/test/std/localization/locale.categories/category.time/locale.time.get.byname/get_time_wide.pass.cpp
   + 3rdparty/libcxx/libcxx/test/std/localization/locale.categories/category.time/locale.time.get.byname/get_weekday.pass.cpp
   + 3rdparty/libcxx/libcxx/test/std/localization/locale.categories/category.time/locale.time.get.byname/get_weekday_wide.pass.cpp
   + 3rdparty/libcxx/libcxx/test/std/localization/locale.categories/category.time/locale.time.get.byname/get_year.pass.cpp
   + 3rdparty/libcxx/libcxx/test/std/localization/locale.categories/category.time/locale.time.get.byname/get_year_wide.pass.cpp
   + 3rdparty/libcxx/libcxx/test/std/localization/locale.categories/category.time/locale.time.put.byname/put1.pass.cpp
   + 3rdparty/libcxx/libcxx/test/std/localization/locale.categories/facet.numpunct/locale.numpunct.byname/decimal_point.pass.cpp
   + 3rdparty/libcxx/libcxx/test/std/localization/locale.categories/facet.numpunct/locale.numpunct.byname/grouping.pass.cpp
   + 3rdparty/libcxx/libcxx/test/std/localization/locale.categories/facet.numpunct/locale.numpunct.byname/thousands_sep.pass.cpp
   + 3rdparty/libcxx/libcxx/test/std/localization/locales/locale.convenience/conversions/conversions.buffer/overflow.pass.cpp
   + 3rdparty/libcxx/libcxx/test/std/localization/locales/locale.convenience/conversions/conversions.buffer/pbackfail.pass.cpp
   + 3rdparty/libcxx/libcxx/test/std/localization/locales/locale.convenience/conversions/conversions.buffer/seekoff.pass.cpp
   + 3rdparty/libcxx/libcxx/test/std/localization/locales/locale.convenience/conversions/conversions.buffer/test.pass.cpp
   + 3rdparty/libcxx/libcxx/test/std/localization/locales/locale.convenience/conversions/conversions.buffer/underflow.pass.cpp
   + 3rdparty/libcxx/libcxx/test/std/localization/locales/locale/locale.cons/assign.pass.cpp
   + 3rdparty/libcxx/libcxx/test/std/localization/locales/locale/locale.cons/char_pointer.pass.cpp
   + 3rdparty/libcxx/libcxx/test/std/localization/locales/locale/locale.cons/copy.pass.cpp
   + 3rdparty/libcxx/libcxx/test/std/localization/locales/locale/locale.cons/default.pass.cpp
   + 3rdparty/libcxx/libcxx/test/std/localization/locales/locale/locale.cons/locale_char_pointer_cat.pass.cpp
   + 3rdparty/libcxx/libcxx/test/std/localization/locales/locale/locale.cons/locale_facetptr.pass.cpp
   + 3rdparty/libcxx/libcxx/test/std/localization/locales/locale/locale.cons/locale_locale_cat.pass.cpp
   + 3rdparty/libcxx/libcxx/test/std/localization/locales/locale/locale.cons/locale_string_cat.pass.cpp
   + 3rdparty/libcxx/libcxx/test/std/localization/locales/locale/locale.cons/string.pass.cpp
   + 3rdparty/libcxx/libcxx/test/std/localization/locales/locale/locale.members/name.pass.cpp
   + 3rdparty/libcxx/libcxx/test/std/localization/locales/locale/locale.operators/eq.pass.cpp
   + 3rdparty/libcxx/libcxx/test/std/localization/locales/locale/locale.statics/global.pass.cpp

**Comment by anitagov** [comment]
Changing title to indicate that these tests have been moved to tests.unsupported as they are not in tests.broken.

**Comment by anitagov** [comment]
PR #1070 - Enabled 1 libcxx thread test
PR #1082 - Enabled 2 libcxx tests that build and run with Clang but do not build with gcc

**Comment by anitagov** [comment]
Enclave abort() results in SIGILL instead of SIGABRT:
3rdparty/libcxx/libcxx/test/libcxx/debug/debug_abort.pass.cpp

This is expected enclave behavior that abort() will result in SIGILL and not SIGABRT. This test cannot be supported.

**Comment by anitagov** [comment]
Opened new issue #1091 to cover the libcxx tests that require the C++17 flag. So, closing this issue.
