### ISSUE TITLE
Enclaves failing with OE_IOCTL_FAILED for OE on platforms without AVX

### ISSUE THREAD

**Issue by jmechalas** [Microsoft/openenclave#1511]
On a fresh Ubuntu 16.04.5 LTS system (local, bare-metal; not an Azure VM), I built openenclave in SGX1 mode (with no FLC) [using the directions here](https://github.com/Microsoft/openenclave/blob/master/docs/GettingStartedDocs/SGX1GettingStarted.md), on the master branch. This resulted in 147/173 failed tests from `ctest` and enclaves that fail to load on an OE_IOCTL_FAILED error:

```
johnm@sgxvmoe03:~/src/samples/helloworld$ make run
host/helloworldhost ./enc/helloworldenc.signed
21:26:09:066563 tid(0x7f6c3e805700) (H)[ERROR]rc=0xffffffff
[/home/johnm/git/openenclave/host/sgx/linux/sgxioctl.c sgx_ioctl_enclave_create:64]
21:26:09:066717 tid(0x7f6c3e805700) (H)[ERROR]:OE_IOCTL_FAILED[/home/johnm/git/openenclave/host/sgx/sgxload.c oe_sgx_create_enclave:526]
21:26:09:066799 tid(0x7f6c3e805700) (H)[ERROR]:OE_IOCTL_FAILED[/home/johnm/git/openenclave/host/sgx/create.c oe_sgx_build_enclave:658]
21:26:09:066956 tid(0x7f6c3e805700) (H)[ERROR]:OE_IOCTL_FAILED[/home/johnm/git/openenclave/host/sgx/create.c oe_create_enclave:790]
oe_create_helloworld_enclave(): result=15 (OE_IOCTL_FAILED)
Makefile:13: recipe for target 'run' failed
make: *** [run] Error 1
```

Examining the enclaves in the sample apps shows that they all contain the undefined symbol `__tls_get_addr`:

```
$ nm -A */enc*/*.signed | grep -i ' u '
data-sealing/enc1/enclave_a_v1.signed:                 U __tls_get_addr
data-sealing/enc2/enclave_a_v2.signed:                 U __tls_get_addr
data-sealing/enc3/enclave_b.signed:                 U __tls_get_addr
file-encryptor/enc/file-encryptorenc.signed:                 U __tls_get_addr
helloworld/enc/helloworldenc.signed:                 U __tls_get_addr
```

**Comment by jmechalas** [comment]
The undefined symbol may be a red herring, as I was able to build OE on another 16.04 LTS system and get a successful result. There are some differences between the two systems (kernel versions, and possibly some software versions) which I am exploring.

**Comment by jmechalas** [comment]
Does Open Enclave have a dependency on AVX instructions?

My failing systems are:

- Intel NUC7PJYH, Pentium Silver J5005 (supports SGX1, SGX2, and FLC)
- KVM/QEMU guest on a Xeon E-2176G (CFL processor, supports SGX1 and FLC)

My passing system:

- Intel Xeon E3-1270 v6 (supports SGX1, but not FLC)

The Pentium Silver line does not support AVX at all. The Xeon E-2176G does, but a bug in kvm-sgx kernel v4.13r3 through v4.19 prevents AVX instructions from being usable in an enclave.

The Xeon E-1270 v6 supports AVX, and OpenEnclave works. The kernel versions between all three of these systems are identical (I just verified by re-imaging everything) and AVX support is the only thing I can think of that is different between them.

Coincidentally, the Pentium Silver also can't run Open Enclave in the SGX1+FLC mode, whether I build it from source or install the pre-compiled binary packages.

**Comment by anakrish** [comment]
@johnkord @CodeMonkeyLeet Can you please chime in about what could be happening here?

RE: __tls_get_addr. When thread locals are used, the compiler generates calls to the __tls_get_addr function to obtain the location of a thread-local variable. The generated code assumes the worst case (i.e multiple shared libraries). The linker optimizes away the calls to __tls_get_addr since we compile the enclave as a single shared library using the -pie flag. That undefined symbol can be ignored.
If we encounter a case where there is a call to _tls_get_addr, we are planning to add an implementation for it; however it indicates that such a tls variable is not optimal.

**Comment by jmechalas** [comment]
@anakrish Thank you for the explanation on __tls_get_addr.

Something that occurs to me re: AVX is the valid bits of SECS.ATTRIBUTES that can be set with ECREATE. This is obtained from cpuid leaf 0x12 subleaf 0x1. The XFRM attributes are found in EDX:ECX, and these control whether or not the AVX family (AVX, AVX2, FMA, etc.) are available in an enclave.

Is there an explicit check for CPUID.(EAX=12H, ECX=1):ECX[2]=1 (i.e., SEC.ATTRIBUES.XFRM == 3)?

**Comment by CodeMonkeyLeet** [comment]
@jmechalas Yes, I think you have found the key difference. OE doesn't technically need to use AVX inside the enclaves, but it attempts to preserve AVX state and defaults to creating enclaves with AVX enabled; `SEC.ATTRIBUTES.XFRM` is set to 7 by default on enclave creation just to exercise the XSAVE handling, but it needs to checking for the presence of AVX first.

Thanks for the analysis, it is much appreciated!

For maintainers: we also default the `SIGSTRUCT.ATTRIBUTES.XFRM` to 7 and that should probably be fixed up as well; it doesn't really matter since it's masked out, but there's no real reason for that to be 7 either.

**Comment by jmechalas** [comment]
Thanks, @CodeMonkeyLeet. I'll watch for the patch so I can pull it into my repo.

**Comment by anakrish** [comment]
@johnkord @gupta-ak Can you prioritize this issue.

**Comment by anitagov** [comment]
I am working on this.

**Comment by jmechalas** [comment]
Just a quick confirmation: a new release of kvm-sgx was posted this week which fixes `SEC.ATTRIBUTES.XFRM` in guests, and I just verified that OE works in those guests now (they didn't before).

**Comment by anitagov** [comment]
This is great info @jmechalas

**Comment by anitagov** [comment]
John @jmechalas - I have a fix that works on Linux host. Will you be able to test it on your Pentium Silver platform? If so, I can provide a patch. Please let me know.

**Comment by jmechalas** [comment]
Yes, I can test it straight away. Should I apply it to master or a particular branch?

**Comment by anitagov** [comment]
@jmechalas - This is great John. You can directly build OE from my branch located at: https://github.com/Microsoft/openenclave/tree/anitagov.noavx.fix
If that doesn't work, I will provide a patch with details. Thanks.

**Comment by jmechalas** [comment]
170/173 tests passed in SGX1+FLC mode. The failing tests were on attestation, which I assume is expected in my isolated environment.

**Comment by anitagov** [comment]
Great info. Thanks a bunch @jmechalas . Yes, the attestation tests will fail in your isolated environment.

**Comment by sniperyyc** [comment]
I encounter the same problem as @jmechalas and could not solve by building it from source. Could you provide a way to help me fix this? Thanks!

**Comment by anitagov** [comment]
@sniperyyc - Which SGX platform are you using? Is this an Intel Silver line that supports SGX but not AVX?

**Comment by sniperyyc** [comment]
I am currently using Intel(R) Xeon(R) CPU E3-1270 v6 + ubuntu 16.04 which I suppose supporting SGX (and not FLC). Since I cannot run the oesgx utility tool as specified in the repo, I am not sure about this. Is there any way to check that?

**Comment by jmechalas** [comment]
That system has AVX and thus should not have been this exact problem. I hate to ask the "is it plugged in?" question, but are you sure Intel SGX is enabled in your BIOS?

You can verify SGX support with [this application](https://github.com/intel/sgx-software-enable). It's a standalone utility and does not require an SGX toolkit to use. Run `sgx-enable --status`

**Comment by anitagov** [comment]
Thanks @jmechalas . Your input came as I was typing this in.

@sniperyyc - It appears that you are running a KabyLake i.e. SGX1 platform. You need to make sure that SGX is enabled in the BIOS. The attestation tests will fail on SGX1 platform as we support that only on FLC platforms running on Azure VMs.

This platform supports AVX and so you should hit the issue that @jmechalas hit with the Intel Silver line.

**Comment by sniperyyc** [comment]
Thanks @jmechalas and @anitagov ! I just checked my system setting using your script and it shows that

> Intel SGX is already enabled on this system

I also checked the BIOS setting and the SGX is "ON". I am considering installing openenclave from scratch. Could you provide me some steps and links to do that? (Some of the readme files from openenclave repo are outdated and cannot be used). 

Currently I follow the procedure on: [https://github.com/Microsoft/openenclave/blob/master/docs/GettingStartedDocs/install_oe_sdk.md](url) but it fails with the above issue. Should I use another way to do that? Thanks a lot for all your response!

**Comment by johnkord** [comment]
Hey @sniperyyc ! I think your system currently has the DCAP SGX driver installed.  I think you need the non-DCAP SGX driver. You can find the latest version of the non-DCAP SGX driver here I think: https://01.org/intel-softwareguard-extensions/downloads/intel-sgx-linux-2.4-release

The DCAP SGX driver can only be installed on SGX systems with FLC, which is what the install_oe_sdk.md guide expects. The DCAP SGX driver installs the "intel_sgx" module, whereas the non-DCAP SGX driver installs the "isgx" module.

Try installing this "isgx" module and see what happens. You might have to remove the intel_sgx module, but I'm not sure.  Run this command to see if an sgx device now exists on your system: `ls /dev/*sgx`. You should see /dev/isgx if the non-DCAP SGX driver is installed properly. (The /dev/sgx device will exist if you're using the DCAP driver and you're on an SGX system with FLC)

**Comment by anitagov** [comment]
@sniperyyc - Please refer to the document: https://github.com/Microsoft/openenclave/blob/master/docs/GettingStartedDocs/SGX1GettingStarted.md.
It appears that you are installing an incorrect driver.

**Comment by anitagov** [comment]
Thanks @johnkord .
@sniperyyc - Please ignore my previous remark (which I just deleted).

**Comment by sniperyyc** [comment]
@johnkord Thanks a lot for the detailed info! I try to install the two .bin files in the link you show, and when I do `lsmod | grep sgx`, it shows:

> isgx                   45056  0
intel_sgx              94208  0

However, the `ls /dev/isgx` still does not exist. Do I install the driver in a wrong way?

**Comment by johnkord** [comment]
@sniperyyc Hmm. Try removing the intel_sgx module with `rmmod intel_sgx`. Also maybe try rebooting?

If that doesn't make the device appear, then I'm not sure! This seems like an issue you might want to ask Intel about (or possibly someone else here, that might have an answer for you). Fundamentally, you won't be able to create enclaves until Intel's SGX driver gets installed properly and the device at /dev/isgx exists (or /dev/sgx if you had FLC).

By the way, is this system you have running as a VM? If so, does the hypervisor support SGX and have enabled it for your VM?

What happens when you try running the "oesgx" binary? It should be installed to /opt/openenclave/bin/oesgx if you've installed the OE SDK. I'm curious as to what it reports.

**Comment by sniperyyc** [comment]
When I run "oesgx" binary, I get the following result:

> CPU supports Software Guard Extensions:SGX1
MaxEnclaveSize_64: 2^(36)

I think the results look good? I am running SGX on a physical machine instead of a server and my concern is that I may still not install the driver correctly? I tried to install the two .bin files in this link: [https://01.org/intel-softwareguard-extensions/downloads/intel-sgx-linux-2.4-release](url) and it shows installation successful while the device "/dev/isgx" does not show. Is there any possible reason for that issue?

**Comment by sniperyyc** [comment]
> When I run "oesgx" binary, I get the following result:
> 
> > CPU supports Software Guard Extensions:SGX1
> > MaxEnclaveSize_64: 2^(36)
> 
> I think the results look good?
> 
> I am running SGX on a physical machine instead of a VM and my concern is that I may still not install the driver correctly? I tried to install the two .bin files in this link: [https://01.org/intel-softwareguard-extensions/downloads/intel-sgx-linux-2.4-release](url) and it shows installation successful while the device "/dev/isgx" does not show. Is there any possible reason for that issue?
> 
> One maybe irrelevant question, when I do rmmod intel_sgx, the mode intel_sgx is still there after reboot, does that matter?

I tried to clean the two module I installed and follow the steps exactly here [https://github.com/Microsoft/openenclave/blob/bf0b2292545dfabf7d1e8fe1661bce79b67ad948/docs/GettingStartedDocs/SGX1GettingStarted.md](url), and it works now! Thanks @jmechalas @johnkord @anitagov and everyone else for your help!

**Comment by anitagov** [comment]
@sniperyyc - Great that it worked and that the SGX1GettingStarted.md doc also helped.

**Comment by anitagov** [comment]
@jmechalas - My fix for setting SECS.ATTRIBUTES.XFRM correctly is in the master. Can you please checkout the master and let me know if you are still able to build and test on the Pentium Silver platform? You will continue to see the failures with attestation tests if the platform does not have FLC. But can you let me know if the test props (where I made the changes) continues to PASS? Thanks.

**Comment by anitagov** [comment]
@jmechalas - Wondering if you want to fix the title to include non-AVX so that this issue does not get overloaded. Will also close this issue once I hear back from you that things are resolved.

**Comment by jmechalas** [comment]
173/174 tests passed in SGX1+FLC mode on Pentium Silver using the master branch. Failing test was "samples", and specifically the remote attestation sample, as expected. So the master branch looks good to me. Thank you!

**Comment by anitagov** [comment]
Thanks a bunch @jmechalas for your feedback. 
Closing this as PR #1540 has been merged to master.

**Comment by danintel** [comment]
Here is my experience. If the `/dev/sgx` driver (`intel_sgx`) is installed (the DCAP Intel SGX driver), it has to be removed first (with the correct `uninstall.sh`, which may be somewhere under `/opt/intel/`). Only then can you install the non-DCAP `/dev/isgx` driver (the one that uses Intel IAS), module `isgx`).

Be careful not to overwrite the `uninstall.sh` script of the old driver with the new driver. Uninstall the `/dev/sgx` driver first before even unzipping/untarring the driver files.

You can also go the other way (from `/dev/isgx` to `/dev/sgx`).

**Comment by johnkord** [comment]
Thanks for this great explanation of how to change Intel drivers @danintel !
