### ISSUE TITLE
Disable all Simulation Mode tests on Windows in CI

### ISSUE THREAD

**Issue by johnkord** [Microsoft/openenclave#1519]

**Comment by johnkord** [comment]
@anakrish commented in #1502 to disable all Simulation mode tests on Windows until the issue he mentions can be addressed.

**Comment by ionutbalutoiu** [comment]
@johnkord @anakrish Thanks for this info!

Currently, the upstream `master` branch doesn't have any CI testing stages with Windows simulation.

We had the following `WiP` issues & PRs to get this up and running:

* Simulation testing on Windows https://github.com/Microsoft/openenclave/issues/1293
    * Add simulation testing stages to Jenkinsfile https://github.com/Microsoft/openenclave/pull/1407
* Flaky Windows simulation tests discovered https://github.com/Microsoft/openenclave/issues/1474
   * Skip any known flaky Windows simulation tests https://github.com/Microsoft/openenclave/pull/1502

I just moved these items to the backlog until we're ready to merge them upstream.
