### ISSUE TITLE
Inconsistent CI results from the `scripts/check-ci` checks

### ISSUE THREAD

**Issue by anakrish** [Microsoft/openenclave#1526]
The following run errors out in only one CI node:
https://oe-jenkins.eastus.cloudapp.azure.com/blue/organizations/jenkins/Bors/detail/trying/757/pipeline/

+ ./scripts/check-ci

In scripts/clangw line 68:

        clang -target x86_64-pc-linux ${args[@]} -fuse-ld="`which ld.lld`"

                                      ^-- SC2068: Double quote array expansions, otherwise they're like $* and break on spaces.

                                                           ^-- SC2006: Use $(..) instead of legacy `..`.

In scripts/clangw line 70:

        clang -target x86_64-pc-linux ${args[@]}

                                      ^-- SC2068: Double quote array expansions, otherwise they're like $* and break on spaces.

In scripts/clangw line 74:

call_clang $@

           ^-- SC2068: Double quote array expansions, otherwise they're like $* and break on spaces.

However, it should error out in all nodes or none.

@johnkord @andschwa @ionutbalutoiu @aserdean

**Comment by andschwa** [comment]
I would actually heed these two warnings. Are you purposefully wanting to split the array arguments on spaces? I wouldn't think so... I would think you'd want each argument quoted correctly. [This is what I follow.](http://mywiki.wooledge.org/BashGuide/Arrays#Using_Arrays)

**Comment by ionutbalutoiu** [comment]
@anakrish 

I think there's a misunderstanding here. Your above errors are not related to the Windows CI machines. Those are linters errors and we don't even run linter checks on Windows machines.

Let me bring some context here. There's a bash script [scripts/check-ci](https://github.com/Microsoft/openenclave/blob/master/scripts/check-ci) that runs the following:
* [check-license](https://github.com/Microsoft/openenclave/blob/master/scripts/check-license) - Prints a list of sources missing the license header.
* [check-linters](https://github.com/Microsoft/openenclave/blob/master/scripts/check-linters) - Runs ShellCheck across scripts to lint them.
* [format-code](https://github.com/Microsoft/openenclave/blob/master/scripts/format-code) - Formats Open Enclave C/C++ code using clang-format. However, the parameter [whatif](https://github.com/Microsoft/openenclave/blob/8e95a0df00657e0704ac8c07b22063004cabdd86/scripts/format-code#L92-L93) is passed.

This [scripts/check-ci](https://github.com/Microsoft/openenclave/blob/master/scripts/check-ci) script is run **only** as part of the following [CI testing stages](https://github.com/Microsoft/openenclave/blob/972fe0c9b0efbfd93802c10cb13ba9a5c84a9cb8/.jenkins/Jenkinsfile#L203-L204), which executes this [piece of code](https://github.com/Microsoft/openenclave/blob/972fe0c9b0efbfd93802c10cb13ba9a5c84a9cb8/.jenkins/Jenkinsfile#L104-L116) on an Ubuntu 16.04 machine & an Ubuntu 18.04 machine.

Shortly speaking, there are **only** two separate CI testing stage (on Ubuntu 16.04 & 18.04) executing the [scripts/check-ci](https://github.com/Microsoft/openenclave/blob/master/scripts/check-ci) script. 

However, there is is an inconsistency here, and it's probably your concern with this issue. The `spellcheck` APT package from Ubuntu 18.04 is version `0.4.6`, while the `spellcheck` APT package from Ubuntu 16.04 is version `0.3.7`.

To be honest, I don't believe we need to run `check-ci` script on all platforms, and we should have it run only on a single platform. I'd suggest that we go with Ubuntu 18.04 only.

I assume that given the same `spellcheck` binary version, the output will be the same on all other platforms. But we should avoid running multiple versions of the same binary as part of the same CI pipeline.

@andschwa, @johnkord @anakrish What do you think about keeping only the Ubuntu 18.04 `check-ci` script run, and remove the Ubuntu 16.04 run ?

**Comment by ionutbalutoiu** [comment]
Changed the title to reflect the actual issue.

Into the internal sync meeting from yesterday, we agreed to have `scripts/check-ci` check only on Ubuntu 18.04. Thus, the CI won't be reporting inconsistent results for the linter checks.

I opened https://github.com/Microsoft/openenclave/issues/1547 to track this going forward. Closing this.
