### ISSUE TITLE
Thread Locals: threading-model and assertion

### ISSUE THREAD

**Issue by anakrish** [Microsoft/openenclave#1536]
This issue captures the final tweaks needed to support thread-local storage in 0.5x

- Decide whether to specify the threading-model as part of compiler options. If so, add it to pkgconfig.
   Choose the correct threading model, inital-exec or local-exec.
   If not specified as compiler options, then document the options if the end-user gets a link error with __tls_get_addr

- Investigate and remove the assertion put in place to detect when thread-locals information in ELF section and program header differ

**Comment by anakrish** [comment]
Update:

- The thread-local model is now specified via -ftls-model=local-exec. This is the most optimal thread-local model for enclaves.
- With -ftls-model specified as local-exec, the compiler does not generate a reference to _tls_get_addr
- Assertion has been put in place to detect when the thread-local information found in section and program header differ. We have not hit it so far other than a case where there is no .tdata and the linker uses the .tbss section to populate the program header; this scenario has been handled to not assert.

**Comment by anakrish** [comment]
Fixed.

**Comment by andschwa** [comment]
Closed via #1580.
