### ISSUE TITLE
oeedger8r-generated code not compatible with -Werror=strict-aliasing

### ISSUE THREAD

**Issue by letmaik** [Microsoft/openenclave#1541]
```
interface_u.c:179:5: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
     *(uint8_t**)&_pargs_out = _output_buffer;
```

This is using gcc 7.3.0 and a recent build of OE (e504559e9ea03dfd).

**Comment by anakrish** [comment]
@andschwa Can you take a look?

**Comment by andschwa** [comment]
@letmaik Can you give me some sample code (like the EDL you were using)? I'm having trouble repro'ing this. I removed `-fno-strict-aliasing` and set `-Werror=strict-aliasing` on our `edl_enc` test code, which I would have expected to repro, but tit didn't. This was also with GCC 7.3. Thanks!

**Comment by letmaik** [comment]
```
    trusted {
        public int a([in, count=c] const char* d, size_t c);
        public int b([user_check] char** e, [in, count=f] size_t* g, size_t f,  [out, count=i] char* h, size_t i, [out, count=1] size_t* j);
    };
```

**Comment by andschwa** [comment]
Thanks @letmaik! I have a test added that successfully repros this now. I'll get it fixed!
