### ISSUE TITLE
Keep only 18.04 testing stage with `scripts/check-ci` check

### ISSUE THREAD

**Issue by ionutbalutoiu** [Microsoft/openenclave#1547]
Right now, we run the `scripts/check-ci` script as part of two testing stages (on Ubuntu 16.04 and Ubuntu 18.04). This is part of [Check dev flows](https://github.com/Microsoft/openenclave/blob/972fe0c9b0efbfd93802c10cb13ba9a5c84a9cb8/.jenkins/Jenkinsfile#L104-L116) stage inside the `def checkDevFlows(String version)`, which is run on both platforms [here](https://github.com/Microsoft/openenclave/blob/972fe0c9b0efbfd93802c10cb13ba9a5c84a9cb8/.jenkins/Jenkinsfile#L203-L204).

The `scripts/check-ci` script checks license headers, runs spellcheck and does a dry run of clang-format. Besides the fact that it's not needed to run this twice, the binaries versions (spellcheck and clang-format) from Ubuntu 16.04 and Ubuntu 18.04 may differ and we can end up with inconsistent results.

We need to remove the `scripts/check-ci` testing stage run from the `checkDevFlows` method, and have it run in the CI only for the Ubuntu 18.04 flavor.

**Comment by johnkord** [comment]
Let's also set a specific version for each of the tools that we use and make it a requirement for our contributor environment

**Comment by dragoshsch** [comment]
@johnkord I created #1552 to fix this, and we'll treat the package version pinning in ansible in a separate PR.

**Comment by ionutbalutoiu** [comment]
I opened https://github.com/Microsoft/openenclave/issues/1555 to continue tracking the packages versions pinning in Ansible.
