### ISSUE TITLE
Publish non-SGX simulation mode package

### ISSUE THREAD

**Issue by letmaik** [Microsoft/openenclave#1549]
Currently, there is only one apt package (`open-enclave`) and it [requires](https://github.com/Microsoft/openenclave/blob/master/docs/GettingStartedDocs/install_oe_sdk.md#platform-requirements) SGX hardware. To use OE on non-SGX hardware in simulation mode for testing, I would have to build it from source myself.

If there's nothing that speaks against it, I would like it if a second package `open-enclave-sim` is published that doesn't have SGX dependencies (hardware and Intel libraries). The idea is that the open-enclave and open-enclave-sim packages are exclusive to each other, so cannot be installed at the same time, which can be realized with the `Conflicts` directive.

I think this would be useful for CI scenarios where you don't necessarily have SGX hardware available and don't want to spend the time building OE from scratch. It's also useful for developers that want to test locally on non-SGX hardware and only do final testing on a remote SGX system, again without having to spend time building OE themselves.

**Comment by johnkord** [comment]
Thanks for the suggestion! Currently we don't have this plan, and as long as you need this capability we think there should be a workaround.
