### ISSUE TITLE
Determine and assert the minimum required CMake for the samples

### ISSUE THREAD

**Issue by andschwa** [Microsoft/openenclave#1561]
From #1472, we can probably go quite a bit lower than 3.10 (though most likely not below 3.0). This needs to be tested, and when determined, the samples' minimum CMake updated. We may want to add CI to explicitly test the samples against the oldest supported version, but I only see a modicum of value in doing so.

**Comment by johnkord** [comment]
We're going to set a dependency for Linux systems to use CMake 3.13 like our current CI jobs, which we might lower in a future release to be consistent with Windows at 3.10.

**Comment by andschwa** [comment]
@johnkord this applies to the samples only, which implies the minimum required CMake to to _use_ our SDK. I am going to re-open this bug as do want want to require 3.13 of users of the CMake package, which is what this issue is about.

**Comment by aserdean** [comment]
A successful run was with CMake `3.3`, although:
```
CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.3)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring done
CMake Error:
  Error evaluating generator expression:

    $<COMPILE_LANGUAGE:CXX>

  $<COMPILE_LANGUAGE:...> may only be used to specify include directories
  compile definitions, compile options and to evaluate components of the
  file(GENERATE) command.
```
Which was solved in `3.11`: https://gitlab.kitware.com/cmake/cmake/issues/17811

**Comment by andschwa** [comment]
@aserdean Oh dang! Looks like we're actually pinned to 3.11 due to a CMake bug (I don't see anyway of working around that). Thanks for finding and investigating.

Let's move the samples to minimum 3.11, and probably reference that fact in the readme of the samples too. Thanks so much!

**Comment by aserdean** [comment]
Closed via: https://github.com/Microsoft/openenclave/pull/1570/commits/d1d07b91aaccb7e263bd4654eca788502949a2d7
