### ISSUE TITLE
Find and document library dependencies

### ISSUE THREAD

**Issue by andschwa** [microsoft/openenclave#1563]
The current CMake package per #1472 has only been tested on Linux, and only has one documented dependency (via `find_dependency`, for `Threads`). We need to find and document the rest (notably `dl` and `crypto` for sure, but also anything else using `find_library` or just raw link flags). We then need to require those only on the correct platforms, so that eventually the package _might_ work on Windows too.

**Comment by johnkord** [comment]
@andschwa Do you mean this has only been tested on Linux?

**Comment by andschwa** [comment]
@johnkord the CMake package is only tested on Linux (note: all the samples are only tested on Linux).
