### ISSUE TITLE
Use -fPIE flag for compiling enclaves

### ISSUE THREAD

**Issue by anakrish** [Microsoft/openenclave#1567]
Today, we use -pie flag for linking enclaves and use -fPIC for compiling enclaves.
However GCC [docs ](https://gcc.gnu.org/onlinedocs/gcc/Link-Options.html#Link-Options)state:

**-pie**
_Produce a dynamically linked position independent executable on targets that support it. For predictable results, you must also specify the same set of options used for compilation (-fpie, -fPIE, or model suboptions) when you specify this linker option._

Since we are using a flag combination that GCC does not recommend, we need to fix it or provide a rationale why we use it.

CC: @CodeMonkeyLeet @johnkord @lilyfang @crisl-ms

**Comment by andschwa** [comment]
Related to #1168

**Comment by andschwa** [comment]
@anakrish @mikbras what flag combination _should_ we be using?

**Comment by anakrish** [comment]
According to GCC document linked, we should use -fPIE.
