### ISSUE TITLE
Unused enclave configuration files in samples?

### ISSUE THREAD

**Issue by aserdean** [Microsoft/openenclave#1569]
While working on cmake files for samples I noticed that the files:
https://github.com/Microsoft/openenclave/blob/master/samples/remote_attestation/common/enc.conf
https://github.com/Microsoft/openenclave/blob/master/samples/local_attestation/common/enc.conf

They aren't used by the Makefiles.

I have no idea what the original purpose for them are so I sent a tentative PR to remove them here:
 https://github.com/Microsoft/openenclave/pull/1568.

CC: @andschwa , @johnkord , @soccerGB

**Comment by andschwa** [comment]
Yeah, that's odd. I think it's just tech debt from a prior refactoring. If the conf files are the same for all the enclaves in a sample, it seems to me should just keep the one in `common` and delete the rest. @soccerGB what do you think?

**Comment by johnkord** [comment]
We may want to keep these files around and use them to test oesign in the samples. Let's chat tomorrow at our weekly sync meeting, @aserdean @andschwa

**Comment by andschwa** [comment]
@johnkord I'm not sure I follow. There already is a conf file being used to test signing; these are extra that are (presumably) leftover from a refactoring.

**Comment by ionutbalutoiu** [comment]
Fixed by https://github.com/Microsoft/openenclave/pull/1568
