### ISSUE TITLE
Missing test coverage for testing signed enclaves using oesign tool

### ISSUE THREAD

**Issue by anitagov** [Microsoft/openenclave#1579]
The OESIGN tool gets used or exercised only by samples right now.
We need a test that uses the OESIGN tool to sign an enclave and test it. 

Uncovered this during my PR #1540 when I modified properties and had added XFRM to signing and the issue was not caught by any test but samples.

**Comment by johnkord** [comment]
@anitagov What is missing here? There are several tests (that aren't samples) that use the oesign tool. For example, the properties test runs both unsigned/signed tests.

**Comment by anitagov** [comment]
Verified that tests props and debug-mode both invoke the oesign tool for signing enclaves. The ENCLAVE_CONFIG setting gets enabled for these tests as this parameter is specified in the enc/CMakeLists.txt.

add_enclave(TARGET props_enc **CONFIG sign.conf** SOURCES enc.c props.c ${gen})

Verified that the key was generated at run time and the tool oesign invoked to build the target(s).

Closing this.
