### ISSUE TITLE
oe-gdb: oe-gdb script needs to be relocatable to any OE install location

### ISSUE THREAD

**Issue by anakrish** [Microsoft/openenclave#1582]
Currently the oe-gdb script is generated via a configure_file command that uses the installation directory specified during cmake-configure time.
cmake -DCMAKE_INSTALL_PREFIX=foo

However  installation can also be done via the following syntax:
make install DESTDIR=bar

The above install would not work since the oe-gdb script has been configured to work at foo.

**Comment by anakrish** [comment]
CC: @andschwa @CodeMonkeyLeet @johnkord

**Comment by andschwa** [comment]
Resolved by #1591.
