### ISSUE TITLE
Clarify how to enable/disable simulation

### ISSUE THREAD

**Issue by andschwa** [Microsoft/openenclave#1587]
From #1570 we bumped making the use of `OE_SIMULATION` clearer. It makes some the samples a bit confusing. As we don't yet know the future of simulation mode, we're punting this for now.

**Comment by johnkord** [comment]
We understand that more work needs to be done on simulation mode, but we should clarify our documentation that this is solely for testing purposes and some features may not work when using simulation mode.

**Comment by andschwa** [comment]
@johnkord Can you file a separate issue for documentation? This issue is about a particular quirk in the sample builds, and is a backlog item.

**Comment by anakrish** [comment]
@john this is the doc task for simulation. We need to update GettingStartedDocs/SimulatorGettingStarted.md with the disclaimer about simulation mode.

**Comment by johnkord** [comment]
Closing this as resolved with #1647

**Comment by andschwa** [comment]
Also with #1662 for the other issue here 😆
