### ISSUE TITLE
Fix naming of enclaves in samples

### ISSUE THREAD

**Issue by andschwa** [Microsoft/openenclave#1588]
Noticed in #1570. Our samples inconsistently use `enc1` for folders, and `enclave_a` for names; this was due to "key A" and "key B" being used in the original documentation, but now it's confusing.

We should both rename the folders from `enc1` to `enclave1` and the targets from `enclave_a` to `enclave1`.

**Comment by andschwa** [comment]
(And just `enc` folders to `enclave`.)

**Comment by aserdean** [comment]
`A` and `B` sounds better than `1` and `2` IMO.
