### ISSUE TITLE
Add DEPENDS file.edl to samples

### ISSUE THREAD

**Issue by andschwa** [Microsoft/openenclave#1594]
In the [custom command in the samples](https://github.com/Microsoft/openenclave/blob/10e48844c1de3842d4f3180602e4d0a5d5379c0f/samples/data-sealing/common/CMakeLists.txt#L6) we need to ensure there is a `DEPENDS file.edl` so that the build rebuilds if the EDL file changes. This is not implicit from [`add_custom_command`](https://cmake.org/cmake/help/latest/command/add_custom_command.html?highlight=add_custom_command). For example:

```c
add_custom_command(OUTPUT datasealing_t.h datasealing_t.c
  DEPENDS ${CMAKE_SOURCE_DIR}/datasealing.edl
  COMMAND openenclave::oeedger8r --trusted ${CMAKE_SOURCE_DIR}/datasealing.edl)
```

**Comment by andschwa** [comment]
Thanks @paulcallen for catching this.

**Comment by anakrish** [comment]
A similar issue also exists for all the EDL files for tests.
If any of the test edl files are changed, oeedger is not re-triggered when doing a make.

**Comment by aserdean** [comment]
I think this needs to go in the Makefiles as well.

**Comment by aserdean** [comment]
The CMake part is done via: https://github.com/Microsoft/openenclave/pull/1570/commits/9f2c8811abc7fb9ed084b463de37fde8242e75f1

Should we leave this open for Makefiles or should we open a different issue?

**Comment by andschwa** [comment]
@aserdean different issue for the Makefiles as we want to completely vet them for sample-quality in #1562, so I'll close this issue as resolved. Thanks!
