### ISSUE TITLE
Need a cmake openenclave::oe-gdb SDK target

### ISSUE THREAD

**Issue by paulcallen** [Microsoft/openenclave#1599]
To sign an enclave within cmake you can use openenclave::oesign for the binary name and it will pull it from the SDK bin directory.
To add a custom target to run you generally need to have a custom command to run `host/host enc/enclave`. No special SDK target is needed here.
However we should be able to add a custom target so I can debug. This way I should be able to add a custom target `debug` which calls openenclave::oe-gdb, but this does not exist.
The reason the lack of this became problematic for me is that I need to run the host as sudo and that loses the path so it cannot find it so I had to jump through hoops to get the path before I call sudo,
Adding an openenclave::oe-gdb would make this easier.

**Comment by andschwa** [comment]
Sure, you can do that pretty easily. Just add a new `install` command so it gets exported. There's lots of examples in the CMake files.

**Comment by andschwa** [comment]
That `install` command should look like [this](https://github.com/Microsoft/openenclave/blob/42b852736142a7ac0933d69793a81f912a41490d/tools/oesign/CMakeLists.txt#L12).
