### ISSUE TITLE
Host Windows enclave/exit assembly code needs to handle Spectre mitigation

### ISSUE THREAD

**Issue by anitagov** [Microsoft/openenclave#1601]
The host Windows enclave/exit assembly code needs to handle Spectre mitigation, similar to the Linux Windows enclave/exit assembly.

**Comment by CodeMonkeyLeet** [comment]
@anitagov Isn't this a dupe of #1557?

**Comment by anitagov** [comment]
yes - forgot that I had filed it already. Closing this as duplicate of #1557
