### ISSUE TITLE
oesign dump expects enclave to have  _enc in its name

### ISSUE THREAD

**Issue by radhikaj** [Microsoft/openenclave#1612]
Looking at this code and running 
oesign dump helloworldenc->just prints out usage information 
oesign dump heloworld_enc ->works as expected. 
From looking at the code oesign expects the enclave image to be named *_enc*.

https://github.com/Microsoft/openenclave/blob/42b852736142a7ac0933d69793a81f912a41490d/tools/oesign/main.c#L646

**Comment by ionutbalutoiu** [comment]
Hello @radhikaj! This is being taken care of as part of the PR https://github.com/Microsoft/openenclave/pull/1602 where the `oesign` CLI to arguments parsing is revamped.
