### ISSUE TITLE
Remove special case around `void fn()` and `example_args.h` header

### ISSUE THREAD

**Issue by andschwa** [Microsoft/openenclave#1627]
There's an edge case where an arguments header will not be generated if the only EDL functions are of the form `void fn()`. This is bad, let's just generate an empty header so that we gurantee a header is always generated.

**Comment by johnkord** [comment]
Let's ensure that the other generated headers don't #include example_args.h in this case, since that file won't exist. It's a better solution than generating an empty example_args.h file.

**Comment by anakrish** [comment]
I don't see any code that explicitly does this check.
I just now tried out with the following edl:
enclave {
  trusted {
    public void foo();
  };
};

This generates the _args.h as expected.

**Comment by andschwa** [comment]
Sorry, this bug was really filed by @paulcallen, I haven't confirmed it.

**Comment by andschwa** [comment]
@paulcallen I'm assigning you just to confirm this. If you have a repro, please post it, otherwise it looks like we can close this.

**Comment by paulcallen** [comment]
huh! I am confused also. I was sure the information was correct, although do not recall where that information came for. Thanks @anakrish for validating. 
Lets close it!
