### ISSUE TITLE
OE SDK Enhanced Logging Feature needs to be documented

### ISSUE THREAD

**Issue by anitagov** [microsoft/openenclave#1660]
The OE SDK enhanced Logging feature is documented in issue #1118 . It needs to be available as a document for SDK users to reference.

**Comment by johnkord** [comment]
OE SDK Enhanced logging today is an internal feature. The only thing that needs to be documented is how to turn on the OE SDK logs at their different levels. This is not something the public can expand upon yet.

**Comment by soccerGB** [comment]
Agreed with John
