### ISSUE TITLE
Enforce integrity of secure channel after remote attestation

### ISSUE THREAD

**Issue by AjayBrahmakshatriya** [microsoft/openenclave#1707]
The remote_attestation sample implements a "proprietary" secure channel (as mentioned in #1325). The algorithm exchanges public keys for both the enclaves and uses these public keys to encrypt the messages to each other. 
But the public keys are visible to the external world including the host. This compromises the integrity of the messages sent over the channel. The host can fake messages on behalf of the enclaves. 

As a fix, the enclaves should use the established ephemeral private keys to perform a signed Diffie-Hellman key exchange and use symmetric key cryptography to communicate after that point. This will also improve the communication overhead. 

Diffie-Hellman key exchange would be the ideal implementation. But an alternate implementation could just generate an ephemeral symmetric key in one of the enclave, sign it with its own private key and then encrypt it with the public key of the other enclave to be sent to the other enclave. This will ensure that the symmetric key is known only to the two enclaves and the root of trust is in the remote attestation.

**Comment by soccerGB** [comment]
Ajay, thanks for pointing out this issue. 
What you pointed out is correct that the channel established in the existing remote attestation sample is susceptible to fake messages originated by any untrusted hosts that have access to the public key.
Given the attested tls feature (#1325) is coming in a couple weeks, what I am going to do is to update the remote attestation to limit it to mutual attestation and point out additional session exchange logics (such as Diffie-Hellman algorithm) in order to establish a really "secure" channel, instead of adding session exchange logics there, which will be soon replaced by the Attested TLS feature.
Let me know what you think

**Comment by AjayBrahmakshatriya** [comment]
Hi Cheng,
When you say point out additional session exchange logics do you mean you would add instructions to the README? Also does this mean you will remove the `ecall_dispatcher::generate_encrypted_message` function and the corresponding `ecall_dispatcher::process_encrypted_msg` function from the sample?
I agree, Attested TLS would solve this completely. Looking forward to that feature.
Thanks

**Comment by anitagov** [comment]
@soccerGB - Can you please clarify if you want to go ahead with the plan of action that you mentioned here.

**Comment by CodeMonkeyLeet** [comment]
Reassigned to @anitagov to implement the reduced scope fix

**Comment by anitagov** [comment]
My PR #1944 addresses this and modifies the remote attestation to remove claims of having a secure channel. The additional session exchange routines after mutual attestation has been completed have been removed. 

There will be other issues/PRs for samples with TLS, etc.
Closing t his as #1944 has been merged to master.

**Comment by soccerGB** [comment]
@AjayBrahmakshatriya 
Thanks for your great feedback.

Based on your feedback, we updated the remote attestation sample to make it focus only on demonstrating how to conduct remote attestation itself by removing the "secure channel" part of implementation and documentation.  We will have separate sample the need for A future separate sample will have proprietary 

And the Attested TLS channel feature (tracked by https://github.com/openenclave/openenclave/issues/1325) has been merged into the master branch. You can find SDK samples in https://github.com/openenclave/openenclave/blob/master/samples/attested_tls/README.md

Any feedback will be great appreciated.
