### ISSUE TITLE
The ansible playbook to install OE on ACC hardware fails in 0.5.0

### ISSUE THREAD

**Issue by achamayou** [Microsoft/openenclave#1712]
From https://github.com/Microsoft/openenclave/tree/master/scripts/ansible

Open Enclave environment for contributors using ACC hardware:

ansible-playbook oe-contributors-acc-setup.yml

Fails with:

    "msg": "Request failed",
    "response": "HTTP Error 404: Not Found",
    "state": "absent",
    "status_code": 404,
    "url": "https://download.01.org/intel-sgx/dcap-1.1/linux/dcap_installers/ubuntuServer18.04/sgx_linux_x64_driver_dcap_3c2bd37.bin"

I see that this has been addressed in master, but for projects that target a release of OpenEnclave, it'd be good to have a fix for this in a release (0.5.1?).

**Comment by johnkord** [comment]
Thanks @achamayou we'll update this. We might also want to consider whether we should be referencing cached CDN endpoints for these Ansible playbooks.

**Comment by achamayou** [comment]
Yes, if the links aren’t stable enough, it may be necessary to consider that. Thank you for the quick response.

**Comment by johnkord** [comment]
Fixed by #1718

**Comment by letmaik** [comment]
Why is there no 0.5.1 patch release for this yet? It's been two weeks already :-)

**Comment by johnkord** [comment]
@letmaik I think because we've only modified documentation and an ansible task, neither of which goes into the SDK package, we didn't plan on making a new 0.5.1 release.

**Comment by achamayou** [comment]
@johnkord if a user downloads the latest release and tries to follow the instructions for contributors, they're going to hit this bug though. Should the release notes and/or the documentation at least mention this?

**Comment by johnkord** [comment]
@letmaik @achamayou I will bring this up today with the team! I now understand what you mean by "latest release": the archive (.tar.gz) of the repo, as opposed to the .deb SDK package

**Comment by achamayou** [comment]
Yes, sorry, I wasn’t clear. A contributing user (or one that needs a custom build) would get the tarball with the source rather than the .deb.
