### ISSUE TITLE
Missing compiler-rt: __popcountdi2 

### ISSUE THREAD

**Issue by Lusitanian** [microsoft/openenclave#1729]
We've recently incorporated a library into our enclave build that relies on the ANTLR4 C++ runtime. It appears that some of their code which uses `std::bitset` ends up relying on an intrinsic that OE doesn't provide: 

```
../external/install/lib/libauthz_oe.a(ParserATNSimulator.cpp.o): In function `antlr4::atn::ParserATNSimulator::execATN(antlr4::dfa::DFA&, antlr4::dfa::DFAState*, antlr4::TokenStream*, unsigned long, antlr4::ParserRuleContext*)':
ParserATNSimulator.cpp:(.text+0x1fb8): undefined reference to `__popcountdi2'
ParserATNSimulator.cpp:(.text+0x1fc7): undefined reference to `__popcountdi2'
ParserATNSimulator.cpp:(.text+0x1fd8): undefined reference to `__popcountdi2'
ParserATNSimulator.cpp:(.text+0x1fe9): undefined reference to `__popcountdi2'
ParserATNSimulator.cpp:(.text+0x1ffa): undefined reference to `__popcountdi2'
../external/install/lib/libauthz_oe.a(ParserATNSimulator.cpp.o):ParserATNSimulator.cpp:(.text+0x200b): more undefined references to `__popcountdi2' follow
```

I've worked around this for now by using the implementation from here  https://raw.githubusercontent.com/intel/linux-sgx/master/sdk/compiler-rt/popcountdi2.c

**Comment by letmaik** [comment]
It's not an intrinsic, but yes, OE needs compiler-rt to avoid these issues.

Previously mentioned in https://github.com/Microsoft/openenclave/pull/531#issuecomment-415430684 and https://github.com/Microsoft/openenclave/pull/603#issue-211443232 (August 2018).

**Comment by johnkord** [comment]
Is it possible to turn off intrinsics for this particular module? @Lusitanian

**Comment by Lusitanian** [comment]
@letmaik ahh, you're right, important clarification. thank you!

@johnkord I don't think so  - I believe these calls are actually inserted by the compiler. @letmaik clarified the underlying issue above and is more knowledgeable on this than me

**Comment by CodeMonkeyLeet** [comment]
To summarize, we don't pull in the compiler runtime library as part of the base OE SDK link dependencies, which surfaces as the set of missing intrinsics/compiler functions observed when moving between GCC and Clang, or inclusion of libraries that already depend on them. 

We're not going to fix this as a one off, and specifically we haven't really explored the extent of support for custom C++ runtimes, so I've added #1766 to track the discussion in this space for future, but we won't be addressing this right now.

FYI @anakrish who was looking at issues related to our factoring of libunwind and MUSL runtimes.
