### ISSUE TITLE
Install ocamlformat on CI

### ISSUE THREAD

**Issue by andschwa** [microsoft/openenclave#1738]
Per #1737, I'd like to get [ocamlformat](https://github.com/ocaml-ppx/ocamlformat) installed on the CI machines so we can add it to the `format-code` script. This probably means installing `opam` and then running `opam install ocamlformat` in the Ansible scripts.

**Comment by ionutbalutoiu** [comment]
Assigned this to [george-caluta](https://github.com/george-caluta).

**Comment by ionutbalutoiu** [comment]
@andschwa I just merged https://github.com/microsoft/openenclave/pull/1778 to have `ocamlformat` installed as part of the Ansible setup.

And I run this on our Jenkins CI machines. All of them should have `ocamlformat` available.
