### ISSUE TITLE
Incorrect example

### ISSUE THREAD

**Issue by letmaik** [Microsoft/openenclave#1739]
https://github.com/Microsoft/openenclave/blob/master/docs/GettingStartedDocs/Edger8rGettingStarted.md

Below "Within the host we would do the following:" it says:
```c++
void main(void)
{
    //enclave initialization goes here

    oe_result_t result;
    char* out_string = NULL;
    result = call_one(enclave, &out_string);
    if (result == OE_OK)
    {
        // We now have a string in out_string

        // When we are done we need to free it
        oe_host_free(out_string);
    }
}
```

But oe_host_free is only available inside enclave. Should this be free(out_string)?

**Comment by anakrish** [comment]
@soccerGB @shruti25ratnam This is a nice ramp up task to get into the SDK codebase.

**Comment by johnkord** [comment]
@anakrish @shruti25ratnam I agree! Shruti, would you be willing to pick this up?

**Comment by shruti25ratnam** [comment]
Sure, it should be free(out_string) inside the main function. I will fix this. Thank you!
