### ISSUE TITLE
Update Get Started doc with the automated process

### ISSUE THREAD

**Issue by jxyang** [Microsoft/openenclave#1743]
It seems we have automated with Ansible the installation of prerequisites, e.g., Intel and Microsoft APT Repositories, Intel SGX and DCAP drivers. But the following pages are still referring to the old process of installing required packages individually:

https://github.com/Microsoft/openenclave/blob/master/docs/GettingStartedDocs/install_oe_sdk-Ubuntu_16.04.md
https://github.com/Microsoft/openenclave/blob/master/docs/GettingStartedDocs/install_oe_sdk-Ubuntu_18.04.md

**Comment by achamayou** [comment]
It's also unfortunate that the playbooks included in the latest release (0.5.0) do not work because of a URL change (#1718). It would be really good to have a 0.5.1 with that change.

**Comment by jxyang** [comment]
I learned the behavior is intended. The SDK users who don't want to hack openenclave need not to pull in all the required packages, thus a package-by-package installation process is still OK. We need to document the rational though.

**Comment by johnkord** [comment]
@jxyang Sounds good. Would you like to add some documentation to describe the rationale for this? :)

**Comment by jxyang** [comment]
@johnkord Sure.
