### ISSUE TITLE
Need to disable simulation mode on Windows

### ISSUE THREAD

**Issue by mikbras** [microsoft/openenclave#1753]
We need to disable simulation mode Windows because it crashes sporadically. Linux uses the FS register for pthreads and leaves the GS register unused. Simulation mode on Linux takes over the GS register. But Windows uses the FS and GS register and these are corrupted when calling into the enclave in simulation mode.

Suggestion: oe_create_enclave() should fail on Windows whit the simulation mode flag.

**Comment by anakrish** [comment]
@jxyang This is a nice first task for you.
CC @aserdean @shruti25ratnam in case you want to take this on.

**Comment by jxyang** [comment]
@anakrish Sure I will take a look.
