### ISSUE TITLE
oeedger8r: Tests for propagate_errno

### ISSUE THREAD

**Issue by anakrish** [microsoft/openenclave#1775]
The following scenarios would need to be locked down:

1) Correct propagation of errno in presence of multiple threads:
host/enclave transition involves binding a host thread to and enclave thread and also thread-local storage. If any of these malfunction, errno values will not be reliable.
Note: We don't support reentrant ecalls. Supporting reentrant ecalls in the form of 'private ecalls' would lead to some interesting scenarios to consider.

2) Error is currently propagated from the host to the enclave, **only** during an ocall. This leads to the question, what should the initial value of errno be for an enclave thread. Should it be 0 or should it be the errno value of the host prior to making the outermost ecall for a given host thread

3) When an outermost ecall returns, the enclave thread essentially terminates. If the host were to call back into the enclave, the same enclave thread could get reused. The old value of errno should not incorrectly persist within the enclave.

4) Does errno work with synchronous switchless calls?

CC: @mikbras

**Comment by mikbras** [comment]
Good question Anand. In the POSIX extensions work, we clear the errno in the OCALL as our first step. For example:

```
oe_host_fd_t oe_posix_open_ocall(
    const char* pathname,
    int flags,
    oe_mode_t mode)
{
    errno = 0;

    return open(pathname, flags, mode);
}
```

Otherwise, the enclave will receive some garbage value left over from before.

**Comment by mikbras** [comment]
Note that clearing **errno** is not strictly necessary since **errno** is only examined when there is an error (when some function returns an error indication).

**Comment by mikbras** [comment]
Background for readers of this issue on the implementation of **errno**. Typically **errno** is defined something like this:

```
int* __errno_location(void);
#define errno *__errno_location()
```
A typical implementation of **___erno_location()**:

```
static __thread int _errno = 0;

int* __errno_location(void)
{
    return &_errno;
}
```

**Comment by yakman2020** [comment]
@andschwa @anakrish  has this been satisfied?

**Comment by andschwa** [comment]
@anakrish Is this where you want it to be with #1779? If not, please re-open.
