### ISSUE TITLE
Support TTY operations for console devices

### ISSUE THREAD

**Issue by mikbras** [microsoft/openenclave#1808]
The console file system (**./posix/consolefs.c**) implements the **stdin**, **stdout**, and **stderr** devices. Since it opens devices by name (**/dev/stdin**, **/dev/stdout**, and **/dev/stderr**), TTY-related **ioctl** requests fail when delegated to the host because they do not identify as TTY-devices.

MUSL checks whether file descriptors refer to TTY devices when writing to **stdout** and **stderr**. It uses the **ioctl** **TIOCGWINSZ** request to determine whether to use line-buffered I/O and if this fails, writes to certain standard devices fail.

To work around his, **./posix/consolefs.c** implements **TIOCGWINSZ** on the enclave side.

This problem can be resolved in two ways: (1) figure out how to mark host-side descriptors as TTY devices (research pty devices) or (2) implement the TIO ioctl request on the enclave side.

An extreme test to this feature would be to see if **curses** functions work through a console, although

**Comment by johnkord** [comment]
Closing this issue as per our triage discussion
