### ISSUE TITLE
Clarify/Evaluate role of corelibc and MUSL: DO NOT EDIT!!!

### ISSUE THREAD

**Issue by anakrish** [microsoft/openenclave#1831]
### What is LIBC ?

For this discussion, libc is defined as an implementation of a C library as seen in various Linux, Unix, Android, OS-X platforms. 

A libc provides the following functionality
- **fully compatible implementation of ISO C standards** (89/99 etc)
- **mostly compatible implementation of POSIX standards**
- **OS specific functionality and extensions**

libc does not require that there exist a single binary/library that contains the entire implementations.For example posix threads exist in a separate library pthreads.

For OE, we are dealing with a subset of libc functionality since not all functionality makes sense in an enclave and not all functionality is immediately relevant.

Some popular OS (e.g Mac OS X) are posix certified, whereas other popular OSes (**Linux**, Android) are **mostly POSIX compliant**. What this means is that the libc for these mostly POSIX compliant platforms are heavily based on POSIX, but may have known and important differences from POSIX.

### System Call ABI

The mostly POSIX like functionality implemented by Linux and its derivatives are called [system calls](http://man7.org/linux/man-pages/man2/syscalls.2.html).

Often each kernel syscall function (e.g. _Sys_open_) provides an almost compatible implementation of a POSIX function (e.g. _open_) and is wrapped by the user space GLIBC function that has the POSIX name (e.g. _open_).

The behavior of a Linux system call can be obtained via _man 2_:
```bash
$ man 2 open | less
OPEN(2)                                                                          Linux Programmer's Manual                                                                         OPEN(2)

NAME
       open, openat, creat - open and possibly create a file

...
DESCRIPTION
       The open() system call opens the file specified by pathname.  If the specified file does not exist, it may optionally (if O_CREAT is specified in flags) be created by open().
```

The POSIX behavior for the same function can be looked up via an online reference [http://pubs.opengroup.org/onlinepubs/9699919799/](http://pubs.opengroup.org/onlinepubs/9699919799/)

### syscall instruction
Various processors provide instructions to transfer control to and invoke functions in the kernel.
In x64, this is the [_syscall_](https://www.felixcloutier.com/x86/syscall) instruction, in ARM64 it is the _svc #0_ instruction.

[http://man7.org/linux/man-pages/man2/syscall.2.html](http://man7.org/linux/man-pages/man2/syscall.2.html) lists the "syscall" instructions used on various processors.

The syscall instruction in various processors invokes a OS handler that implements a specific (mostly) posix functionality at kernel privilege. The instruction also provides various guarantees about registers, flags e.t.c.

For example, the syscall instruction on x64 provides the following behavior and guarantees:
> SYSCALL invokes an OS system-call handler at privilege level 0. It does so by loading RIP from the IA32_LSTAR MSR (after saving the address of the instruction following SYSCALL into RCX). (The WRMSR instruction ensures that the IA32_LSTAR MSR always contain a canonical address.) SYSCALL also saves RFLAGS into R11 and then masks RFLAGS using the IA32_FMASK MSR (MSR address C0000084H); specifically, the processor clears in RFLAGS every bit corresponding to a bit that is set in the IA32_FMASK MSR.

### LIBC syscall function

The syscall instruction is generally wrapped by the platform's LIBC via a [syscall function/intrinsic](http://man7.org/linux/man-pages/man2/syscalls.2.html).

```c
       #define _GNU_SOURCE         /* See feature_test_macros(7) */
       #include <unistd.h>
       #include <sys/syscall.h>   /* For SYS_xxx definitions */

       long syscall(long number, ...);
```

The syscall function itself provides various guarantees:
>syscall() saves CPU registers before making the system call, restores
       the registers upon return from the system call, and stores any error
       code returned by the system call in errno(3) if an error occurs.

### LIBC POSIX functions

LIBC generally provides thin wrappers of the kernel system calls by using the LIBC system call function.

[http://man7.org/linux/man-pages/man2/syscalls.2.html](http://man7.org/linux/man-pages/man2/syscalls.2.html)
> Often the glibc wrapper function is quite thin, doing little work
       other than copying arguments to the right registers before invoking
       the system call, and then setting errno appropriately after the
       system call has returned.

There are also exceptions where the LIBC function is more than a thin wrapper
> Sometimes, however, the wrapper function does some extra work before
       invoking the system call.  For example, nowadays there are (for
       reasons described below) two related system calls, truncate(2) and
       truncate64(2), and the glibc truncate() wrapper function checks which
       of those system calls are provided by the kernel and determines which
       should be employed.

or cases where the LIBC function does not call the corresponding system call
```bash
$ man 2 signal | grep sigaction
By default, in glibc 2 and later, the signal() wrapper function does not invoke the kernel system call.  Instead, it calls sigaction(2) using flags that  supply  BSD  semantics
```

### Call chain for LIBC functions

In general calling a LIBC function (mostly posix) leads to the following chain of call:
`LIBC open  ->  LIBC syscall function  -> processor syscall instruction  -> kernel Sys_open system call`

Note that the kernel syscall implementations are guarded by both the syscall instruction as well as the LIBC syscall function, both of which provide register preservation and other guarantees across the user space to kernel transfer of control.

### What is MUSL?
From [MUSL faq](https://www.musl-libc.org/faq.html)
> musl is a “libc”, an implementation of the standard library functionality described in the ISO C and POSIX standards, plus common extensions, intended for use on Linux-based systems.
... musl is a new general-purpose implementation of the C library. It is lightweight, fast, simple, free, and aims to be correct in the sense of standards-conformance and safety. 

For our purpose, MUSL is a replacement of Linux GLIBC. However it may not be 100% behaviorally equivalent of GLIBC. Additionally MUSL claims to be _lightweight, fast, simple, free, and aims to be correct in the sense of standards-conformance and safety_.

Using MUSL would lead to the following call chain where MUSL becomes the LIBC:
`MUSL open  ->  LIBC syscall function  -> processor syscall instruction  -> kernel Sys_open system call`

### Enclave syscall function hook/

Since syscall instruction is not supported within SGX enclaves, OE provides an implementation of the LIBC syscall function that instead of executing the syscall instruction, dispatches to the OE syscall implementations

https://github.com/microsoft/openenclave/blob/eac946aaec2a71e7d48283bd025ee84aed10f9f5/posix/syscall.c#L37-L54

and

https://github.com/microsoft/openenclave/blob/eac946aaec2a71e7d48283bd025ee84aed10f9f5/libc/sgx/syscalls.c#L226-L251

**Note: Currently the OE syscall function does not provide the same guarantees (e.g register save restore as described by http://man7.org/linux/man-pages/man2/syscall.2.html**

**Comment by dthaler** [comment]
Be careful to not assume that the term "syscall" means Linux.  Other OS's use the same term as well, so it would be incorrect to use the term "syscall" by itself in a way that is Linux-specific.  It's safer to say "Linux syscall" if you mean Linux specific behavior.

**Comment by anakrish** [comment]
@dthaler Good point. Will rephrase. Am capturing my thoughts/understanding for now in this issue.

Can you point me to TrustZone documentation? I would like to know what kind of library functions the enclave has access to - is it POSIX or some custom flavor of LIBC.

**Comment by dthaler** [comment]
Your question is really about OP-TEE not TrustZone per se.  https://wiki.linaro.org/WorkingGroups/Security/OP-TEE#What_API.27s_has_been_implemented_in_OP-TEE.3F and https://optee.readthedocs.io/ explain that it implements the GlobalPlatform (not POSIX) APIs.  That said, OP-TEE also includes native support for a limited number of POSIX APIs which you can see in the headers in this directory: https://github.com/ms-iot/optee_os/tree/ms-iot/lib/libutils/isoc/include

**Comment by anakrish** [comment]
@Thanks! Very useful.

**Comment by anakrish** [comment]
@dthaler Thanks! Very useful.
