### ISSUE TITLE
oe_verify_report fails with OE_VERIFY_CRL_EXPIRED

### ISSUE THREAD

**Issue by jumaffre** [microsoft/openenclave#1842]
CCF's quote verification started failing this morning (UK) with the following error:

```
10:26:26:751624 tid(0x7f48f5a6f740) (H)[ERROR]enforcing CRL (oe_result_t=(null))[OE_VERIFY_CRL_EXPIRED ../common/sgx/quote.c:5139712]
```

A similar behaviour is reproducible by running v0.5.0 OE's `tests/report`:

```
171: 10:27:34:359257 tid(0x7fcdeb9f90c0) (H)[ERROR]X509_verify_cert failed!
171:  error: (12) CRL has expired
171:  (oe_result_t=OE_VERIFY_CRL_EXPIRED)[../host/crypto/openssl/cert.c oe_cert_verify:721]
171: 10:27:34:359264 tid(0x7fcdeb9f90c0) (H)[ERROR]oe_cer_veTest failed: ../tests/report/common/tests.cpp(1055): test_remote_verify_report VerifyReport(report_buffer, report_size, NULL) == OE_OK
```

Note that the current date on the machine is `Thu May 30 10:28:33 GMT 2019`. However, when moving the time back to `Thu May 30 10:22:00 GMT 2019`, the tests (both CCF and OE) complete successfully. The threshold appears to be at `10:23:00 GMT`. 

There is nothing obvious from the quote certificate chain CRL (`Next Update` field for both PCK CRL and IntelSGXRootCA) that would make us think that [this flag](https://github.com/microsoft/openenclave/blob/1922dfbfc37c2d78361e662de45cd313af12f486/enclave/crypto/cert.c#L344) is set.

All of our CI and local builds are failing right now due to this. Feel free to let us know if you need additional detail on this.

**Comment by achamayou** [comment]
In case it helps, this is the driver we run:

$ /sbin/modinfo intel_sgx
filename:       /lib/modules/4.18.0-1014-azure/updates/dkms/intel_sgx.ko
license:        Dual BSD/GPL
author:         Jarkko Sakkinen <jarkko.sakkinen@linux.intel.com>
description:    Intel SGX Driver
srcversion:     18FB1A7E2798C015F3ABBAB
alias:          acpi*:INT0E0C:*
depends:
retpoline:      Y
name:           intel_sgx
vermagic:       4.18.0-1014-azure SMP mod_unload
signat:         PKCS#7
signer:
sig_key:
sig_hashalgo:   md4

And we believe the az-dcap-client is up to date:

$ sudo apt install az-dcap-client
Reading package lists... Done
Building dependency tree
Reading state information... Done
az-dcap-client is already the newest version (1.0).
0 upgraded, 0 newly installed, 0 to remove and 47 not upgraded.

**Comment by soccerGB** [comment]
This issue turned out to be a result of the fact that "sgx pck processor ca CRL" fetched from the caching service expired. We are working on a solution for it.

**Comment by achamayou** [comment]
@soccerGB is there something that can/should be done to avoid that in the future? Like make the request with Cache-Control: no-cache?
