### ISSUE TITLE
[CI/CD] Add a global timeout for the CI pipeline runs

### ISSUE THREAD

**Issue by ionutbalutoiu** [microsoft/openenclave#1845]
Recently, we had some hanging stages for Bors that blocked the CI. This needed a manual abort in order to unblock the CI.

We should have a global timeout (let's say 4 hours) after which we should terminate every hanging stage (if present).

**Comment by CodeMonkeyLeet** [comment]
@mikbras also inquired as to whether we can add a specific timeout on a per test basis.

**Comment by vlaza** [comment]
@CodeMonkeyLeet are you referring to _ctest_ in this particular case? There is a flag that can do that _--timeout <seconds>_

**Comment by ionutbalutoiu** [comment]
@CodeMonkeyLeet @mikbras 

The global timeout described here will be a value applied for each CI stage (the stages are executed in parallel).

I think that using a `ctest` parameter, we can add a specific timeout per test bases as well (as suggested by @vlaza). Would a timeout of `5 minutes` per test would work here ? What do you think ?

**Comment by aserdean** [comment]
@ionutbalutoiu I would make it 8 minutes to be sure the tests/samples complete. 5 minutes if the system is under load might be too less.

I would add to the ctest command the following argument ``--timeout 480`` (the input is in seconds).
