### ISSUE TITLE
Running data-sealing and attestation samples fails on Simulation Mode

### ISSUE THREAD

**Issue by ShivKushwah** [microsoft/openenclave#1851]
Hi,
I'm running OpenEnclave on a Ubuntu 18.04 VM and am successfully able to run the helloworld and file-encryptor samples using simulation mode (make simulate). However, I noticed that the data-sealing, local_attestation, and remote_attestation samples don't have simulation natively supported in the Makefile. As a result, I tried manually running the enclave in simulation mode by adding the flag  OE_ENCLAVE_FLAG_SIMULATE in the create_enclave method of the host.cpp file in the host directory of these samples. Specifically, I modify the oe_create method as below

` oe_result_t result = oe_create_datasealing_enclave(
        enclavePath,
        OE_ENCLAVE_TYPE_SGX,
        OE_ENCLAVE_FLAG_DEBUG|OE_ENCLAVE_FLAG_SIMULATE,
        NULL,
        0,
        &enclave);`

Now, the sample is able to successfully create an enclave, but it fails at a later step. I am unable to figure out why. Is there anything else I need to add to make the sample files run in simulation mode? For the data-sealing sample, the error I receive is below :
<img width="1080" alt="Screen Shot 2019-06-02 at 12 09 02 PM" src="https://user-images.githubusercontent.com/13080000/58766062-3de6be00-852f-11e9-93d0-dcc92828ba57.png">

**Comment by anakrish** [comment]
@ShivKushwah Data-sealing and attestation rely on special SGX instructions that generate the cryptographic sealing-key and report respectively. Hence these samples won't work in simulation mode.

Do you have access to a machine/VM with SGX support?

CC: @soccerGB

**Comment by ShivKushwah** [comment]
Hi, thanks for the quick response!
I don't currently have access to a machine/VM with SGX support, but I noticed that there are options online. Do you recommend anything in particular?

Also, do you have any experience using Scone? https://sconedocs.github.io/firstcontainer/
I noticed it has native SGX support.

Finally, one last thing, I was able to run the attestation and sealing examples provided in the Intel SGX SDK in simulation mode. Is there any reason why simulation mode works there and not in OpenEnclave?

Thanks!

**Comment by soccerGB** [comment]
Sorry for not being more clear about the fact that those three samples do not support under simulation mode.

The OE SDK's simulation mode support is kind of limited, which does not cover data-sealing or any report related operations. 

With the available of SGX-enabled CPUs coming up the market, we are finding less justification to invest in the simulation mode, we would like to hear any useful scenarios that could help us justify future investment on this.

**Comment by ShivKushwah** [comment]
Thanks for the information!
