### ISSUE TITLE
oe_once/pthread_once is not reentrant in an enclave.

### ISSUE THREAD

**Issue by mikbras** [microsoft/openenclave#1906]
The oe_once() function is not reentrant. That is, if the function called by oe_once() calls oe_once() it hangs waiting on the spinlock. One solution is to use mutexes (which are recursive in OE). Another solution is to implement recursive spinlocks.

OpenSSL uses nested once functions, so this is a high-priority bug.

**Comment by anakrish** [comment]
@mikbras, @johnkord and I prototyped a solution for this a long time ago: #1871. Can you take a look?

**Comment by johnkord** [comment]
This was fixed by #1871 
Thank you everyone for your help! That thread is very insightful by the way.
