### ISSUE TITLE
oe_mount has an access violation when fed an invalid file system name

### ISSUE THREAD

**Issue by radhikaj** [microsoft/openenclave#1919]
In oe_mount mount_point_t is not initialized. 
If line 142 fails  "device = oe_device_table_find(filesystemtype, OE_DEVICE_TYPE_FILE_SYSTEM); "
then we go to done:
    if (mount_point.path)
        oe_free(mount_point.path);

But since mount_point.path was not initialized to null, it has an access violation.

**Comment by anitagov** [comment]
Good find Radhika
