### ISSUE TITLE
Consider prefixing OE libmbedtls for easier disambiguation

### ISSUE THREAD

**Issue by herveyw** [Microsoft/openenclave#199]
My system has both the real libmbedtls and the OE version. find_package has to be carefully constructed to disambiguate between them, it would be less error prone if the OE version had the oe prefix.

**Comment by CodeMonkeyLeet** [comment]
Likely superseded by work for #401 to consolidate mbedtls libs into oecrypto lib.

**Comment by johnkord** [comment]
This should no longer be relevant by using CMake.
