### ISSUE TITLE
Deprecate unsafe CRT functions. 

### ISSUE THREAD

**Issue by lk2100** [Microsoft/openenclave#215]
This task tracks identifying the use of unsafe CRT functions in the OE code and replacing them with secure equivalents. In particular, this includes:

- [x] Verifying that the OE versions of CRT methods are secure (e.g. we have applied appropriate Spectre1 mitigations)
- [x] Using secure versions of CRT functions (e.g. memset_s rather than memset)
- [x] Upgrading CRT functions to custom methods as required by security context (e.g. use of oe_secure_memcpy, oe_secure_zero_fill rather than memcpy or memset)

To avoid future unsafe use, #28 also tracks adding deprecation warnings as appropriate.

**Comment by CodeMonkeyLeet** [comment]
Resolved by #744
