### ISSUE TITLE
Core Testing: Expand tests for thread binding behavior for enclaves

### ISSUE THREAD

**Issue by CodeMonkeyLeet** [Microsoft/openenclave#24]
We need to flush out the details for behaviors of the enclave APIs and validate them. This includes thread binding behavior and its interactions in multi-threaded scenarios:

- ~~Thread binding correctly avoids deadlocks from thread exhaustion in the enclave~~
    - [x] Thread binding now fails if we exhaust all enclave threads, we should simply verify that host handles this failure gracefully. (Addressed by PR #1023 )
- - [X] Validate implementations of all OE synchronization primitives (Covered with #476 )
- - [X] Stress and load tests for multi-threaded enclave applications (Missing coverage provided with #612 )

**Comment by anitagov** [comment]
Need a test to verify that a reentrant ecall uses the same thread as the original ecall. => This is no longer applicable as reentrancy with ocalls is no longer supported (See Issue #474 ).

**Comment by anitagov** [comment]
Thread binding now fails if we exhaust all enclave threads, we should simply verify that host handles this failure gracefully. => Adding a new test to thread tests to verify this.

**Comment by anitagov** [comment]
PR #1023 adds a new test to verify TCS exhaustion returns OE_OUT_OF_THREADS has been merged to resolved.
The main 3 bullet items have been addressed. So, closing this issue.
