### ISSUE TITLE
App devs have a clear understanding of simulator mode support in Open Enclave

### ISSUE THREAD

**Issue by CodeMonkeyLeet** [Microsoft/openenclave#26]
Document existing level of support for simulator mode and ensure that unsupported functions have a consistent graceful degradation strategy (fail fast or no-op success). We should consider removing support and the Intel dependency entirely if the value of this outweighs the maintenance cost as features are added. 

This story requires extra investigation into effort involved for documenting limits of support and cost to attain Intel parity support for simulator mode.

**Comment by lilyfang** [comment]
Simulation mode will be supported.
