### ISSUE TITLE
sudo make install with the default prefix (/usr/local) installs to locations it should not

### ISSUE THREAD

**Issue by achamayou** [Microsoft/openenclave#382]
Following the build instructions and not setting a prefix, or setting /usr/local for a system-wide install, the OE Makefile installs to the following locations:

$ grep -c "/usr/local/include/mbedtls" install_manifest.txt
70

$ grep -c "/usr/local/include/libc" install_manifest.txt
383

$ grep -c "/usr/local/include/libcxx" install_manifest.txt
175

This is going to come as an extreme and unwelcome surprise to a typical Linux developer, who will quite possibly already have the actual mbedtls library installed for example, and will find some parts of it altered.

All of the headers should instead be under /usr/local/include/openenclave, by default and when selecting /usr/local as a prefix.

**Comment by CodeMonkeyLeet** [comment]
Resolved by #815
