### ISSUE TITLE
App devs have better feature parity when using oelibc 

### ISSUE THREAD

**Issue by CodeMonkeyLeet** [Microsoft/openenclave#413]
Related to #404, once we have layered the oelibc on top of C functions implemented by oecore, we would like to improve the level of functionality provided by the default oelibc library. This includes:

- [x] #151 Investigate test issues for tests/libcxx/tests.broken so we can determine more of what falls in the supported/unsupported feature set.
- [x] #389 Feature request: oe_host_printf: More support for formats

**Comment by anitagov** [comment]
Closing this as #389 has been completed and #151 is almost resolved by me.
