### ISSUE TITLE
App devs can debug enclaves using LLDB

### ISSUE THREAD

**Issue by CodeMonkeyLeet** [Microsoft/openenclave#436]
Closely related to #435. Part of making the statement of supporting Clang for use with Open Enclave should also include its related tools such as the LLDB debugger. The current oe-gdb implementation takes GCC-specific dependencies today to make GDB work in enclaves (i.e. overloading of the `__morestack` function for stack stitching)

This requires further investigation as to the amount of work needed to:
- [ ] Design an LLDB extension that supports debugging (with stack stitching) an enclave
- [ ] Converge oe-gdb implementation where appropriate (and possibly with the events needed for windbg as well)

**Comment by novikov-alexander** [comment]
Hello, I've rewrote existing GDB extension using LLDB Python API and made the PR #997

**Comment by johnkord** [comment]
We're not going to do this (for now).
