### ISSUE TITLE
Using %Iu format specifier causes corrupt output

### ISSUE THREAD

**Issue by technicianted** [Microsoft/openenclave#488]
When using `%Iu` format specifier with `printf` family, the entire output is garbage, even if it occurs at the end of the literal.

To repro, add this line to `attestation.cpp` in the sample:
```c
    printf("******************************\n");
    printf("output is %Iu\n", 123);
    printf("******************************\n");
```

Output will be:
```
******************************
▒       ▒▒▒******************************
```

**Comment by CodeMonkeyLeet** [comment]
Update: We don't provide cross-platform format specifiers anymore as of v0.4.0. The expectation is that the dev understands the compatibility of `printf` specifiers on different platforms; we just invoke the underlying library implementations for this.

**Comment by dthaler** [comment]
I don't think it's reasonable to assume that a TA has to be different for each host OS.   And with TrustZone that would become even more unreasonable.

**Comment by dthaler** [comment]
We want to have a TA that does:
printf("output is %Iu\n", 123);
(or whatever it should be) that will work with both Linux and Windows hosts.   Especially with TrustZone, the TA can be authored and installed independent of any host application, so if you consider a TA server (whether it's like an app store or a company portal or file share etc), the same TA should be able to be installed without knowing which OS the host side is running.
