### ISSUE TITLE
Add timeouts to thread-wait OCALLs

### ISSUE THREAD

**Issue by mikbras** [Microsoft/openenclave#516]
To allow for future support of **pthread_mutex_timedlock()**, timeout arguments should be added to thread-wait OCALLs. These include:
- **OE_OCALL_THREAD_WAIT**
- **OE_OCALL_THREAD_WAKE_WAIT**

The enclave should pass a timeout of zero to the host now (since we plan to support this later).

Both the Windows and Linux implementations accept timeouts (**futex** and **WaitForSingleObjectd()** respectively).

Also, the Windows implementers should consider using **WaitOnAddress()** rather than **WaitForSingleObject()**. (#85)

The other option is to forgo this work with plans to provide the following OCALLs future releases.
- **OE_OCALL_THREAD_TIMED_WAIT**
- **OE_OCALL_THREAD_WAKE_TIMED_WAIT**

Per API review:
* e.g. We can take caller provided timeout parameters, but the OE thread API surface does not need to guarantee them a specific scheduling behavior or that the timeout is respected (timeouts are hints, not guarantees)
* We may choose to only handle the 0 timeout value as a special case (we can reliably return immediately in those cases, effectively behaving like a try-acquire version)

**Comment by johnkord** [comment]
We're going to close this and implement this differently.
