### ISSUE TITLE
Assorted Jenkins CI Improvements

### ISSUE THREAD

**Issue by johnkord** [Microsoft/openenclave#539]
- [x] Perform a merge from master before build/test
- [x] Set up email reporting directed at people who submitted PR and maintainers
- [x] Add clang builds to the build/test matrix
- [x] Jenkins CI documentation
- [x] Add a nightly build of OE with email reporting
- [ ] Puppet or Ansible configuration management for all systems in the Jenkins CI domain
- [x] Enable libc/libcxx tests run at a regular cadence with master and an optional parameter for PR builds
- [ ] Add a testrun for inside a docker container on an ACC VM in hardware mode
- [x] Backups of Jenkins master configuration
- [x] ~~Add a "build passing/failing" button to the main OE github page~~ build never fails with Bors
- [ ] Investigate whether it is possible to change the Jenkins Blue Ocean UI timing that quickly jumps you to the bottom of the page.
- [x] Transition OAuth application to be owned by oeciteam when logging into Jenkins
- [x] Investigate adding bors-NG to automate build-merging
- [x] Replace read/write OECITeam key with read-only deply keys
- [x] Transition all Jenkins CI resources to the same resource group/region so they can all be on the same private network, allowing better security

**Comment by andschwa** [comment]
We have "configuration management" of sorts for the _build_ environment in the sense that we have Dockerfiles describing the state required to build Open Enclave. While it would be _nice to have_ Puppet or Ansible style configuration management of the Jenkins master and nodes (and Bors), we have extensive documentation on the manual setup of the nodes, and the Jenkins master and Bors (and its database) all run out of containers.

**Comment by andschwa** [comment]
Considering this closed now, thanks @johnkord.
