### ISSUE TITLE
libcxx test failures with debug and optimized builds

### ISSUE THREAD

**Issue by anitagov** [Microsoft/openenclave#580]
JenkinsCI runs with libcxx yesterday with the Release/RelWithDebInfo build reported the following 4 new failures:

	3625 - tests/libcxxtest-std_re_re.results_re.results.form_form1.pass (Child aborted)
	3626 - tests/libcxxtest-std_re_re.results_re.results.form_form2.pass (Child aborted)
	3627 - tests/libcxxtest-std_re_re.results_re.results.form_form3.pass (Child aborted)
	3628 - tests/libcxxtest-std_re_re.results_re.results.form_form4.pass (Child aborted)

These 4 tests (form1.pass, form2.pass, form3.pass and form4.pass) are available in: <oe-project-dir>/3rdparty/libcxx\libcxx/test/std/re/re.results/re.results.form

**Info on the JenkinsCI pipeline:**	
https://oe-jenkins.westus2.cloudapp.azure.com/blue/organizations/jenkins/OpenEnclave-libcxx_tests/detail/OpenEnclave-libcxx_tests/1/pipeline 
Please note that this reports 10 failures and 6 of these are being addressed by issue #552

**Comment by CodeMonkeyLeet** [comment]
Resolved by #940
