### ISSUE TITLE
Document need to install sgx driver after kernel update

### ISSUE THREAD

**Issue by gupta-ak** [Microsoft/openenclave#689]
The driver isn't automatically updated when the kernel is updated. As a result, the SGX hardware enclave tests can fail despite having the correct hardware. To fix this, all you have to do is to install the driver again.

@paulcallen  and I have both hit this issue.

**Comment by soccerGB** [comment]
This was mentioned in 
https://github.com/Microsoft/openenclave/blob/master/docs/GettingStartedDocs/install_oe_sdk.md#3-install-the-intel-sgx-dcap-driver
