### ISSUE TITLE
Use of C99 / C11 on Windows

### ISSUE THREAD

**Issue by gupta-ak** [Microsoft/openenclave#749]
MSVC C compiler doesn't support the entire C99 or C11 standards. The most notable C99 feature we use is variable length arrays. For example there are cases similar to the one below that won't compile on MSVC.

```C
void some_function()
{
    size_t buffer_size = 0;

    some_function_to_set_buffer_size(&buffer_size);
    
    {
        uint8_t buffer[buffer_size];
    }
}
```

For future cross-platform C code, we should keep it at C90.

**Comment by mikbras** [comment]
**Update:** Bor-Ming is porting the enclave side to Windows now, so we will have to avoid VLA's for now.

**Comment by johnkord** [comment]
Closing this as won't fix. We have fixed the inconsistency on Windows, but we're not going to convert everything to C90.
