### ISSUE TITLE
Remove `OE_ASM` from `CMakeLists.txt`

### ISSUE THREAD

**Issue by andschwa** [Microsoft/openenclave#755]
Per #731, there are two different things being set:

In `CMakeLists.txt`:

```
if (UNIX)
  set(OE_ASM ASM)
elseif (WIN32)
  set(OE_ASM ASM_MASM)
endif ()
```

This is _only_ used for the language specified to `project()`, which just does an `enable_language()` call. I do not believe this call differentiates between `ASM` and `ASM_MASM`.

In `compiler_settings.cmake`:

```
# Use ML64 as assembler on Windows
if (WIN32)
  set(CMAKE_ASM_MASM_COMPILER "ml64")
endif ()
```

I _believe_ this is the only part that is actually necessary to "pick up" `ml64` on Windows. @sushantstripathi Can you help me test this?

**Comment by sushantstripathi** [comment]
## In CMakeLists.txt:

if (UNIX)
  set(OE_ASM ASM)
elseif (WIN32)
  set(OE_ASM ASM_MASM)
endif ()

project("open-enclave" VERSION ${OE_VERSION} LANGUAGES ${OE_ASM} C CXX)

Here OE_ASM is use to choose the assembler that needs to be taken for compiling during build time depending on OS.

As ASM is used in UNIX and MASM is used in Windows respectively.

## In compiler_settings.cmake:

Use ML64 as assembler on Windows
if (WIN32)
  set(CMAKE_ASM_MASM_COMPILER "ml64")
endif ()

MASM has two versions of the assembler ml (16 bit and 32 bit )  assembly sources and ml64 (64 bit) for 64-bit sources only.

The above line is use to ensure windows *.asm file are compiled using ml64 assembler.
