### ISSUE TITLE
Remove hard-coded output directories

### ISSUE THREAD

**Issue by andschwa** [Microsoft/openenclave#757]
Per #731, in `package_settings.cmake`, we include the module [GNUInstallDirs](https://cmake.org/cmake/help/latest/module/GNUInstallDirs.html), but then don't use it and instead hard-code our own `OE_OUTPUT_DIR` paths which are used throughout CMake.

This should instead be refactored to use CMake's built-ins and GNUInstallDirs, instead of our own hard-coded paths.

**Comment by radhikaj** [comment]
GNUInstall dirs are used when installing the OE package
radhikaj@ubuntu:~/openenclave_install$ ls
bin  include  lib  share
OE_OUTPUT_DIR is used when building OE and generates a subdir called "Output" under the build directory. The directory structure replicates the GNUInstall dir structure
radhikaj@ubuntu:~/oe/build/output$ ls
bin  include lib  share

Are we saying that OE_OUTPUT_DIR should not be used? Where would the lib/bins etc go while building OE?

**Comment by radhikaj** [comment]
GNUInstall dirs are used when installing the OE package
~/openenclave_install$ ls
bin include lib share
OE_OUTPUT_DIR is used when building OE and generates a subdir called "Output" under the build directory. The directory structure replicates the GNUInstall dir structure
~/oe/build/output$ ls
bin include lib share

Are we saying that OE_OUTPUT_DIR should not be used? Where would the lib/bins etc go while building OE?

Should we instead be using LIBRARY_OUTPUT_PATH , EXECUTABLE_OUTPUT_PATH,  CMAKE_ARCHIVE_OUTPUT_DIRECTORY,  CMAKE_LIBRARY_OUTPUT_DIRECTORY etc?

**Comment by andschwa** [comment]
> Are we saying that OE_OUTPUT_DIR should not be used? Where would the lib/bins etc go while building OE?

It shouldn't need to be. CMake defaults to sticking the build artifacts in `CMAKE_CURRENT_BINARY_DIR`, which is `$(build_dir)/mirrored/path/to/place/in/src/tree`.

CMake takes care of linking stuff together and so we shouldn't need to futz with the paths. That is, we the devs should never have to know what path something is at when building, only the target name. Then when installing (or creating a package) the GNUInstall dirs can be used.

**Comment by andschwa** [comment]
I've mostly fixed most of this. We should continue to follow the CMake convention of not caring about the placement of artifacts at build time (only at installation time), and when changes are made to existing targets where the output paths are hard-coded, we should remove that.

So I am closing this in the sense that we are not going to do this as a blanket change, but it is our policy to fix when we can and avoid introducing more hard coded outputs in the future.
