### ISSUE TITLE
Setup ccache correctly in CMake

### ISSUE THREAD

**Issue by andschwa** [Microsoft/openenclave#759]
Per #731, we currently do the following to find and use `ccache`:

```
find_program(CCACHE_FOUND ccache)
if (CCACHE_FOUND)
  set_property(GLOBAL PROPERTY RULE_LAUNCH_COMPILE ccache)
  set_property(GLOBAL PROPERTY RULE_LAUNCH_LINK ccache)
  message("Using ccache")
else ()
  message("ccache not found")
endif (CCACHE_FOUND)
```

However, CMake 3.4+ has better support for this by setting `CMAKE_<LANG>_COMPILER_LAUNCHER` (and we should _not_ be setting `RULE_LAUNCH_LINK`). See [this article](https://crascit.com/2016/04/09/using-ccache-with-cmake/) for more info.

**Comment by aserdean** [comment]
I sent a tentative: https://github.com/Microsoft/openenclave/pull/1374
