### ISSUE TITLE
Prereqs build fails 

### ISSUE THREAD

**Issue by Lusitanian** [Microsoft/openenclave#773]
On a clean pull of master, `sudo make -C prereqs` fails as it pulls in libprotobuf-dev from the Ubuntu repo, which is an older version than the Intel PSW AE needs: 

`g++ -Wnon-virtual-dtor -std=c++11 -fstack-protector-strong -O2 -D_FORTIFY_SOURCE=2 -UDEBUG -DNDEBUG -ffunction-sections -fdata-sections -Wall -Wextra -Winit-self -Wpointer-arith -Wreturn-type -Waddress -Wsequence-point -Wformat-security -Wmissing-include-dirs -Wfloat-equal -Wundef -Wshadow -Wcast-align -Wconversion -Wredundant-decls -DITT_ARCH_IA64 -fPIC -Werror -Wno-unused-parameter -g -DPROTOBUF_INLINE_NOT_IN_HEADERS=0  -I. -I/home/david/Development/openenclave/prereqs/aesm/linux-sgx/common -I/home/david/Development/openenclave/prereqs/aesm/linux-sgx/common/inc -I/home/david/Development/openenclave/prereqs/aesm/linux-sgx/common/inc/internal  -I/home/david/Development/openenclave/prereqs/aesm/linux-sgx/psw/ae/common -I/home/david/Development/openenclave/prereqs/aesm/linux-sgx/psw/ae/inc -I/home/david/Development/openenclave/prereqs/aesm/linux-sgx/psw/ae/inc/internal -I/home/david/Development/openenclave/prereqs/aesm/linux-sgx/sdk/tseal -I/home/david/Development/openenclave/prereqs/aesm/linux-sgx/external/epid-sdk -I../../../psw/ae/common/inc -I../uae_wrapper/inc -I../../../psw/ae/common/proto -I/home/david/Development/openenclave/prereqs/aesm/linux-sgx/psw/ae/aesm_service/source -c ../../../psw/ae/common/src/AECloseSessionRequest.cpp -o AECloseSessionRequest.o
In file included from ../../../psw/ae/common/inc/IAEMessage.h:40:0,
                 from ../../../psw/ae/common/src/AECloseSessionRequest.cpp:38:
../../../psw/ae/common/proto/messages.pb.h:12:2: error: #error This file was generated by a newer version of protoc which is
 #error This file was generated by a newer version of protoc which is
  ^
../../../psw/ae/common/proto/messages.pb.h:13:2: error: #error incompatible with your Protocol Buffer headers. Please update
 #error incompatible with your Protocol Buffer headers.  Please update
  ^
../../../psw/ae/common/proto/messages.pb.h:14:2: error: #error your headers.
 #error your headers.
  ^
In file included from ../../../psw/ae/common/inc/IAEMessage.h:40:0,
                 from ../../../psw/ae/common/src/AECloseSessionRequest.cpp:38:
../../../psw/ae/common/proto/messages.pb.h:23:35: fatal error: google/protobuf/arena.h: No such file or directory
compilation terminated.
`

**Comment by andschwa** [comment]
We believe this has since been resolved as the `make preqreqs` target now install the Intel SGX package, which pulls in the correct protobuf dependency.

```
install: /etc/apt/sources.list.d/intel-sgx.list
	apt-get -y install libsgx-enclave-common libsgx-enclave-common-dev libsgx-dcap-ql libsgx-dcap-ql-dev
```

We no longer
