### ISSUE TITLE
Replace hard-coded certificates in tests with certificates that get generated on-demand

### ISSUE THREAD

**Issue by johnkord** [Microsoft/openenclave#783]
There are plenty of certificates hard-coded into source files (like in tests/crypto/rsa_tests.c) and checked in (like tests/crypto_crls_cert_chains/data/RootCA1.key.pem). 

These certificates should ideally be generated on demand instead, as it is considered bad practice to store certificates in source control.  This should also apply to all private keys that are checked in as well.

**Comment by CodeMonkeyLeet** [comment]
With #927, the only major body of tests left that have checked in certs is `tests\crypto_crls_cert_chains`, we should automate cert generation there as well.

**Comment by soccerliu** [comment]
I think there was some confusion in above comment. In fact, the changes in #927 was only for crypto_crls_cert_chains. It did cover anything outside of that test

**Comment by anakrish** [comment]
@soccerliu There are still certs in the tests.
tests/crypto has certs, crls etc but those are embedded as hex-values within the source code.

**Comment by vishnumohan1991** [comment]
all use cases covered under #1059  closing issue
