### ISSUE TITLE
Check with MSRC if OE emails should have have a prefix

### ISSUE THREAD

**Issue by andschwa** [Microsoft/openenclave#808]
I am not sure how the MSRC team responds to emails. Our current guidelines simply say that any security reports should go to `secure@microsoft.com`, but per #780, we might want to update this with more specific instructions.

/cc @anakrish

**Comment by CodeMonkeyLeet** [comment]
Confirmed with MSRC that the posted guidelines is the recommended protocol for handling security issues.
