### ISSUE TITLE
New libcxx test failures with RelWithDebInfo and clang

### ISSUE THREAD

**Issue by anitagov** [Microsoft/openenclave#823]
The following 2 tests fail with RelWithDebInfo and clang and were part of the full libcxx test suite as reported by the last Jenkins Server run 43 on Oct 3rd 2018

../../3rdparty/libcxx/libcxx/test/libcxx/experimental/containers/sequences/dynarray/dynarray.cons/default_throws_bad_alloc.pass.cpp
../../3rdparty/libcxx/libcxx/test/std/utilities/memory/default.allocator/allocator.members/construct.pass.cpp

These were reported by the Jenkins Server run 43
https://oe-jenkins.westus2.cloudapp.azure.com/blue/organizations/jenkins/OpenEnclave-libcxx_tests/activity/ - Click on 43 and then on the RelWithDebInfo run to view these failures. 
Here is the direct link: https://oe-jenkins.westus2.cloudapp.azure.com/blue/organizations/jenkins/OpenEnclave-libcxx_tests/detail/OpenEnclave-libcxx_tests/43/pipeline/19

**Comment by CodeMonkeyLeet** [comment]
Resolved by #889
