### ISSUE TITLE
Windows: Implement POSIX time functions for Windows

### ISSUE THREAD

**Issue by mikbras** [Microsoft/openenclave#83]
The initial Windows port left the following unimplemented: 
- [ ] HandleStrftTime
- [ ] HandleGettimeofday
- [ ] HandleClockgettime
- [ ] HandleNanosleep

These must be implemented in order for certain libc functions to work correctly. The handler methods should just be wrappers for the libc functions that need to be implemented as part of #402 for Linux.

**Comment by CodeMonkeyLeet** [comment]
Superseded by #459
