### ISSUE TITLE
Issue with libcxx test sized_delete_array_calls_unsized_delete_array.pass.cpp with clang

### ISSUE THREAD

**Issue by anitagov** [Microsoft/openenclave#830]
The following test behaves differently with clang and gcc with C++14 .
3rdparty/libcxx/libcxx/test/std/language.support/support.dynamic/new.delete/new.delete.array/sized_delete_array_calls_unsized_delete_array.pass.cpp.

A little bit of background: C++14 introduces the opportunity to declare a global overload of operator delete suitable for sized deallocation, something which wasn't possible in C++11. This is default behavior with gcc but not with clang v-7. But adding the -fsized-deallocation flag results in different behavior between gcc and clang with this particular test which is sized_delete array that calls unsized_delete.
	
What this test does: The test sized operator [] delete calls the unsized operator [] delete. When sized operator delete [] is not available as in this test(ex C++11) then the unsized operator delete [] should be called directly. With gcc, this is the behavior and the test Passes. However, with clang and the sized deallocation flag, the default delete [] operator is invoked instead of the unsized operator delete [] and the test Fails. Without the sized deallocation flag, the test Passes. 

Filing this issue to mark the anomaly (possible clang bug) and moving this test to unsupported as this is a gray area in the C++14 spec.

References:
C++ Working Draft: N3691 - http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2013/n3691.pdf
Here are the wording changes relative to the C++ Working Draft N3691 for C++14
https://isocpp.org/files/papers/n3778.html#expr.delete
Section 18.6.1.2 Array forms [new.delete.array]

**Comment by anitagov** [comment]
We should probably enable this test for gcc and disable for clang.

**Comment by anitagov** [comment]
@berinpaul - I unassigned myself from this issue. Can you please enabled this test for gcc but keep it disabled in clang? Thanks.

**Comment by berinpaul** [comment]
Sure
