### ISSUE TITLE
Deprecate oe_call_enclave, oe_call_host and oe_call_host_by_address

### ISSUE THREAD

**Issue by dthaler** [Microsoft/openenclave#833]
Asking developers to hard code magic strings is a huge no-no.  The reason is that errors cannot be caught during compilation, and as a result code becomes bug prone as errors are only caught at runtime, so if a particular code path is not exercised in tests, the bug can even go undetected until an end-user hits it and an application crashes, or corrupts data, or whatever else.  As a result, we strongly discourage “magic strings” in any public sample, as they just encourage buggy code.  The oe_call_enclave() api requires magic strings.

Second, the code assumes that the host can actually extract function names from the secure binary.   If you want this to be hardware-agnostic instead of SGX-specific, this is not a realistic assumption, especially if one adds the ability to have private code in a TA (whether TrustZone or SGX or otherwise).

Third, it results in a tiny perf hit to do string lookups for no real benefit.   (The benefit is not code readability, since an enum can give the same benefit with an index.)

With oeedger8r support for generating code that shouldn't need these APIs, they should be removed, or at best deprecated and only present if you #define something that lets you use deprecated APIs.

**Comment by anakrish** [comment]
Initial experimental prototype for function tables being done here: https://github.com/Microsoft/openenclave/compare/anakrish.function_tables

1. Ecall and ocall tables generated on enclave and host side.
2. Calls dispatched using function-id and table.
3. Enclave-side: table registered via global constructor. To be (re) implemented as an extern symbol that oecore uses.
4. On host side, registration happens during oe_create_enclave. oe_create_enclave takes additional parameters (table and table size). oe_create_<encalve-name>_enclave also generated to hide away implementation details.
5. Marshaling strategy has not yet been changed (pointer params will still lead to host-pointers in the marshaling struct).

Note: This is work-in-progress. The details/implementation may change.

**Comment by EMumau** [comment]
The code for oe_call_enclave, oe_call_host, and oe_call_host_by_address was removed in #1521
