### ISSUE TITLE
oe_ocall and oe_ecall APIs need a size argument

### ISSUE THREAD

**Issue by dthaler** [Microsoft/openenclave#834]
There are two types of trusted execution environments: ones where the trusted code can reach out and read/write untrusted memory, and ones where they can't.   We need the ECALL/OCALL mechanism to work for both types.   When they can't, the buffer has to be marshaled across the boundary, which requires knowing the size.   Furthermore, for efficiency, the input and output buffers should be allowed to be separate (for calls that use inout buffers, one could pass the same pointer).  Thus the following APIs is minimally required in order to work on both types of TEE.

    oe_result_t oe_ecall_v2(     oe_enclave_t*     enclave,
                              uint32_t          func,
                              void*             inBuffer,
                              uint32_t          inBufferLength,
                              void*             outBuffer,
                              uint32_t          outBufferLength,
                              uint32_t*         outBufferSizeWritten);

    oe_result_t oe_ocall_v2(     uint32_t          func,
                              const void*       inBuffer,
                              uint32_t          inBufferSize,
                              void*             outBuffer,
                              uint32_t          outBufferSize,
                              uint32_t*         outBufferSizeWritten);

To stage this breaking change into a couple steps, I'd recommend:
1) adding oe_ocall_v2 / oe_ecall_v2
2) changing code generator to generate v2-calling code
3) remove v1 APIs

Note a separate issue will be filed to track agreement on the ocall_table issue, which might also affect these prototypes.

**Comment by paulcallen** [comment]
This was fixed as part of the function-id based work in the edger8r
