### ISSUE TITLE
deprecate oe_get_enclave() 

### ISSUE THREAD

**Issue by dthaler** [Microsoft/openenclave#835]
This API was added for the following reason: if a host uses multiple enclaves, from time to time, those enclaves might make ocalls back to the same host routine, in which case the host needs a way to distinguish which enclave this call is from.  In theory, the host could use a mix of thread contexts and  its own enclave handles for determining source of the ecall.  It was suggested it would make a host’s job easier if an enclave would self-identify itself by sending over its enclave handle as part of the OCall. oe_get_encall() helps the enclave handle available to the enclave itself.

The problem with this is that using oe_get_enclave() requires changes to the EDL file to pass the value back out in an ocall, which means that the enclave developer has to explicitly decide which ocalls to pass it to, and implement it for every one of them.   That’s less efficient, and more complex and arguably more error prone than the alternatives.

The way the Intel SGX SDK deals with that is that the host app registers (via edger8r-generated code) different ocall handlers for each enclave, and the generated code demux’es that way.  Thus, there’s no need to complicate enclave code at all, and the generated code automatically solves the problem for all enclaves.   Any host app that only has one enclave doesn’t notice any complexity at all, no extra “enclave” argument in the ocall to ignore.   Any more complicated app that wants to call the same host app code in response to ocalls from different enclaves, can deal with it themselves without needing oe_get_enclave().

Another way a host+enc app developer can solve the problem themselves without oe_get_enclave() is to have their host app pass a context value (which might be the enclave_t* or might be a pointer to its own app-layer context for that enclave) in ECALLs they define, and then pass that value back in OCALLs they define.   Again, no need for oe_get_enclave().

Hence, a simpler solution that doesn't require EDL changes, and is more interoperable when the host and enclave code are from different organizations, is to follow the same approach used in the Intel SDK, which is that a separate ocall_table pointer is passed into oe_ecall by oeedger8r-generated code.

This requires that the syntax of oe_ocall_v2 include such an argument like so:

    oe_result_t oe_ecall(     oe_enclave_t*     enclave,
                              uint32_t          func,
                              const void*       ocall_table,
                              void*             inBuffer,
                              uint32_t          inBufferLength,
                              void*             outBuffer,
                              uint32_t          outBufferLength,
                              uint32_t*         outBufferSizeWritten);

The ocall_table pointer is not passed into the enclave, but should be used by the host library to demux OCALLs.

Once this API is done, I believe oe_get_enclave() should be deprecated, if not removed.

**Comment by dthaler** [comment]
Now that the ocall_table is in this call, oe_create_enclave() should probably be moved to edger8r/host.h

**Comment by lilyfang** [comment]
We will keep this function instead. It is a pointer of enclave from the host side. There are multiple instances of enclave. If host gets callback from one of these enclave instances, host needs to know the enclave identity.
