### ISSUE TITLE
Add exception handling support on Windows

### ISSUE THREAD

**Issue by CodeMonkeyLeet** [Microsoft/openenclave#839]
In addition to basic Linux-Windows feature parity as tracked in #376, this has other implications for being able to run mbedtls crypto inside enclaves on Windows host. 

The mbedtls library depends on the ability to use CPUID today to determine what crypto instructions are available to it (e.g. AESNI), and OE emulates this for mbedtls by trapping the illegal instruction signal and handling it to return the appropriate CPUID results. 

This task also includes ensuring that the `VectorException` tests are ported to pass on Windows.

**Comment by anitagov** [comment]
#1243 adds Structured Exception Handling on Windows and enables VectorException test on Windows

**Comment by anitagov** [comment]
PR #1372 is to enable mbed tests to work on Windows.

**Comment by anitagov** [comment]
Closing this as I checked in #1372 into master yesterday.
