### ISSUE TITLE
call-twice APIs are an anti-pattern

### ISSUE THREAD

**Issue by dthaler** [Microsoft/openenclave#841]
The Win32 API Design guidelines say:
   5.	Designing variable-sized out parameters
   This applies to functions that have one or more out parameters where: 
   *	the size of the value returned in the out parameter is variable and cannot be known by the user of the function. 
   *	the complete value is being retrieved (not a portion of the value). 
   *	the function is providing a copy of the value (not a reference). 
   Do favor designs that automatically allocate the out parameter values for the user of the function. … 
   Consider using a callback if allocating the out parameters is not acceptable for the scenario. This should be rare 
   Consider providing a separate function to get the length if allocating the out parameters is not acceptable for the scenario.  This should be rare. 
   Do not use the “two-calls-in-one” design, where calling the function one way will tell you the length of the data that will be copied, and calling it another way will actually copy the data

And you see cross-platform standards bodies also following the same rules as above, e.g., the way getaddrinfo() works in POSIX.
And you see other relevant SDKs also following the same rules as above, e.g., Intel’s sgx_get_quote_size() follows the “separate function to get the length” design.
The public OE APIs, e.g., oe_get_report() and oe_get_seal_key(), instead use the “two-calls-in-one” design that shouldn’t be used.

**Comment by paulcallen** [comment]
Checked in.
