### ISSUE TITLE
Name, location, and scope of properties.h header

### ISSUE THREAD

**Issue by dthaler** [Microsoft/openenclave#845]
As the comments at the top of the file say:
0001	/**
0002	 * This file defines the SGX properties for an enclave.
0003	 *
0004	 * The enclave properties should only be defined once for all code compiled
0005	 * into an enclave binary using the OE_SET_ENCLAVE_SGX macro.
0006	 * These properties can be overwritten at sign time by the oesign tool.
0007	 */

This file should either be:
a)	SGX –specific: in this case it need to be renamed to, say, sgxproperties.h not properties.h.   TrustZone properties would go in a separate file, say, tzproperties.h.
b)	Not SGX-specific: in this case, the comments at the top of the file are wrong, and we’d be free to add TrustZone properties into the same file.

Also, these APIs seem to me to be internal, not meant for normal app developers.   If that’s the case, the file should be moved from the bits directory to the internal directory.

**Comment by paulcallen** [comment]
Moved sgx specific stuff from the two properties.h files to an sgx specific version of the file and included on platforms supporting sgx.
