### ISSUE TITLE
APIs to make passing handles generated by an enclave back into the enclave

### ISSUE THREAD

**Issue by dthaler** [Microsoft/openenclave#849]
Enclaves often want to allow host code to reference something in the enclave from a previous call.   The EDL syntax supports [user_check] in ECALLs for this purpose but it's very hard to use securely.  Instead, we should provide enclave APIs to make it easy to do that, since this is such a common desire.

Here’s strawman syntax:
```
// Enclave can call this API to create a handle to pass to the host.
oe_result_t oe_allocate_handle(
    void* secure_address,  /** [in] address to create handle for */
    ptrdiff_t* handle);     /** [out] handle usable by normal world */

// Enclave can call this API to resolve a handle to the secure address.
oe_result_t oe_resolve_handle(
    ptrdiff_t handle,        /** [in] handle from normal world */
    void** secure_address); /** [out] address associated with the handle */

// Enclave can call this API to free a handle, e.g., before it frees the memory the secure_address points to.
void oe_free_handle(
    ptrdiff_t handle);     /** [in] handle to free */
```

**Comment by anakrish** [comment]
In EDL, user_check is used to pass pointers from host to the enclave as well. These could be pointers to shared memory in the host, or pointers that are treated as handles eg FILE*.
Without user_check, the behavior of EDL is to treat the pointer as an array of one element and copy that element over.

**Comment by lilyfang** [comment]
We will not fix this until we have very clear user scenarios and why this is actually needed.
