### ISSUE TITLE
OE_TRACE_DEBUG doesn't compile

### ISSUE THREAD

**Issue by yakman2020** [Microsoft/openenclave#872]
One gets a implicit definition error in compilation.  In trace.h print.h is not included, and oe_host_printf is 
not defined.  To fix, need to do either. 

#ifdef OE_BUILD_ENCLAVE
#include <openenclave/enclave.h>
int oe_host_printf(const char* fmt, ...);  
#define OE_PRINTF oe_host_printf
#else

**Comment by vishnumohan1991** [comment]
Hi in trace.h print.h is included from merged PR #764

**Comment by anakrish** [comment]
Fixed by #862
