### ISSUE TITLE
Rename liboeenclave and introduce new interface target

### ISSUE THREAD

**Issue by letmaik** [Microsoft/openenclave#881]
From the perspective of a developer trying to use Open Enclave via CMake, my intuition (that's not how it is atm) is roughly:
- link against oehost for the host part
- link against oeenclave for the enclave part

There are pkgconfig files that capture this intuition. But when looking at the libraries themselves and the corresponding CMake targets, this intuition is lost and in fact oeenclave is *not* the single thing one has to link against, but it merely contains some "enclave extras": 
https://github.com/Microsoft/openenclave/blob/558e9759c1e453b6f6e2e06aab33a9e80edd1dd2/enclave/README.md#L4-L15

How about refactoring this so that the whole picture is more logical:
- Move enclave/* (except enclave/core) into enclave/extra (or some other name)
- Rename the oeenclave library to oeextra
- Add new oeenclave CMake interface target that behaves like the current pkgconfig counterpart. Adding C++-only parts can be done with generator expressions, e.g. for linking oelibcxx: `$<STREQUAL:$<TARGET_PROPERTY:LINKER_LANGUAGE>,CXX>`.

This simplifies the CMake setup that external projects have to do to start creating enclave projects.

**Comment by CodeMonkeyLeet** [comment]
@letmaik, I'm not clear on the suggested change.
- The README.md file is out of date. The functions in oeenclave are _not_ extraneous. You must link oeenclave today. We may choose a different name for the new library instead.
- If the suggestion is to create a single aggregated .a for linking that contains oeenclave, oembedx509, oembedtls, oelibc and oecore, then that target would be specific to CMake target use, correct?

**Comment by letmaik** [comment]
It's fine to keep the libraries separate, this is just about introducing an interface target in CMake, which acts like a "meta"-package that pulls in other libraries, compile flags etc. to whoever is linking against that interface target. "Linking" here is in the sense of `target_link_libraries`, which isn't equivalent to simple low-level linking. I think @andschwa would have a good idea about that.

Regarding naming, I leave that to you guys. As long as the intent of a library is somehow represented in its name I'm happy.

**Comment by andschwa** [comment]
@letmaik I am going to close this as I think I have completed it. I didn't make any new libraries, but I did make it so `oehost` and `oeenclave` correctly pull in their dependencies. What's more, the `add_enclave` function is going to be made public, and it takes a `CXX` option to also link `oelibcxx`.
