### ISSUE TITLE
Move openenclaverc file under openenclave folder

### ISSUE THREAD

**Issue by CodeMonkeyLeet** [Microsoft/openenclave#893]
The `openenclaverc` file distributed in the SDK is installed directly under the `/opt/openenclave/share` today; this can pollute a user's root share folder if the install was specified to target `/usr` instead. We should move it under `/opt/openenclave/share/openenclave` as is the case with other OE specific files.

**Comment by paulcallen** [comment]
Cut from spec:
The following file APIs are exposed to trusted applications as well.  On SGX, they map to encrypted files stored in the filesystem, such that they can only be decrypted from within the enclave.  On TrustZone, they map to files that are in secure storage, invisible to the normal world.  As such, encryption need not be done by the application.
•	fopen, fflush, ferror, fclose, feof, fread, fseek, ftell, fwrite, fputs, fgets
The following POSIX file enumeration APIs are exposed to trusted applications as well.
•	closedir, opendir, readdir

**Comment by anitagov** [comment]
PR #1087 resolves this. So, closing.
