### ISSUE TITLE
Add support for new C++17 threading tests in libcxx 7.0    

### ISSUE THREAD

**Issue by anitagov** [Microsoft/openenclave#955]
After the libcxx upgrade to libcxx 7.0, libcxxthrd directory was merged with libcxx (PR #974 ). This issue is to discuss adding support for the following 8 new libcxx 7.0 thread tests. These tests use the scoped_lock and shared_mutex C++17 features. The libcxx tests are currently being compiled with the C++14 flag. With the C++17 flag for compilation, the following tests PASS with gcc and clang and the other libcxx tests continue to PASS.

../../3rdparty/libcxx/libcxx/test/std/thread/thread.mutex/thread.lock/thread.lock.scoped/adopt_lock.pass.cpp
../../3rdparty/libcxx/libcxx/test/std/thread/thread.mutex/thread.lock/thread.lock.scoped/mutex.pass.cpp
../../3rdparty/libcxx/libcxx/test/std/thread/thread.mutex/thread.lock/thread.lock.scoped/types.pass.cpp

../../3rdparty/libcxx/libcxx/test/std/thread/thread.mutex/thread.mutex.requirements/thread.shared_mutex.requirements/thread.shared_mutex.class/default.pass.cpp
../../3rdparty/libcxx/libcxx/test/std/thread/thread.mutex/thread.mutex.requirements/thread.shared_mutex.requirements/thread.shared_mutex.class/lock.pass.cpp
../../3rdparty/libcxx/libcxx/test/std/thread/thread.mutex/thread.mutex.requirements/thread.shared_mutex.requirements/thread.shared_mutex.class/lock_shared.pass.cpp
../../3rdparty/libcxx/libcxx/test/std/thread/thread.mutex/thread.mutex.requirements/thread.shared_mutex.requirements/thread.shared_mutex.class/try_lock.pass.cpp
../../3rdparty/libcxx/libcxx/test/std/thread/thread.mutex/thread.mutex.requirements/thread.shared_mutex.requirements/thread.shared_mutex.class/try_lock_shared.pass.cpp

**Comment by anitagov** [comment]
The following threading tests will need to be added to tests.supported after they are proven to be working after the upgrade to libcxx 7.0.

../../3rdparty/libcxx/libcxx/test/std/thread/thread.mutex/thread.lock/thread.lock.scoped/adopt_lock.pass.cpp
../../3rdparty/libcxx/libcxx/test/std/thread/thread.mutex/thread.lock/thread.lock.scoped/mutex.pass.cpp
../../3rdparty/libcxx/libcxx/test/std/thread/thread.mutex/thread.lock/thread.lock.scoped/types.pass.cpp
../../3rdparty/libcxx/libcxx/test/std/thread/thread.mutex/thread.mutex.requirements/thread.shared_mutex.requirements/thread.shared_mutex.class/default.pass.cpp
../../3rdparty/libcxx/libcxx/test/std/thread/thread.mutex/thread.mutex.requirements/thread.shared_mutex.requirements/thread.shared_mutex.class/lock.pass.cpp
../../3rdparty/libcxx/libcxx/test/std/thread/thread.mutex/thread.mutex.requirements/thread.shared_mutex.requirements/thread.shared_mutex.class/lock_shared.pass.cpp
../../3rdparty/libcxx/libcxx/test/std/thread/thread.mutex/thread.mutex.requirements/thread.shared_mutex.requirements/thread.shared_mutex.class/try_lock.pass.cpp
../../3rdparty/libcxx/libcxx/test/std/thread/thread.mutex/thread.mutex.requirements/thread.shared_mutex.requirements/thread.shared_mutex.class/try_lock_shared.pass.cpp

**Comment by anitagov** [comment]
libcxx tests use c++14 but most of the other tests and OE core use c++11. So, we are not switching to using c++17 with libcxx yet.

To reiterate, all these C++17 tests PASS with the c++17 compile switch.

**Comment by anitagov** [comment]
Unassigning this as we are not moving to building libcxx with C++17 at this time.

**Comment by johnkord** [comment]
We're not supporting C++17 yet, so this is closed as won't fix.

**Comment by anitagov** [comment]
@johnkord - I filed this issue to keep track of the tests that need to be added when we upgrade to C++17 in the future. So, would like this to be kept open.
