### ISSUE TITLE
samples do not detect missing edger8r headers

### ISSUE THREAD

**Issue by paulcallen** [Microsoft/openenclave#958]
headers under openenclave/edger8r were missing and samples were working where the validation should have failed. We need to find out why they were passing when they should have not found a header.

**Comment by johnkord** [comment]
@andschwa This is probably related to the samples refactor work in CMake, do you think this should be linked to one of those issues?

**Comment by andschwa** [comment]
@johnkord this issue was from October... @paulcallen can you confirm this repros on top of `master` (or on top of #1472)?
