### ISSUE TITLE
Clarify or change result of oe_create_enclave if initialization fails

### ISSUE THREAD

**Issue by acl33** [Microsoft/openenclave#990]
If I have code such as the following within an enclave (at top level):
```
class Foo {
public:
  Foo() { throw std::runtime_error("Ooops"); }
};

Foo f;
```
Then oe_create_enclave returns success, despite oe_abort having been called (via std::terminate) from the user's initialization code. The failure to initialize is only detected during subsequent attempts to make call-ins, none of which even reach the user code but instead return OE_ENCLAVE_ABORTING. This seems surprising.
[init_abort.zip](https://github.com/Microsoft/openenclave/files/2525441/init_abort.zip)

**Comment by johnkord** [comment]
This is fixed now.
